-------------------------------------**     LibEquippable     **-------------------------------------
-- This file is autogenerated, please do not edit it manually or fuckups might occur.
-------------------------------------**  All Rights Reserved  **-------------------------------------

local LE = LibStub and LibStub("LibEquippable-1.0", true)
if not LE  then return end

local items = {}
local names = {}

items[19295] = {id=19295,name="Darkmoon Flower",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=7930,Recipe=false,RecipeID=0,DropChance=0,Zone="The Killing Fields"}}
items[3360] = {id=3360,name="Stitches' Femur",obtain={NpcID=412,NpcName="Stitches",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=95.1,Zone="Duskwood"}}
items[7344] = {id=7344,name="Torch of Holy Flame",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=55,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[1131] = {id=1131,name="Totem of Infliction",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=101,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[43515] = {id=43515,name="Mystic Tome",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=58565,DropChance=0,Zone=""}}
items[45067] = {id=45067,name="Egg Basket",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=13502,Recipe=false,RecipeID=0,DropChance=0,Zone="The Killing Fields"}}
items[15912] = {id=15912,name="Buccaneer's Orb",obtain={NpcID=335,NpcName="Singe",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Redridge Mountains"}}
items[5323] = {id=5323,name="Everglow Lantern",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=893,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[6341] = {id=6341,name="Eerie Stable Lantern",obtain={NpcID=4278,NpcName="Commander Springvale",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.4,Zone="Shadowfang Keep"}}
items[15972] = {id=15972,name="Ritual Stein",obtain={NpcID=3783,NpcName="Shadethicket Raincaller",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Ashenvale"}}
items[43655] = {id=43655,name="Book of Survival",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59478,DropChance=0,Zone=""}}
items[22784] = {id=22784,name="Sunwell Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=9176,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[15925] = {id=15925,name="Journeyman's Stave",obtain={NpcID=16855,NpcName="Tregla",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.1,Zone="Eversong Woods"}}
items[2943] = {id=2943,name="Eye of Paleth",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=293,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[15973] = {id=15973,name="Watcher's Star",obtain={NpcID=5915,NpcName="Brother Ravenoak",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.3,Zone="Stonetalon Mountains"}}
items[15933] = {id=15933,name="Simple Branch",obtain={NpcID=2065,NpcName="Councilman Cooper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.2,Zone="Silverpine Forest"}}
items[16887] = {id=16887,name="Witch's Finger",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=909,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[1172] = {id=1172,name="Grayson's Torch",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=104,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[15947] = {id=15947,name="Sanguine Star",obtain={NpcID=11682,NpcName="Warsong Grunt",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Ashenvale"}}
items[38579] = {id=38579,name="Venomous Tome",obtain={NpcID=28347,NpcName="Miles Sidney (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Stormwind City"}}
items[15866] = {id=15866,name="Veildust Medicine Bag",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=6124,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[15974] = {id=15974,name="Pagan Rod",obtain={NpcID=5859,NpcName="Hagg Taurenbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="The Barrens"}}
items[43654] = {id=43654,name="Tome of the Dawn",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59475,DropChance=0,Zone=""}}
items[2562] = {id=2562,name="Bouquet of Scarlet Begonias",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=34,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[11855] = {id=11855,name="Tork Wrench",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=3924,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[15926] = {id=15926,name="Spellbinder Orb",obtain={NpcID=3529,NpcName="Moonrage Armorer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.1,Zone="Silverpine Forest"}}
items[7508] = {id=7508,name="Ley Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=1861,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[6182] = {id=6182,name="Dim Torch",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=7364,DropChance=0,Zone=""}}
items[2879] = {id=2879,name="Antipodean Rod",obtain={NpcID=3424,NpcName="Thunderhawk Cloudscraper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="The Barrens"}}
items[5611] = {id=5611,name="Tear of Grief",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=963,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[15969] = {id=15969,name="Beaded Orb",obtain={NpcID=2968,NpcName="Galak Outrunner",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Mulgore"}}
items[15927] = {id=15927,name="Bright Sphere",obtain={NpcID=4464,NpcName="Blackrock Gladiator",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Redridge Mountains"}}
items[9769] = {id=9769,name="Greenweave Branch",obtain={NpcID=11656,NpcName="Warsong Peon",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Ashenvale"}}
items[6898] = {id=6898,name="Orb of Soran'ruk",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=1740,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[15946] = {id=15946,name="Mystic's Sphere",obtain={NpcID=3900,NpcName="Caedakar the Vicious",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Darkshore"}}
items[5183] = {id=5183,name="Pulsating Hydra Heart",obtain={NpcID=3398,NpcName="Gesharahan",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=22.6,Zone="The Barrens"}}
items[15971] = {id=15971,name="Aboriginal Rod",obtain={NpcID=3295,NpcName="Sludge Beast",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.1,Zone="The Barrens"}}
items[15945] = {id=15945,name="Runic Stave",obtain={NpcID=11519,NpcName="Bazzalan",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Ragefire Chasm"}}
items[27398] = {id=27398,name="Carved Crystalline Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=9646,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[23401] = {id=23401,name="Divining Crystal",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=9169,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[15970] = {id=15970,name="Native Branch",obtain={NpcID=12319,NpcName="Burning Blade Toxicologist",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.7,Zone="The Barrens"}}
items[15932] = {id=15932,name="Disciple's Stein",obtain={NpcID=16854,NpcName="Eldinarcus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.1,Zone="Eversong Woods"}}
items[15944] = {id=15944,name="Ancestral Orb",obtain={NpcID=6128,NpcName="Vorlus Vilehoof",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Teldrassil"}}
items[4837] = {id=4837,name="Strength of Will",obtain={NpcID=3134,NpcName="Kzixx (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Duskwood"}}
items[9800] = {id=9800,name="Ivy Orb",obtain={NpcID=6230,NpcName="Peacekeeper Security Suit",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Gnomeregan"}}
items[13031] = {id=13031,name="Orb of Mistmantle",obtain={NpcID=15814,NpcName="Qiraji Lieutenant Jo-rel",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=7.5,Zone="The Barrens"}}
items[4836] = {id=4836,name="Fireproof Orb",obtain={NpcID=3134,NpcName="Kzixx (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Duskwood"}}
items[4838] = {id=4838,name="Orb of Power",obtain={NpcID=3134,NpcName="Kzixx (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Duskwood"}}
items[7558] = {id=7558,name="Shimmering Stave",obtain={NpcID=6392,NpcName="Holdout Medic",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Gnomeregan"}}
items[7608] = {id=7608,name="Seer's Fine Stein",obtain={NpcID=2477,NpcName="Gradok",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.9,Zone="Loch Modan"}}
items[15206] = {id=15206,name="Jadefinger Baton",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=5321,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[7554] = {id=7554,name="Willow Branch",obtain={NpcID=16358,NpcName="Kel'gash the Wicked",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Ghostlands"}}
items[3451] = {id=3451,name="Nightglow Concoction",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=451,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[7559] = {id=7559,name="Runic Cane",obtain={NpcID=5838,NpcName="Brokespear",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=20.5,Zone="The Barrens"}}
items[7507] = {id=7507,name="Arcane Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=1880,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[6654] = {id=6654,name="Torch of the Eternal Flame",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=1526,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[4984] = {id=4984,name="Skull of Impending Doom",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=737,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[43663] = {id=43663,name="Stormbound Tome",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59493,DropChance=0,Zone=""}}
items[10796] = {id=10796,name="Drakestone",obtain={NpcID=5722,NpcName="Hazzas",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.1,Zone="The Temple of Atal'Hakkar"}}
items[43656] = {id=43656,name="Tome of Kings",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59484,DropChance=0,Zone=""}}
items[43664] = {id=43664,name="Manual of Clouds",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59494,DropChance=0,Zone=""}}
items[43660] = {id=43660,name="Fire Eater's Guide",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59489,DropChance=0,Zone=""}}
items[7515] = {id=7515,name="Celestial Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=1958,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[11904] = {id=11904,name="Spirit of Aquementas",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=3962,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[13030] = {id=13030,name="Basilisk Bone",obtain={NpcID=15741,NpcName="Colossus of Regal",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=25.0,Zone="Silithus"}}
items[7557] = {id=7557,name="Gossamer Rod",obtain={NpcID=8497,NpcName="Nightmare Suppressor",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="The Temple of Atal'Hakkar"}}
items[9393] = {id=9393,name="Beacon of Hope",obtain={NpcID=4872,NpcName="Obsidian Golem",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Badlands"}}
items[43657] = {id=43657,name="Royal Guide of Escape Routes",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59486,DropChance=0,Zone=""}}
items[43661] = {id=43661,name="Book of Stars",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59490,DropChance=0,Zone=""}}
items[13029] = {id=13029,name="Umbral Crystal",obtain={NpcID=2925,NpcName="Silvermane Howler",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="The Hinterlands"}}
items[7749] = {id=7749,name="Omega Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=1049,Recipe=false,RecipeID=0,DropChance=0,Zone="Sharptalon's Claw"}}
items[1992] = {id=1992,name="Swampchill Fetish",obtain={NpcID=3976,NpcName="Scarlet Commander Mograine",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Scarlet Monastery"}}
items[15966] = {id=15966,name="Venomshroud Orb",obtain={NpcID=8198,NpcName="Tick",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Tanaris"}}
items[17737] = {id=17737,name="Cloud Stone",obtain={NpcID=12203,NpcName="Landslide",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=23.9,Zone="Maraudon"}}
items[11625] = {id=11625,name="Enthralled Sphere",obtain={NpcID=9018,NpcName="High Interrogator Gerstahn",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=19.7,Zone="Blackrock Depths"}}
items[15983] = {id=15983,name="Gaea's Scepter",obtain={NpcID=193,NpcName="Blue Dragonspawn",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Azshara"}}
items[19115] = {id=19115,name="Flask of Forest Mojo",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=7847,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[9644] = {id=9644,name="Thermotastic Egg Timer",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=648,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[5028] = {id=5028,name="Lord Sakrasis' Scepter",obtain={NpcID=2541,NpcName="Lord Sakrasis",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=50.2,Zone="Stranglethorn Vale"}}
items[9627] = {id=9627,name="Explorers' League Lodestar",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=2240,Recipe=false,RecipeID=0,DropChance=0,Zone="Sharptalon's Claw"}}
items[15107] = {id=15107,name="Orb of Noh'Orahil",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=4975,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[7685] = {id=7685,name="Orb of the Forgotten Seer",obtain={NpcID=4543,NpcName="Bloodmage Thalnos",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=49.6,Zone="Scarlet Monastery"}}
items[33266] = {id=33266,name="Book of the Adept",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=11147,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[15976] = {id=15976,name="Thistlefur Branch",obtain={NpcID=12976,NpcName="Kolkar Waylayer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Desolace"}}
items[2565] = {id=2565,name="Rod of Molten Fire",obtain={NpcID=23637,NpcName="Deserter Lieutenant",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Dustwallow Marsh"}}
items[15857] = {id=15857,name="Magebane Scion",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=5942,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[18762] = {id=18762,name="Shard of the Green Flame",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=7603,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[15979] = {id=15979,name="Embersilk Stave",obtain={NpcID=4328,NpcName="Firemane Scalebane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Dustwallow Marsh"}}
items[6774] = {id=6774,name="Uthek's Finger",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=1380,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[15918] = {id=15918,name="Conjurer's Sphere",obtain={NpcID=15070,NpcName="Vinchaxa",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.2,Zone="Stranglethorn Vale"}}
items[15962] = {id=15962,name="Satyr's Rod",obtain={NpcID=7404,NpcName="Galak Flame Guard",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.1,Zone="Thousand Needles"}}
items[15934] = {id=15934,name="Sage's Stave",obtain={NpcID=1200,NpcName="Morbent Fel",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Duskwood"}}
items[2944] = {id=2944,name="Cursed Eye of Paleth",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[15936] = {id=15936,name="Duskwoven Branch",obtain={NpcID=9680,NpcName="Crest Killer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Blackrock Depths"}}
items[9944] = {id=9944,name="Abjurer's Crystal",obtain={NpcID=9028,NpcName="Grizzle",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Blackrock Depths"}}
items[10708] = {id=10708,name="Skullspell Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=3461,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[15937] = {id=15937,name="Hibernal Sphere",obtain={NpcID=8497,NpcName="Nightmare Suppressor",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="The Temple of Atal'Hakkar"}}
items[15982] = {id=15982,name="Bloodwoven Rod",obtain={NpcID=6502,NpcName="Plated Stegodon",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Un'Goro Crater"}}
items[15965] = {id=15965,name="Windchaser Orb",obtain={NpcID=193,NpcName="Blue Dragonspawn",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Azshara"}}
items[12471] = {id=12471,name="Desertwalker Cane",obtain={NpcID=10081,NpcName="Dustwraith",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=21.7,Zone="Zul'Farrak"}}
items[15981] = {id=15981,name="Lunar Sphere",obtain={NpcID=5360,NpcName="Deep Strider",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Feralas"}}
items[15980] = {id=15980,name="Darkmist Orb",obtain={NpcID=6193,NpcName="Spitelash Screamer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Azshara"}}
items[7611] = {id=7611,name="Mistscape Stave",obtain={NpcID=5280,NpcName="Nightmare Wyrmkin",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="The Temple of Atal'Hakkar"}}
items[7555] = {id=7555,name="Regal Star",obtain={NpcID=17235,NpcName="Witch Doctor Mai'jin",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="The Hinterlands"}}
items[15964] = {id=15964,name="Silksand Star",obtain={NpcID=5402,NpcName="Khan Hratha",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Desolace"}}
items[6803] = {id=6803,name="Prophetic Cane",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=14355,Recipe=false,RecipeID=0,DropChance=0,Zone="Sharptalon's Claw"}}
items[15978] = {id=15978,name="Geomancer's Rod",obtain={NpcID=11781,NpcName="Ambershard Crusher",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Desolace"}}
items[7610] = {id=7610,name="Aurora Sphere",obtain={NpcID=2571,NpcName="Boulderfist Lord",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Arathi Highlands"}}
items[15108] = {id=15108,name="Orb of Dar'Orahil",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=4964,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[15977] = {id=15977,name="Vital Orb",obtain={NpcID=23590,NpcName="Defias Conjuror",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Dustwallow Marsh"}}
items[15929] = {id=15929,name="Nightsky Orb",obtain={NpcID=4063,NpcName="Feeboz",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Arathi Highlands"}}
items[15935] = {id=15935,name="Durable Rod",obtain={NpcID=757,NpcName="Lost One Fisherman",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Swamp of Sorrows"}}
items[15928] = {id=15928,name="Silver-thread Rod",obtain={NpcID=1200,NpcName="Morbent Fel",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Duskwood"}}
items[15975] = {id=15975,name="Raincaller Scepter",obtain={NpcID=17300,NpcName="Gorgannon",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Ashenvale"}}
items[10709] = {id=10709,name="Pyrestone Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=3507,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[11870] = {id=11870,name="Oblivion Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=4510,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[9914] = {id=9914,name="Royal Scepter",obtain={NpcID=678,NpcName="Mosh'Ogg Mauler",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Stranglethorn Vale"}}
items[11859] = {id=11859,name="Jademoon Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=2976,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[11262] = {id=11262,name="Orb of Lorica",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=1053,Recipe=false,RecipeID=0,DropChance=0,Zone="Sharptalon's Claw"}}
items[9882] = {id=9882,name="Sorcerer Sphere",obtain={NpcID=2640,NpcName="Vilebranch Witch Doctor",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="The Hinterlands"}}
items[4125] = {id=4125,name="Tranquil Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=206,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[10770] = {id=10770,name="Mordresh's Lifeless Skull",obtain={NpcID=7357,NpcName="Mordresh Fire Eye",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=32.8,Zone="Razorfen Downs"}}
items[7556] = {id=7556,name="Twilight Orb",obtain={NpcID=2420,NpcName="Targ",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Alterac Mountains"}}
items[15963] = {id=15963,name="Stonecloth Branch",obtain={NpcID=23590,NpcName="Defias Conjuror",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Dustwallow Marsh"}}
items[7609] = {id=7609,name="Elder's Amber Stave",obtain={NpcID=943,NpcName="Kurzen Wrangler",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Stranglethorn Vale"}}
items[45854] = {id=45854,name="Rituals of the New Moon",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=64051,DropChance=0,Zone=""}}
items[35609] = {id=35609,name="Talisman of Scourge Command",obtain={NpcID=29308,NpcName="Prince Taldaram",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=33.0,Zone="Ahn'kahet: The Old Kingdom"}}
items[37024] = {id=37024,name="Medicine Stick",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=11613,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[18602] = {id=18602,name="Tome of Sacrifice",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=7583,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[45849] = {id=45849,name="Twilight Tome",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=64053,DropChance=0,Zone=""}}
items[36462] = {id=36462,name="Coldarra Crystal",obtain={NpcID=27949,NpcName="Alliance Commander",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.2,Zone="The Nexus"}}
items[35858] = {id=35858,name="Tome of Alacrity",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=11307,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[45850] = {id=45850,name="Rituals of the New Moon",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[45010] = {id=45010,name="Mining: The Pick and You",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[13353] = {id=13353,name="Book of the Dead",obtain={NpcID=10812,NpcName="Grand Crusader Dathrohan",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.8,Zone="Stratholme"}}
items[36461] = {id=36461,name="Demon-Skull Orb",obtain={NpcID=26333,NpcName="Corrupted Lothalor Ancient",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Dragonblight"}}
items[4696] = {id=4696,name="Lapidis Tankard of Tidesippe",obtain={NpcID=15741,NpcName="Colossus of Regal",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=25.0,Zone="Silithus"}}
items[37817] = {id=37817,name="Branch of Sinful Reprieve",obtain={NpcID=27860,NpcName="Luthion the Vile",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.8,Zone="Borean Tundra"}}
items[30857] = {id=30857,name="Deep Core Lantern",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10630,Recipe=false,RecipeID=0,DropChance=0,Zone="A Rogue's Deal"}}
items[15986] = {id=15986,name="Bonecaster's Star",obtain={NpcID=14308,NpcName="Ferra",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Dire Maul"}}
items[45853] = {id=45853,name="Rituals of the New Moon",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[36465] = {id=36465,name="Evergreen Branch",obtain={NpcID=26828,NpcName="Magister Keldonus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.7,Zone="Dragonblight"}}
items[34206] = {id=34206,name="Book of Highborne Hymns",obtain={NpcID=25166,NpcName="Grand Warlock Alythess",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=18.3,Zone="Sunwell Plateau"}}
items[29269] = {id=29269,name="Sapphiron's Wing Bone",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[21597] = {id=21597,name="Royal Scepter of Vek'lor",obtain={NpcID=15276,NpcName="Emperor Vek'lor",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=8.1,Zone="Ahn'Qiraj"}}
items[21666] = {id=21666,name="Sartura's Might",obtain={NpcID=15516,NpcName="Battleguard Sartura",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=8.4,Zone="Ahn'Qiraj"}}
items[15989] = {id=15989,name="Eternal Rod",obtain={NpcID=6109,NpcName="Azuregos",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=3.1,Zone="Azshara"}}
items[43666] = {id=43666,name="Hellfire Tome",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59495,DropChance=0,Zone=""}}
items[19315] = {id=19315,name="Therazane's Touch",obtain={NpcID=13216,NpcName="Gaelden Hammersmith (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[15930] = {id=15930,name="Imperial Red Scepter",obtain={NpcID=9678,NpcName="Shill Dinger",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Blackrock Depths"}}
items[45852] = {id=45852,name="Rituals of the New Moon",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[35598] = {id=35598,name="Tome of the Lore Keepers",obtain={NpcID=26763,NpcName="Anomalus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=31.8,Zone="The Nexus"}}
items[39124] = {id=39124,name="Branch of Insightful Dreams",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=12152,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[37033] = {id=37033,name="Manual of the Tides",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=11968,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[31715] = {id=31715,name="Demoniac Soul Prison",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10838,Recipe=false,RecipeID=0,DropChance=0,Zone="A Rogue's Deal"}}
items[45851] = {id=45851,name="Rituals of the New Moon",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[36464] = {id=36464,name="Darkened Scepter",obtain={NpcID=26862,NpcName="Anthis",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.8,Zone="Grizzly Hills"}}
items[38293] = {id=38293,name="Suntouched Flowers",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=12140,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[38217] = {id=38217,name="Tome of the Violet Tower",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=12107,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[36459] = {id=36459,name="Icy Orb",obtain={NpcID=24215,NpcName="Jlarborn the Strategist",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Howling Fjord"}}
items[27534] = {id=27534,name="Hortus' Seal of Brilliance",obtain={NpcID=16808,NpcName="Warchief Kargath Bladefist",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=14.3,Zone="The Shattered Halls"}}
items[29270] = {id=29270,name="Flametongue Seal",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[31823] = {id=31823,name="Book of Many Blessings",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10921,Recipe=false,RecipeID=0,DropChance=0,Zone="A Rogue's Deal"}}
items[25090] = {id=25090,name="Slavehandler Rod",obtain={NpcID=19354,NpcName="Arzeth the Merciless",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Hellfire Peninsula"}}
items[25088] = {id=25088,name="Laughing Skull Orb",obtain={NpcID=19312,NpcName="Drillmaster Zurok",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Hellfire Peninsula"}}
items[25086] = {id=25086,name="Dreamseeker Dandelion",obtain={NpcID=19261,NpcName="Infernal Warbringer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Hellfire Peninsula"}}
items[17067] = {id=17067,name="Ancient Cornerstone Grimoire",obtain={NpcID=10184,NpcName="Onyxia",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=21.4,Zone="Onyxia's Lair"}}
items[19312] = {id=19312,name="Lei of the Lifegiver",obtain={NpcID=13216,NpcName="Gaelden Hammersmith (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[43667] = {id=43667,name="Book of Clever Tricks",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59496,DropChance=0,Zone=""}}
items[15938] = {id=15938,name="Mystical Orb",obtain={NpcID=10584,NpcName="Urok Doomhowl",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Blackrock Spire"}}
items[38224] = {id=38224,name="Life Binder Talisman",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=12151,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[38214] = {id=38214,name="Hypergizmatic Energy Booster",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=11701,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[28387] = {id=28387,name="Lamp of Peaceful Repose",obtain={NpcID=20885,NpcName="Dalliah the Doomsayer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=18.5,Zone="The Arcatraz"}}
items[29274] = {id=29274,name="Tears of Heaven",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[31493] = {id=31493,name="Netherwing Spiritualist's Charm",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10870,Recipe=false,RecipeID=0,DropChance=0,Zone="A Rogue's Deal"}}
items[29170] = {id=29170,name="Windcaller's Orb",obtain={NpcID=17904,NpcName="Fedryen Swiftspear (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Zangarmarsh"}}
items[25091] = {id=25091,name="Mistyreed Torch",obtain={NpcID=17846,NpcName="Pit Spectator",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=3.2,Zone="Unknown"}}
items[23048] = {id=23048,name="Sapphiron's Right Eye",obtain={NpcID=15989,NpcName="Sapphiron",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=3.2,Zone="Naxxramas"}}
items[23469] = {id=23469,name="High Warlord's Tome of Mending",obtain={NpcID=12794,NpcName="Stone Guard Zarg (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Orgrimmar"}}
items[18695] = {id=18695,name="Spellbound Tome",obtain={NpcID=10508,NpcName="Ras Frostwhisper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=15.2,Zone="Scholomance"}}
items[15931] = {id=15931,name="Arcane Star",obtain={NpcID=10439,NpcName="Ramstein the Gorger",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Stratholme"}}
items[18425] = {id=18425,name="Kreeg's Mug",obtain={NpcID=14322,NpcName="Stomper Kreeg",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=53.5,Zone="Dire Maul"}}
items[18672] = {id=18672,name="Elemental Ember",obtain={NpcID=14461,NpcName="Baron Charr",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=45.5,Zone="Un'Goro Crater"}}
items[15985] = {id=15985,name="Arachnidian Branch",obtain={NpcID=14351,NpcName="Gordok Bushwacker",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Dire Maul"}}
items[35016] = {id=35016,name="Brutal Gladiator's Grimoire",obtain={NpcID=26352,NpcName="Big Zokk Torquewrench (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Netherstorm"}}
items[34179] = {id=34179,name="Heart of the Pit",obtain={NpcID=25158,NpcName="Brutallus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=40.0,Zone="Unknown"}}
items[30872] = {id=30872,name="Chronicle of Dark Secrets",obtain={NpcID=17767,NpcName="Rage Winterchill",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=16.1,Zone="Hyjal Summit"}}
items[28346] = {id=28346,name="Gladiator's Endgame",obtain={NpcID=18898,NpcName="Explodyne Fizzlespurt (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Nagrand"}}
items[28213] = {id=28213,name="Lordaeron Medical Guide",obtain={NpcID=17848,NpcName="Lieutenant Drake",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.0,Zone="Old Hillsbrad Foothills"}}
items[29272] = {id=29272,name="Orb of the Soul-Eater",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[29273] = {id=29273,name="Khadgar's Knapsack",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[31494] = {id=31494,name="Netherwing Sorceror's Charm",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10870,Recipe=false,RecipeID=0,DropChance=0,Zone="A Rogue's Deal"}}
items[32651] = {id=32651,name="Crystal Orb of Enlightenment",obtain={NpcID=23428,NpcName="Jho'nass (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Blade's Edge Mountains"}}
items[25094] = {id=25094,name="Eldr'naan Scepter",obtain={NpcID=22160,NpcName="Bloodmaul Taskmaster",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Blade's Edge Mountains"}}
items[31732] = {id=31732,name="Unearthed Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10887,Recipe=false,RecipeID=0,DropChance=0,Zone="A Rogue's Deal"}}
items[23049] = {id=23049,name="Sapphiron's Left Eye",obtain={NpcID=15989,NpcName="Sapphiron",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=3.0,Zone="Naxxramas"}}
items[15988] = {id=15988,name="Resplendent Orb",obtain={NpcID=12129,NpcName="Onyxian Warder",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Unknown"}}
items[15805] = {id=15805,name="Penelope's Rose",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=5384,Recipe=false,RecipeID=0,DropChance=0,Zone="Sharptalon's Claw"}}
items[36467] = {id=36467,name="Reflecting Sphere",obtain={NpcID=28034,NpcName="Drakkari Snake Handler",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Zul'Drak"}}
items[35074] = {id=35074,name="Brutal Gladiator's Reprieve",obtain={NpcID=26352,NpcName="Big Zokk Torquewrench (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Netherstorm"}}
items[35008] = {id=35008,name="Brutal Gladiator's Endgame",obtain={NpcID=26352,NpcName="Big Zokk Torquewrench (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Netherstorm"}}
items[36463] = {id=36463,name="Polished Orb",obtain={NpcID=27508,NpcName="Necrolord Amarion",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.7,Zone="Dragonblight"}}
items[32350] = {id=32350,name="Touch of Inspiration",obtain={NpcID=23420,NpcName="Essence of Anger",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=15.8,Zone="Black Temple"}}
items[32361] = {id=32361,name="Blind-Seers Icon",obtain={NpcID=22841,NpcName="Shade of Akama",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=12.6,Zone="Black Temple"}}
items[32961] = {id=32961,name="Merciless Gladiator's Reprieve",obtain={NpcID=12782,NpcName="Captain O'Neal (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[33325] = {id=33325,name="Voodoo Shaker",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[33334] = {id=33334,name="Fetish of the Primal Gods",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[29923] = {id=29923,name="Talisman of the Sun King",obtain={NpcID=19514,NpcName="Al'ar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=19.0,Zone="Tempest Keep"}}
items[30049] = {id=30049,name="Fathomstone",obtain={NpcID=21932,NpcName="Hydross the Unstable",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=24.2,Zone="Unknown"}}
items[199710] = {id=199710,name="Collective Rose",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[25098] = {id=25098,name="Tuurik Torch",obtain={NpcID=20911,NpcName="Blackwing Drakonaar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.2,Zone="The Arcatraz"}}
items[27477] = {id=27477,name="Faol's Signet of Cleansing",obtain={NpcID=17308,NpcName="Omor the Unscarred",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=3.6,Zone="Hellfire Ramparts"}}
items[29330] = {id=29330,name="The Saga of Terokk",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10098,Recipe=false,RecipeID=0,DropChance=0,Zone="A Rogue's Deal"}}
items[27714] = {id=27714,name="Swamplight Lantern",obtain={NpcID=17942,NpcName="Quagmirran",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=7.4,Zone="The Slave Pens"}}
items[28941] = {id=28941,name="Grand Marshal's Battletome",obtain={NpcID=12782,NpcName="Captain O'Neal (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[25097] = {id=25097,name="Astralaan Orb",obtain={NpcID=23222,NpcName="Bonechewer Brawler",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.1,Zone="Black Temple"}}
items[31699] = {id=31699,name="Imbued Draenethyst Crystal",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10857,Recipe=false,RecipeID=0,DropChance=0,Zone="A Rogue's Deal"}}
items[31731] = {id=31731,name="Mekeda's Gift",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10887,Recipe=false,RecipeID=0,DropChance=0,Zone="A Rogue's Deal"}}
items[25092] = {id=25092,name="Consortium Crystal",obtain={NpcID=17814,NpcName="Lordaeron Watchman",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Unknown"}}
items[25089] = {id=25089,name="Supplicant's Rod",obtain={NpcID=19312,NpcName="Drillmaster Zurok",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Hellfire Peninsula"}}
items[25087] = {id=25087,name="Bleeding Eye",obtain={NpcID=17455,NpcName="Bonechewer Beastmaster",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Hellfire Ramparts"}}
items[19366] = {id=19366,name="Master Dragonslayer's Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=7782,Recipe=false,RecipeID=0,DropChance=0,Zone="Quests"}}
items[22937] = {id=22937,name="Gem of Nerubis",obtain={NpcID=15956,NpcName="Anub'Rekhan",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=10.8,Zone="Naxxramas"}}
items[22994] = {id=22994,name="Digested Hand of Power",obtain={NpcID=15932,NpcName="Gluth",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.9,Zone="Naxxramas"}}
items[23029] = {id=23029,name="Noth's Frigid Heart",obtain={NpcID=15954,NpcName="Noth the Plaguebringer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=8.3,Zone="Naxxramas"}}
items[23452] = {id=23452,name="Grand Marshal's Tome of Power",obtain={NpcID=12784,NpcName="Lieutenant Jackspring (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Stormwind City"}}
items[23453] = {id=23453,name="Grand Marshal's Tome of Restoration",obtain={NpcID=12784,NpcName="Lieutenant Jackspring (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Stormwind City"}}
items[23462] = {id=23462,name="High Warlord's Tome of Destruction",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[23468] = {id=23468,name="High Warlord's Tome of Destruction",obtain={NpcID=12794,NpcName="Stone Guard Zarg (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Orgrimmar"}}
items[20582] = {id=20582,name="Trance Stone",obtain={NpcID=14887,NpcName="Ysondre",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=16.3,Zone="Duskwood"}}
items[19142] = {id=19142,name="Fire Runed Grimoire",obtain={NpcID=11982,NpcName="Magmadar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=6.3,Zone="Molten Core"}}
items[21471] = {id=21471,name="Talon of Furious Concentration",obtain={NpcID=15340,NpcName="Moam",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.6,Zone="Ruins of Ahn'Qiraj"}}
items[19922] = {id=19922,name="Arlokk's Hoodoo Stick",obtain={NpcID=14515,NpcName="High Priestess Arlokk",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=24.4,Zone="Zul'Gurub"}}
items[19891] = {id=19891,name="Jin'do's Bag of Whammies",obtain={NpcID=11380,NpcName="Jin'do the Hexxer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=14.4,Zone="Zul'Gurub"}}
items[19308] = {id=19308,name="Tome of Arcane Domination",obtain={NpcID=13216,NpcName="Gaelden Hammersmith (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[19309] = {id=19309,name="Tome of Shadow Force",obtain={NpcID=13216,NpcName="Gaelden Hammersmith (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[19310] = {id=19310,name="Tome of the Ice Lord",obtain={NpcID=13216,NpcName="Gaelden Hammersmith (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[19311] = {id=19311,name="Tome of Fiery Arcana",obtain={NpcID=13216,NpcName="Gaelden Hammersmith (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[15942] = {id=15942,name="Master's Rod",obtain={NpcID=18338,NpcName="Highlord Kruul",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.5,Zone="Searing Gorge"}}
items[15941] = {id=15941,name="High Councillor's Scepter",obtain={NpcID=12464,NpcName="Death Talon Seether",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Blackwing Lair"}}
items[15968] = {id=15968,name="Elunarian Sphere",obtain={NpcID=15235,NpcName="Vekniss Stinger",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Ahn'Qiraj"}}
items[18523] = {id=18523,name="Brightly Glowing Stone",obtain={NpcID=11501,NpcName="King Gordok",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=24.2,Zone="Dire Maul"}}
items[21185] = {id=21185,name="Earthcalm Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=8574,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[23156] = {id=23156,name="Blackwood's Thigh",obtain={NpcID=14695,NpcName="Lord Blackwood",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=26.7,Zone="Scholomance"}}
items[15940] = {id=15940,name="Elegant Scepter",obtain={NpcID=10439,NpcName="Ramstein the Gorger",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Stratholme"}}
items[15987] = {id=15987,name="Astral Orb",obtain={NpcID=12476,NpcName="Emeraldon Oracle",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Ashenvale"}}
items[22319] = {id=22319,name="Tome of Divine Right",obtain={NpcID=16080,NpcName="Mor Grayhoof",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=20.3,Zone="Blackrock Spire"}}
items[13385] = {id=13385,name="Tome of Knowledge",obtain={NpcID=10811,NpcName="Archivist Galford",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=13.6,Zone="Stratholme"}}
items[11928] = {id=11928,name="Thaurissan's Royal Scepter",obtain={NpcID=9019,NpcName="Emperor Dagran Thaurissan",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=18.7,Zone="Blackrock Depths"}}
items[20694] = {id=20694,name="Glowing Black Orb",obtain={NpcID=15184,NpcName="Cenarion Hold Infantry",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.2,Zone="Silithus"}}
items[15939] = {id=15939,name="Councillor's Scepter",obtain={NpcID=11143,NpcName="Postmaster Malown",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Stratholme"}}
items[15967] = {id=15967,name="Highborne Star",obtain={NpcID=11465,NpcName="Warpwood Stomper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Dire Maul"}}
items[18536] = {id=18536,name="Milli's Lexicon",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=5526,Recipe=false,RecipeID=0,DropChance=0,Zone="Kanrethad's Quest"}}
items[15984] = {id=15984,name="Opulent Scepter",obtain={NpcID=6129,NpcName="Draconic Magelord",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Azshara"}}
items[39827] = {id=39827,name="Vile Tome of Tenets",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=12596,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[38755] = {id=38755,name="Scepter of Passionate Reprisal",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=12134,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[39118] = {id=39118,name="Glowing Voodoo Orb",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=12152,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[33736] = {id=33736,name="Vengeful Gladiator's Reprieve",obtain={NpcID=20278,NpcName="Vixton Pinchwhistle (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Netherstorm"}}
items[31978] = {id=31978,name="Merciless Gladiator's Endgame",obtain={NpcID=12782,NpcName="Captain O'Neal (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[36460] = {id=36460,name="Northern Star",obtain={NpcID=24238,NpcName="Bjorn Halgurdsson",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.8,Zone="Howling Fjord"}}
items[32452] = {id=32452,name="Gladiator's Reprieve",obtain={NpcID=18898,NpcName="Explodyne Fizzlespurt (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Nagrand"}}
items[25099] = {id=25099,name="Draenei Crystal Rod",obtain={NpcID=21304,NpcName="Warder Corpse",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.3,Zone="The Arcatraz"}}
items[32533] = {id=32533,name="Karrog's Shard",obtain={NpcID=23165,NpcName="Karrog",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=18.5,Zone="Terokkar Forest"}}
items[28728] = {id=28728,name="Aran's Soothing Sapphire",obtain={NpcID=16524,NpcName="Shade of Aran",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=15.5,Zone="Karazhan"}}
items[28412] = {id=28412,name="Lamp of Peaceful Radiance",obtain={NpcID=21466,NpcName="Harbinger Skyriss",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=20.7,Zone="The Arcatraz"}}
items[28187] = {id=28187,name="Star-Heart Lamp",obtain={NpcID=17880,NpcName="Temporus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=15.6,Zone="The Black Morass"}}
items[23463] = {id=23463,name="High Warlord's Tome of Mending",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[22253] = {id=22253,name="Tome of the Lost",obtain={NpcID=10363,NpcName="General Drakkisath",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=25.4,Zone="Blackrock Spire"}}
items[22329] = {id=22329,name="Scepter of Interminable Focus",obtain={NpcID=181083,NpcName="Sothos and Jarien's Heirlooms (Container)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=26.8,Zone="Stratholme"}}
items[13524] = {id=13524,name="Skull of Burning Shadows",obtain={NpcID=10438,NpcName="Maleki the Pallid",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=17.8,Zone="Stratholme"}}
items[13261] = {id=13261,name="Globe of D'sak",obtain={NpcID=9217,NpcName="Spirestone Lord Magus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=22.0,Zone="Blackrock Spire"}}
items[11935] = {id=11935,name="Magmus Stone",obtain={NpcID=9938,NpcName="Magmus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=21.0,Zone="Blackrock Depths"}}
items[36466] = {id=36466,name="Facetted Orb",obtain={NpcID=28848,NpcName="Prophet of Har'koa",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.7,Zone="Zul'Drak"}}
items[30911] = {id=30911,name="Scepter of Purification",obtain={NpcID=17968,NpcName="Archimonde",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=12.5,Zone="Hyjal Summit"}}
items[33681] = {id=33681,name="Vengeful Gladiator's Endgame",obtain={NpcID=20278,NpcName="Vixton Pinchwhistle (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Netherstorm"}}
items[34033] = {id=34033,name="Vengeful Gladiator's Grimoire",obtain={NpcID=20278,NpcName="Vixton Pinchwhistle (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Netherstorm"}}
items[37074] = {id=37074,name="Greatmother's Talisman of Cleansing",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=11689,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[28781] = {id=28781,name="Karaborian Talisman",obtain={NpcID=17257,NpcName="Magtheridon",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=14.3,Zone="Magtheridon's Lair"}}
items[28525] = {id=28525,name="Signet of Unshakable Faith",obtain={NpcID=15687,NpcName="Moroes",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=16.2,Zone="Karazhan"}}
items[28603] = {id=28603,name="Talisman of Nightbane",obtain={NpcID=17225,NpcName="Nightbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=15.9,Zone="Karazhan"}}
items[28734] = {id=28734,name="Jewel of Infinite Possibilities",obtain={NpcID=15689,NpcName="Netherspite",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=18.1,Zone="Karazhan"}}
items[28938] = {id=28938,name="High Warlord's Battletome",obtain={NpcID=14581,NpcName="Sergeant Thunderhorn (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[28260] = {id=28260,name="Manual of the Nethermancer",obtain={NpcID=19221,NpcName="Nethermancer Sepethrea",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=18.9,Zone="The Mechanar"}}
items[25096] = {id=25096,name="Elementalist Star",obtain={NpcID=23584,NpcName="Amani Bear",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.8,Zone="Zul'Aman"}}
items[29271] = {id=29271,name="Talisman of Kalecgos",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[32520] = {id=32520,name="Manaforged Sphere",obtain={NpcID=20520,NpcName="Ethereum Prisoner",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.5,Zone="Netherstorm"}}
items[25095] = {id=25095,name="Archmage Orb",obtain={NpcID=23180,NpcName="Tarren Mill Protector",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Unknown"}}
items[25093] = {id=25093,name="Shadow Council Orb",obtain={NpcID=17814,NpcName="Lordaeron Watchman",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Unknown"}}
items[186049] = {id=186049,name="Communal Rose",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[45271] = {id=45271,name="Ironmender",obtain={NpcID=32930,NpcName="Kologarn",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=16.8,Zone="Ulduar"}}
items[40350] = {id=40350,name="Urn of Lost Memories",obtain={NpcID=16063,NpcName="Sir Zeliek",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=14.1,Zone="Naxxramas"}}
items[45617] = {id=45617,name="Cosmos",obtain={NpcID=32871,NpcName="Algalon the Observer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=11.3,Zone="Ulduar"}}
items[45115] = {id=45115,name="Leviathan Fueling Manual",obtain={NpcID=33113,NpcName="Flame Leviathan",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=18.9,Zone="Ulduar"}}
items[45314] = {id=45314,name="Igniter Rod",obtain={NpcID=33118,NpcName="Ignis the Furnace Master",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=19.0,Zone="Ulduar"}}
items[40698] = {id=40698,name="Ward of the Violet Citadel",obtain={NpcID=29527,NpcName="Orton Bennet (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Dalaran"}}
items[40273] = {id=40273,name="Surplus Limb",obtain={NpcID=16028,NpcName="Patchwerk",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.9,Zone="Naxxramas"}}
items[39766] = {id=39766,name="Matriarch's Spawn",obtain={NpcID=15952,NpcName="Maexxna",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.7,Zone="Naxxramas"}}
items[44210] = {id=44210,name="Faces of Doom",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59498,DropChance=0,Zone=""}}
items[40699] = {id=40699,name="Handbook of Obscure Remedies",obtain={NpcID=29527,NpcName="Orton Bennet (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Dalaran"}}
items[39311] = {id=39311,name="Scepter of Murmuring Spirits",obtain={NpcID=27655,NpcName="Mage-Lord Urom",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.8,Zone="The Oculus"}}
items[40192] = {id=40192,name="Accursed Spine",obtain={NpcID=15954,NpcName="Noth the Plaguebringer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=6.2,Zone="Naxxramas"}}
items[42526] = {id=42526,name="Furious Gladiator's Endgame",obtain={NpcID=31863,NpcName="Nargle Lashcord (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Dalaran"}}
items[39199] = {id=39199,name="Watchful Eye",obtain={NpcID=27977,NpcName="Krystallus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=3.0,Zone="Halls of Stone"}}
items[50173] = {id=50173,name="Shadow Silk Spindle",obtain={NpcID=37970,NpcName="Prince Valanar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=31.7,Zone="Icecrown Citadel"}}
items[42537] = {id=42537,name="Deadly Gladiator's Grimoire",obtain={NpcID=31863,NpcName="Nargle Lashcord (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Dalaran"}}
items[37889] = {id=37889,name="Prison Manifest",obtain={NpcID=30660,NpcName="Portal Guardian",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.8,Zone="The Violet Hold"}}
items[38322] = {id=38322,name="Iron-bound Tome",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=59497,DropChance=0,Zone=""}}
items[47064] = {id=47064,name="Symbol of Transgression",obtain={NpcID=34780,NpcName="Lord Jaraxxus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=8.3,Zone="Trial of the Crusader"}}
items[48032] = {id=48032,name="Lightbane Focus",obtain={NpcID=34496,NpcName="Eydis Darkbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=6.0,Zone="Trial of the Crusader"}}
items[50309] = {id=50309,name="Shriveled Heart",obtain={NpcID=37226,NpcName="The Lich King",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=14.1,Zone="Halls of Reflection"}}
items[50719] = {id=50719,name="Shadow Silk Spindle",obtain={NpcID=37970,NpcName="Prince Valanar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=29.2,Zone="Icecrown Citadel"}}
items[47053] = {id=47053,name="Symbol of Transgression",obtain={NpcID=34780,NpcName="Lord Jaraxxus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.6,Zone="Trial of the Crusader"}}
items[47437] = {id=47437,name="Talisman of Heedless Sins",obtain={NpcID=34780,NpcName="Lord Jaraxxus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.0,Zone="Trial of the Crusader"}}
items[47958] = {id=47958,name="Chalice of Benedictus",obtain={NpcID=34496,NpcName="Eydis Darkbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=6.5,Zone="Trial of the Crusader"}}
items[47470] = {id=47470,name="Mystifying Charm",obtain={NpcID=34496,NpcName="Eydis Darkbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=8.0,Zone="Trial of the Crusader"}}
items[49490] = {id=49490,name="Antediluvian Cornerstone Grimoire",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[50781] = {id=50781,name="Scourgelord's Baton",obtain={NpcID=36855,NpcName="Lady Deathwhisper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=23.7,Zone="Icecrown Citadel"}}
items[49308] = {id=49308,name="Antique Cornerstone Grimoire",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[47742] = {id=47742,name="Chalice of Benedictus",obtain={NpcID=34496,NpcName="Eydis Darkbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.1,Zone="Trial of the Crusader"}}
items[50635] = {id=50635,name="Sundial of Eternal Dusk",obtain={NpcID=36853,NpcName="Sindragosa",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=16.0,Zone="Icecrown Citadel"}}
items[42530] = {id=42530,name="Hateful Gladiator's Reprieve",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[42525] = {id=42525,name="Deadly Gladiator's Endgame",obtain={NpcID=31863,NpcName="Nargle Lashcord (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Dalaran"}}
items[42536] = {id=42536,name="Hateful Gladiator's Grimoire",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[37364] = {id=37364,name="Frostbridge Orb",obtain={NpcID=27635,NpcName="Azure Spellbinder",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.5,Zone="The Oculus"}}
items[47309] = {id=47309,name="Mystifying Charm",obtain={NpcID=34496,NpcName="Eydis Darkbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=8.1,Zone="Trial of the Crusader"}}
items[42796] = {id=42796,name="Lantern of Enchanted Flame",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=12984,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[50423] = {id=50423,name="Sundial of Eternal Dusk",obtain={NpcID=36853,NpcName="Sindragosa",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=16.5,Zone="Icecrown Citadel"}}
items[38458] = {id=38458,name="Darkspear Orb",obtain={NpcID=32565,NpcName="Gara Skullcrush (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Borean Tundra"}}
items[49187] = {id=49187,name="Relentless Gladiator's Compendium",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[42524] = {id=42524,name="Hateful Gladiator's Endgame",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[47146] = {id=47146,name="Chalice of Searing Light",obtain={NpcID=34496,NpcName="Eydis Darkbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.1,Zone="Trial of the Crusader"}}
items[47138] = {id=47138,name="Chalice of Searing Light",obtain={NpcID=34496,NpcName="Eydis Darkbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=6.5,Zone="Trial of the Crusader"}}
items[47276] = {id=47276,name="Talisman of Heedless Sins",obtain={NpcID=34780,NpcName="Lord Jaraxxus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.5,Zone="Trial of the Crusader"}}
items[42532] = {id=42532,name="Furious Gladiator's Reprieve",obtain={NpcID=31863,NpcName="Nargle Lashcord (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Dalaran"}}
items[37051] = {id=37051,name="Seal of Valgarde",obtain={NpcID=26687,NpcName="Gortok Palehoof",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=27.1,Zone="Utgarde Pinnacle"}}
items[42538] = {id=42538,name="Furious Gladiator's Grimoire",obtain={NpcID=31863,NpcName="Nargle Lashcord (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Dalaran"}}
items[38459] = {id=38459,name="Orb of the Eastern Kingdoms",obtain={NpcID=32564,NpcName="Logistics Officer Silverstone (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Borean Tundra"}}
items[37134] = {id=37134,name="Telestra's Journal",obtain={NpcID=26731,NpcName="Grand Magus Telestra",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=25.1,Zone="The Nexus"}}
items[51922] = {id=51922,name="Scourgelord's Baton",obtain={NpcID=36855,NpcName="Lady Deathwhisper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=26.6,Zone="Icecrown Citadel"}}
items[42533] = {id=42533,name="Relentless Gladiator's Reprieve",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[47913] = {id=47913,name="Lightbane Focus",obtain={NpcID=34496,NpcName="Eydis Darkbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.5,Zone="Trial of the Crusader"}}
items[42531] = {id=42531,name="Deadly Gladiator's Reprieve",obtain={NpcID=31863,NpcName="Nargle Lashcord (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Dalaran"}}
items[42535] = {id=42535,name="Savage Gladiator's Grimoire",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[44022] = {id=44022,name="The Witching Grimoire",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=13142,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[44023] = {id=44023,name="Bonecaster's Endgame",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=13142,Recipe=false,RecipeID=0,DropChance=0,Zone="The Scrimshank Redemption"}}
items[36469] = {id=36469,name="Lidless Orb",obtain={NpcID=31224,NpcName="Icefury",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.2,Zone="Icecrown"}}
items[51408] = {id=51408,name="Wrathful Gladiator's Grimoire",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[51396] = {id=51396,name="Wrathful Gladiator's Endgame",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[42523] = {id=42523,name="Savage Gladiator's Endgame",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[42529] = {id=42529,name="Savage Gladiator's Reprieve",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[51407] = {id=51407,name="Wrathful Gladiator's Compendium",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[51409] = {id=51409,name="Wrathful Gladiator's Reprieve",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[42527] = {id=42527,name="Relentless Gladiator's Endgame",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[37718] = {id=37718,name="Temple Crystal Fragment",obtain={NpcID=26631,NpcName="Novos the Summoner",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=23.8,Zone="Drak'Tharon Keep"}}
items[37086] = {id=37086,name="Tome of Salramm",obtain={NpcID=26530,NpcName="Salramm the Fleshcrafter",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=22.1,Zone="The Culling of Stratholme"}}
items[36471] = {id=36471,name="Ice Crystal",obtain={NpcID=37149,NpcName="Kor'kron Necrolyte",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.5,Zone="Unknown"}}
items[36470] = {id=36470,name="Gilded Scepter",obtain={NpcID=31225,NpcName="Plaguehoof",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=4.1,Zone="Icecrown"}}
items[36468] = {id=36468,name="Glistening Star",obtain={NpcID=29885,NpcName="Mildred the Cruel",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=16.6,Zone="The Storm Peaks"}}
items[42539] = {id=42539,name="Relentless Gladiator's Grimoire",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[36472] = {id=36472,name="Carved Rod",obtain={NpcID=32492,NpcName="Frostbrood Matriarch",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=20.0,Zone="Icecrown"}}

names["Darkmoon Flower"] = 19295
names["Stitches' Femur"] = 3360
names["Torch of Holy Flame"] = 7344
names["Totem of Infliction"] = 1131
names["Mystic Tome"] = 43515
names["Egg Basket"] = 45067
names["Buccaneer's Orb"] = 15912
names["Everglow Lantern"] = 5323
names["Eerie Stable Lantern"] = 6341
names["Ritual Stein"] = 15972
names["Book of Survival"] = 43655
names["Sunwell Orb"] = 22784
names["Journeyman's Stave"] = 15925
names["Eye of Paleth"] = 2943
names["Watcher's Star"] = 15973
names["Simple Branch"] = 15933
names["Witch's Finger"] = 16887
names["Grayson's Torch"] = 1172
names["Sanguine Star"] = 15947
names["Venomous Tome"] = 38579
names["Veildust Medicine Bag"] = 15866
names["Pagan Rod"] = 15974
names["Tome of the Dawn"] = 43654
names["Bouquet of Scarlet Begonias"] = 2562
names["Tork Wrench"] = 11855
names["Spellbinder Orb"] = 15926
names["Ley Orb"] = 7508
names["Dim Torch"] = 6182
names["Antipodean Rod"] = 2879
names["Tear of Grief"] = 5611
names["Beaded Orb"] = 15969
names["Bright Sphere"] = 15927
names["Greenweave Branch"] = 9769
names["Orb of Soran'ruk"] = 6898
names["Mystic's Sphere"] = 15946
names["Pulsating Hydra Heart"] = 5183
names["Aboriginal Rod"] = 15971
names["Runic Stave"] = 15945
names["Carved Crystalline Orb"] = 27398
names["Divining Crystal"] = 23401
names["Native Branch"] = 15970
names["Disciple's Stein"] = 15932
names["Ancestral Orb"] = 15944
names["Strength of Will"] = 4837
names["Ivy Orb"] = 9800
names["Orb of Mistmantle"] = 13031
names["Fireproof Orb"] = 4836
names["Orb of Power"] = 4838
names["Shimmering Stave"] = 7558
names["Seer's Fine Stein"] = 7608
names["Jadefinger Baton"] = 15206
names["Willow Branch"] = 7554
names["Nightglow Concoction"] = 3451
names["Runic Cane"] = 7559
names["Arcane Orb"] = 7507
names["Torch of the Eternal Flame"] = 6654
names["Skull of Impending Doom"] = 4984
names["Stormbound Tome"] = 43663
names["Drakestone"] = 10796
names["Tome of Kings"] = 43656
names["Manual of Clouds"] = 43664
names["Fire Eater's Guide"] = 43660
names["Celestial Orb"] = 7515
names["Spirit of Aquementas"] = 11904
names["Basilisk Bone"] = 13030
names["Gossamer Rod"] = 7557
names["Beacon of Hope"] = 9393
names["Royal Guide of Escape Routes"] = 43657
names["Book of Stars"] = 43661
names["Umbral Crystal"] = 13029
names["Omega Orb"] = 7749
names["Swampchill Fetish"] = 1992
names["Venomshroud Orb"] = 15966
names["Cloud Stone"] = 17737
names["Enthralled Sphere"] = 11625
names["Gaea's Scepter"] = 15983
names["Flask of Forest Mojo"] = 19115
names["Thermotastic Egg Timer"] = 9644
names["Lord Sakrasis' Scepter"] = 5028
names["Explorers' League Lodestar"] = 9627
names["Orb of Noh'Orahil"] = 15107
names["Orb of the Forgotten Seer"] = 7685
names["Book of the Adept"] = 33266
names["Thistlefur Branch"] = 15976
names["Rod of Molten Fire"] = 2565
names["Magebane Scion"] = 15857
names["Shard of the Green Flame"] = 18762
names["Embersilk Stave"] = 15979
names["Uthek's Finger"] = 6774
names["Conjurer's Sphere"] = 15918
names["Satyr's Rod"] = 15962
names["Sage's Stave"] = 15934
names["Cursed Eye of Paleth"] = 2944
names["Duskwoven Branch"] = 15936
names["Abjurer's Crystal"] = 9944
names["Skullspell Orb"] = 10708
names["Hibernal Sphere"] = 15937
names["Bloodwoven Rod"] = 15982
names["Windchaser Orb"] = 15965
names["Desertwalker Cane"] = 12471
names["Lunar Sphere"] = 15981
names["Darkmist Orb"] = 15980
names["Mistscape Stave"] = 7611
names["Regal Star"] = 7555
names["Silksand Star"] = 15964
names["Prophetic Cane"] = 6803
names["Geomancer's Rod"] = 15978
names["Aurora Sphere"] = 7610
names["Orb of Dar'Orahil"] = 15108
names["Vital Orb"] = 15977
names["Nightsky Orb"] = 15929
names["Durable Rod"] = 15935
names["Silver-thread Rod"] = 15928
names["Raincaller Scepter"] = 15975
names["Pyrestone Orb"] = 10709
names["Oblivion Orb"] = 11870
names["Royal Scepter"] = 9914
names["Jademoon Orb"] = 11859
names["Orb of Lorica"] = 11262
names["Sorcerer Sphere"] = 9882
names["Tranquil Orb"] = 4125
names["Mordresh's Lifeless Skull"] = 10770
names["Twilight Orb"] = 7556
names["Stonecloth Branch"] = 15963
names["Elder's Amber Stave"] = 7609
names["Rituals of the New Moon"] = 45854
names["Talisman of Scourge Command"] = 35609
names["Medicine Stick"] = 37024
names["Tome of Sacrifice"] = 18602
names["Twilight Tome"] = 45849
names["Coldarra Crystal"] = 36462
names["Tome of Alacrity"] = 35858
names["Rituals of the New Moon"] = 45850
names["Mining: The Pick and You"] = 45010
names["Book of the Dead"] = 13353
names["Demon-Skull Orb"] = 36461
names["Lapidis Tankard of Tidesippe"] = 4696
names["Branch of Sinful Reprieve"] = 37817
names["Deep Core Lantern"] = 30857
names["Bonecaster's Star"] = 15986
names["Rituals of the New Moon"] = 45853
names["Evergreen Branch"] = 36465
names["Book of Highborne Hymns"] = 34206
names["Sapphiron's Wing Bone"] = 29269
names["Royal Scepter of Vek'lor"] = 21597
names["Sartura's Might"] = 21666
names["Eternal Rod"] = 15989
names["Hellfire Tome"] = 43666
names["Therazane's Touch"] = 19315
names["Imperial Red Scepter"] = 15930
names["Rituals of the New Moon"] = 45852
names["Tome of the Lore Keepers"] = 35598
names["Branch of Insightful Dreams"] = 39124
names["Manual of the Tides"] = 37033
names["Demoniac Soul Prison"] = 31715
names["Rituals of the New Moon"] = 45851
names["Darkened Scepter"] = 36464
names["Suntouched Flowers"] = 38293
names["Tome of the Violet Tower"] = 38217
names["Icy Orb"] = 36459
names["Hortus' Seal of Brilliance"] = 27534
names["Flametongue Seal"] = 29270
names["Book of Many Blessings"] = 31823
names["Slavehandler Rod"] = 25090
names["Laughing Skull Orb"] = 25088
names["Dreamseeker Dandelion"] = 25086
names["Ancient Cornerstone Grimoire"] = 17067
names["Lei of the Lifegiver"] = 19312
names["Book of Clever Tricks"] = 43667
names["Mystical Orb"] = 15938
names["Life Binder Talisman"] = 38224
names["Hypergizmatic Energy Booster"] = 38214
names["Lamp of Peaceful Repose"] = 28387
names["Tears of Heaven"] = 29274
names["Netherwing Spiritualist's Charm"] = 31493
names["Windcaller's Orb"] = 29170
names["Mistyreed Torch"] = 25091
names["Sapphiron's Right Eye"] = 23048
names["High Warlord's Tome of Mending"] = 23469
names["Spellbound Tome"] = 18695
names["Arcane Star"] = 15931
names["Kreeg's Mug"] = 18425
names["Elemental Ember"] = 18672
names["Arachnidian Branch"] = 15985
names["Brutal Gladiator's Grimoire"] = 35016
names["Heart of the Pit"] = 34179
names["Chronicle of Dark Secrets"] = 30872
names["Gladiator's Endgame"] = 28346
names["Lordaeron Medical Guide"] = 28213
names["Orb of the Soul-Eater"] = 29272
names["Khadgar's Knapsack"] = 29273
names["Netherwing Sorceror's Charm"] = 31494
names["Crystal Orb of Enlightenment"] = 32651
names["Eldr'naan Scepter"] = 25094
names["Unearthed Orb"] = 31732
names["Sapphiron's Left Eye"] = 23049
names["Resplendent Orb"] = 15988
names["Penelope's Rose"] = 15805
names["Reflecting Sphere"] = 36467
names["Brutal Gladiator's Reprieve"] = 35074
names["Brutal Gladiator's Endgame"] = 35008
names["Polished Orb"] = 36463
names["Touch of Inspiration"] = 32350
names["Blind-Seers Icon"] = 32361
names["Merciless Gladiator's Reprieve"] = 32961
names["Voodoo Shaker"] = 33325
names["Fetish of the Primal Gods"] = 33334
names["Talisman of the Sun King"] = 29923
names["Fathomstone"] = 30049
names["Collective Rose"] = 199710
names["Tuurik Torch"] = 25098
names["Faol's Signet of Cleansing"] = 27477
names["The Saga of Terokk"] = 29330
names["Swamplight Lantern"] = 27714
names["Grand Marshal's Battletome"] = 28941
names["Astralaan Orb"] = 25097
names["Imbued Draenethyst Crystal"] = 31699
names["Mekeda's Gift"] = 31731
names["Consortium Crystal"] = 25092
names["Supplicant's Rod"] = 25089
names["Bleeding Eye"] = 25087
names["Master Dragonslayer's Orb"] = 19366
names["Gem of Nerubis"] = 22937
names["Digested Hand of Power"] = 22994
names["Noth's Frigid Heart"] = 23029
names["Grand Marshal's Tome of Power"] = 23452
names["Grand Marshal's Tome of Restoration"] = 23453
names["High Warlord's Tome of Destruction"] = 23462
names["High Warlord's Tome of Destruction"] = 23468
names["Trance Stone"] = 20582
names["Fire Runed Grimoire"] = 19142
names["Talon of Furious Concentration"] = 21471
names["Arlokk's Hoodoo Stick"] = 19922
names["Jin'do's Bag of Whammies"] = 19891
names["Tome of Arcane Domination"] = 19308
names["Tome of Shadow Force"] = 19309
names["Tome of the Ice Lord"] = 19310
names["Tome of Fiery Arcana"] = 19311
names["Master's Rod"] = 15942
names["High Councillor's Scepter"] = 15941
names["Elunarian Sphere"] = 15968
names["Brightly Glowing Stone"] = 18523
names["Earthcalm Orb"] = 21185
names["Blackwood's Thigh"] = 23156
names["Elegant Scepter"] = 15940
names["Astral Orb"] = 15987
names["Tome of Divine Right"] = 22319
names["Tome of Knowledge"] = 13385
names["Thaurissan's Royal Scepter"] = 11928
names["Glowing Black Orb"] = 20694
names["Councillor's Scepter"] = 15939
names["Highborne Star"] = 15967
names["Milli's Lexicon"] = 18536
names["Opulent Scepter"] = 15984
names["Vile Tome of Tenets"] = 39827
names["Scepter of Passionate Reprisal"] = 38755
names["Glowing Voodoo Orb"] = 39118
names["Vengeful Gladiator's Reprieve"] = 33736
names["Merciless Gladiator's Endgame"] = 31978
names["Northern Star"] = 36460
names["Gladiator's Reprieve"] = 32452
names["Draenei Crystal Rod"] = 25099
names["Karrog's Shard"] = 32533
names["Aran's Soothing Sapphire"] = 28728
names["Lamp of Peaceful Radiance"] = 28412
names["Star-Heart Lamp"] = 28187
names["High Warlord's Tome of Mending"] = 23463
names["Tome of the Lost"] = 22253
names["Scepter of Interminable Focus"] = 22329
names["Skull of Burning Shadows"] = 13524
names["Globe of D'sak"] = 13261
names["Magmus Stone"] = 11935
names["Facetted Orb"] = 36466
names["Scepter of Purification"] = 30911
names["Vengeful Gladiator's Endgame"] = 33681
names["Vengeful Gladiator's Grimoire"] = 34033
names["Greatmother's Talisman of Cleansing"] = 37074
names["Karaborian Talisman"] = 28781
names["Signet of Unshakable Faith"] = 28525
names["Talisman of Nightbane"] = 28603
names["Jewel of Infinite Possibilities"] = 28734
names["High Warlord's Battletome"] = 28938
names["Manual of the Nethermancer"] = 28260
names["Elementalist Star"] = 25096
names["Talisman of Kalecgos"] = 29271
names["Manaforged Sphere"] = 32520
names["Archmage Orb"] = 25095
names["Shadow Council Orb"] = 25093
names["Communal Rose"] = 186049
names["Ironmender"] = 45271
names["Urn of Lost Memories"] = 40350
names["Cosmos"] = 45617
names["Leviathan Fueling Manual"] = 45115
names["Igniter Rod"] = 45314
names["Ward of the Violet Citadel"] = 40698
names["Surplus Limb"] = 40273
names["Matriarch's Spawn"] = 39766
names["Faces of Doom"] = 44210
names["Handbook of Obscure Remedies"] = 40699
names["Scepter of Murmuring Spirits"] = 39311
names["Accursed Spine"] = 40192
names["Furious Gladiator's Endgame"] = 42526
names["Watchful Eye"] = 39199
names["Shadow Silk Spindle"] = 50173
names["Deadly Gladiator's Grimoire"] = 42537
names["Prison Manifest"] = 37889
names["Iron-bound Tome"] = 38322
names["Symbol of Transgression"] = 47064
names["Lightbane Focus"] = 48032
names["Shriveled Heart"] = 50309
names["Shadow Silk Spindle"] = 50719
names["Symbol of Transgression"] = 47053
names["Talisman of Heedless Sins"] = 47437
names["Chalice of Benedictus"] = 47958
names["Mystifying Charm"] = 47470
names["Antediluvian Cornerstone Grimoire"] = 49490
names["Scourgelord's Baton"] = 50781
names["Antique Cornerstone Grimoire"] = 49308
names["Chalice of Benedictus"] = 47742
names["Sundial of Eternal Dusk"] = 50635
names["Hateful Gladiator's Reprieve"] = 42530
names["Deadly Gladiator's Endgame"] = 42525
names["Hateful Gladiator's Grimoire"] = 42536
names["Frostbridge Orb"] = 37364
names["Mystifying Charm"] = 47309
names["Lantern of Enchanted Flame"] = 42796
names["Sundial of Eternal Dusk"] = 50423
names["Darkspear Orb"] = 38458
names["Relentless Gladiator's Compendium"] = 49187
names["Hateful Gladiator's Endgame"] = 42524
names["Chalice of Searing Light"] = 47146
names["Chalice of Searing Light"] = 47138
names["Talisman of Heedless Sins"] = 47276
names["Furious Gladiator's Reprieve"] = 42532
names["Seal of Valgarde"] = 37051
names["Furious Gladiator's Grimoire"] = 42538
names["Orb of the Eastern Kingdoms"] = 38459
names["Telestra's Journal"] = 37134
names["Scourgelord's Baton"] = 51922
names["Relentless Gladiator's Reprieve"] = 42533
names["Lightbane Focus"] = 47913
names["Deadly Gladiator's Reprieve"] = 42531
names["Savage Gladiator's Grimoire"] = 42535
names["The Witching Grimoire"] = 44022
names["Bonecaster's Endgame"] = 44023
names["Lidless Orb"] = 36469
names["Wrathful Gladiator's Grimoire"] = 51408
names["Wrathful Gladiator's Endgame"] = 51396
names["Savage Gladiator's Endgame"] = 42523
names["Savage Gladiator's Reprieve"] = 42529
names["Wrathful Gladiator's Compendium"] = 51407
names["Wrathful Gladiator's Reprieve"] = 51409
names["Relentless Gladiator's Endgame"] = 42527
names["Temple Crystal Fragment"] = 37718
names["Tome of Salramm"] = 37086
names["Ice Crystal"] = 36471
names["Gilded Scepter"] = 36470
names["Glistening Star"] = 36468
names["Relentless Gladiator's Grimoire"] = 42539
names["Carved Rod"] = 36472

LE:RegisterDBItems(items)
LE:RegisterNameDBItems(names)