-------------------------------------**     LibEquippable     **-------------------------------------
-- This file is autogenerated, please do not edit it manually or fuckups might occur.
-------------------------------------**  All Rights Reserved  **-------------------------------------

local LE = LibStub and LibStub("LibEquippable-1.0", true)
if not LE  then return end

local items = {}
local names = {}

items[19295] = {id=19295,name="Darkmoon Flower",source={ID=7930,SourceName="5 Tickets - Darkmoon Flower",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[3360] = {id=3360,name="Stitches' Femur",source={ID=412,SourceName="Stitches",SourceType="Kill",DropChance="95.1",Zone="Duskwood"}}
items[7344] = {id=7344,name="Torch of Holy Flame",source={ID=55,SourceName="Morbent Fel",SourceType="Quest",DropChance="0",Zone="Duskwood"}}
items[1131] = {id=1131,name="Totem of Infliction",source={ID=101,SourceName="The Totem of Infliction",SourceType="Quest",DropChance="0",Zone="Duskwood"}}
items[43515] = {id=43515,name="Mystic Tome",source={ID=58565,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[45067] = {id=45067,name="Egg Basket",source={ID=13502,SourceName="A Tisket, a Tasket, a Noblegarden Basket",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[15912] = {id=15912,name="Buccaneer's Orb",source={ID=335,SourceName="Singe",SourceType="Kill",DropChance="0.1",Zone="Redridge Mountains"}}
items[5323] = {id=5323,name="Everglow Lantern",source={ID=893,SourceName="Weapons of Choice",SourceType="Quest",DropChance="0",Zone="The Barrens"}}
items[6341] = {id=6341,name="Eerie Stable Lantern",source={ID=4278,SourceName="Commander Springvale",SourceType="Kill",DropChance="9.4",Zone="Shadowfang Keep"}}
items[15972] = {id=15972,name="Ritual Stein",source={ID=3783,SourceName="Shadethicket Raincaller",SourceType="Kill",DropChance="0.1",Zone="Ashenvale"}}
items[43655] = {id=43655,name="Book of Survival",source={ID=59478,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[22784] = {id=22784,name="Sunwell Orb",source={ID=9176,SourceName="The Twin Ziggurats",SourceType="Quest",DropChance="0",Zone="Ghostlands"}}
items[15925] = {id=15925,name="Journeyman's Stave",source={ID=16855,SourceName="Tregla",SourceType="Kill",DropChance="1.1",Zone="Eversong Woods"}}
items[2943] = {id=2943,name="Eye of Paleth",source={ID=293,SourceName="Cleansing the Eye",SourceType="Quest",DropChance="0",Zone="Wetlands"}}
items[15973] = {id=15973,name="Watcher's Star",source={ID=5915,SourceName="Brother Ravenoak",SourceType="Kill",DropChance="1.3",Zone="Stonetalon Mountains"}}
items[15933] = {id=15933,name="Simple Branch",source={ID=2065,SourceName="Councilman Cooper",SourceType="Kill",DropChance="1.2",Zone="Silverpine Forest"}}
items[16887] = {id=16887,name="Witch's Finger",source={ID=909,SourceName="Baron Aquanis",SourceType="Quest",DropChance="0",Zone="Ashenvale"}}
items[1172] = {id=1172,name="Grayson's Torch",source={ID=104,SourceName="The Coastal Menace",SourceType="Quest",DropChance="0",Zone="Westfall"}}
items[15947] = {id=15947,name="Sanguine Star",source={ID=11682,SourceName="Warsong Grunt",SourceType="Kill",DropChance="0.2",Zone="Ashenvale"}}
items[38579] = {id=38579,name="Venomous Tome",source={ID=28347,SourceName="Miles Sidney",SourceType="Purchase",DropChance="100",Zone="Stormwind City"}}
items[15866] = {id=15866,name="Veildust Medicine Bag",source={ID=6124,SourceName="Curing the Sick",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[15974] = {id=15974,name="Pagan Rod",source={ID=5859,SourceName="Hagg Taurenbane",SourceType="Kill",DropChance="0.4",Zone="The Barrens"}}
items[43654] = {id=43654,name="Tome of the Dawn",source={ID=59475,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[2562] = {id=2562,name="Bouquet of Scarlet Begonias",source={ID=34,SourceName="An Unwelcome Guest",SourceType="Quest",DropChance="0",Zone="Redridge Mountains"}}
items[11855] = {id=11855,name="Tork Wrench",source={ID=3924,SourceName="Samophlange Manual",SourceType="Quest",DropChance="0",Zone="The Barrens"}}
items[15926] = {id=15926,name="Spellbinder Orb",source={ID=3529,SourceName="Moonrage Armorer",SourceType="Kill",DropChance="1.1",Zone="Silverpine Forest"}}
items[7508] = {id=7508,name="Ley Orb",source={ID=1861,SourceName="Mirror Lake",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[6182] = {id=6182,name="Dim Torch",source={ID=7364,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[2879] = {id=2879,name="Antipodean Rod",source={ID=3424,SourceName="Thunderhawk Cloudscraper",SourceType="Kill",DropChance="0.2",Zone="The Barrens"}}
items[5611] = {id=5611,name="Tear of Grief",source={ID=963,SourceName="For Love Eternal",SourceType="Quest",DropChance="0",Zone="Darkshore"}}
items[15969] = {id=15969,name="Beaded Orb",source={ID=2968,SourceName="Galak Outrunner",SourceType="Kill",DropChance="0.6",Zone="Mulgore"}}
items[15927] = {id=15927,name="Bright Sphere",source={ID=4464,SourceName="Blackrock Gladiator",SourceType="Kill",DropChance="0.3",Zone="Redridge Mountains"}}
items[9769] = {id=9769,name="Greenweave Branch",source={ID=11656,SourceName="Warsong Peon",SourceType="Kill",DropChance="0.4",Zone="Ashenvale"}}
items[6898] = {id=6898,name="Orb of Soran'ruk",source={ID=1740,SourceName="The Orb of Soran'ruk",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[15946] = {id=15946,name="Mystic's Sphere",source={ID=3900,SourceName="Caedakar the Vicious",SourceType="Kill",DropChance="0.2",Zone="Darkshore"}}
items[5183] = {id=5183,name="Pulsating Hydra Heart",source={ID=3398,SourceName="Gesharahan",SourceType="Kill",DropChance="22.6",Zone="The Barrens"}}
items[15971] = {id=15971,name="Aboriginal Rod",source={ID=3295,SourceName="Sludge Beast",SourceType="Kill",DropChance="1.1",Zone="The Barrens"}}
items[15945] = {id=15945,name="Runic Stave",source={ID=11519,SourceName="Bazzalan",SourceType="Kill",DropChance="0.3",Zone="Ragefire Chasm"}}
items[27398] = {id=27398,name="Carved Crystalline Orb",source={ID=9646,SourceName="WANTED: Deathclaw",SourceType="Quest",DropChance="0",Zone="Bloodmyst Isle"}}
items[23401] = {id=23401,name="Divining Crystal",source={ID=9169,SourceName="Deactivate An'owyn",SourceType="Quest",DropChance="0",Zone="Ghostlands"}}
items[15970] = {id=15970,name="Native Branch",source={ID=12319,SourceName="Burning Blade Toxicologist",SourceType="Kill",DropChance="1.7",Zone="The Barrens"}}
items[15932] = {id=15932,name="Disciple's Stein",source={ID=16854,SourceName="Eldinarcus",SourceType="Kill",DropChance="2.1",Zone="Eversong Woods"}}
items[15944] = {id=15944,name="Ancestral Orb",source={ID=6128,SourceName="Vorlus Vilehoof",SourceType="Kill",DropChance="0.6",Zone="Teldrassil"}}
items[4837] = {id=4837,name="Strength of Will",source={ID=3134,SourceName="Kzixx",SourceType="Purchase",DropChance="100",Zone="Duskwood"}}
items[9800] = {id=9800,name="Ivy Orb",source={ID=6230,SourceName="Peacekeeper Security Suit",SourceType="Kill",DropChance="0.2",Zone="Gnomeregan"}}
items[13031] = {id=13031,name="Orb of Mistmantle",source={ID=15814,SourceName="Qiraji Lieutenant Jo-rel",SourceType="Kill",DropChance="7.5",Zone="The Barrens"}}
items[4836] = {id=4836,name="Fireproof Orb",source={ID=3134,SourceName="Kzixx",SourceType="Purchase",DropChance="100",Zone="Duskwood"}}
items[4838] = {id=4838,name="Orb of Power",source={ID=3134,SourceName="Kzixx",SourceType="Purchase",DropChance="100",Zone="Duskwood"}}
items[7558] = {id=7558,name="Shimmering Stave",source={ID=6392,SourceName="Holdout Medic",SourceType="Kill",DropChance="0.1",Zone="Gnomeregan"}}
items[7608] = {id=7608,name="Seer's Fine Stein",source={ID=2477,SourceName="Gradok",SourceType="Kill",DropChance="0.9",Zone="Loch Modan"}}
items[15206] = {id=15206,name="Jadefinger Baton",source={ID=5321,SourceName="The Sleeper Has Awakened",SourceType="Quest",DropChance="0",Zone="Darkshore"}}
items[7554] = {id=7554,name="Willow Branch",source={ID=16358,SourceName="Kel'gash the Wicked",SourceType="Kill",DropChance="0.3",Zone="Ghostlands"}}
items[3451] = {id=3451,name="Nightglow Concoction",source={ID=451,SourceName="A Recipe For Death",SourceType="Quest",DropChance="0",Zone="Silverpine Forest"}}
items[7559] = {id=7559,name="Runic Cane",source={ID=5838,SourceName="Brokespear",SourceType="Kill",DropChance="20.5",Zone="The Barrens"}}
items[7507] = {id=7507,name="Arcane Orb",source={ID=1880,SourceName="Mage-tastic Gizmonitor",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[6654] = {id=6654,name="Torch of the Eternal Flame",source={ID=1526,SourceName="Call of Fire",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[4984] = {id=4984,name="Skull of Impending Doom",source={ID=737,SourceName="Forbidden Knowledge",SourceType="Quest",DropChance="0",Zone="Badlands"}}
items[43663] = {id=43663,name="Stormbound Tome",source={ID=59493,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[10796] = {id=10796,name="Drakestone",source={ID=5722,SourceName="Hazzas",SourceType="Kill",DropChance="9.1",Zone="The Temple of Atal'Hakkar"}}
items[43656] = {id=43656,name="Tome of Kings",source={ID=59484,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[43664] = {id=43664,name="Manual of Clouds",source={ID=59494,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[43660] = {id=43660,name="Fire Eater's Guide",source={ID=59489,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[7515] = {id=7515,name="Celestial Orb",source={ID=1958,SourceName="Celestial Power",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[11904] = {id=11904,name="Spirit of Aquementas",source={ID=3962,SourceName="It's Dangerous to Go Alone",SourceType="Quest",DropChance="0",Zone="Un'Goro Crater"}}
items[13030] = {id=13030,name="Basilisk Bone",source={ID=15741,SourceName="Colossus of Regal",SourceType="Kill",DropChance="25.0",Zone="Silithus"}}
items[7557] = {id=7557,name="Gossamer Rod",source={ID=8497,SourceName="Nightmare Suppressor",SourceType="Kill",DropChance="0.3",Zone="The Temple of Atal'Hakkar"}}
items[9393] = {id=9393,name="Beacon of Hope",source={ID=4872,SourceName="Obsidian Golem",SourceType="Kill",DropChance="0.1",Zone="Badlands"}}
items[43657] = {id=43657,name="Royal Guide of Escape Routes",source={ID=59486,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[43661] = {id=43661,name="Book of Stars",source={ID=59490,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[13029] = {id=13029,name="Umbral Crystal",source={ID=2925,SourceName="Silvermane Howler",SourceType="Kill",DropChance="0",Zone="The Hinterlands"}}
items[7749] = {id=7749,name="Omega Orb",source={ID=1049,SourceName="Compendium of the Fallen",SourceType="Quest",DropChance="0",Zone="Scarlet Monastery"}}
items[1992] = {id=1992,name="Swampchill Fetish",source={ID=3976,SourceName="Scarlet Commander Mograine",SourceType="Kill",DropChance="0",Zone="Scarlet Monastery"}}
items[15966] = {id=15966,name="Venomshroud Orb",source={ID=8198,SourceName="Tick",SourceType="Kill",DropChance="0.2",Zone="Tanaris"}}
items[17737] = {id=17737,name="Cloud Stone",source={ID=12203,SourceName="Landslide",SourceType="Kill",DropChance="23.9",Zone="Maraudon"}}
items[11625] = {id=11625,name="Enthralled Sphere",source={ID=9018,SourceName="High Interrogator Gerstahn",SourceType="Kill",DropChance="19.7",Zone="Blackrock Depths"}}
items[15983] = {id=15983,name="Gaea's Scepter",source={ID=193,SourceName="Blue Dragonspawn",SourceType="Kill",DropChance="0.1",Zone="Azshara"}}
items[19115] = {id=19115,name="Flask of Forest Mojo",source={ID=7847,SourceName="Return to Primal Torntusk",SourceType="Quest",DropChance="0",Zone="The Hinterlands"}}
items[9644] = {id=9644,name="Thermotastic Egg Timer",source={ID=648,SourceName="Rescue OOX-17/TN!",SourceType="Quest",DropChance="0",Zone="Tanaris"}}
items[5028] = {id=5028,name="Lord Sakrasis' Scepter",source={ID=2541,SourceName="Lord Sakrasis",SourceType="Kill",DropChance="50.2",Zone="Stranglethorn Vale"}}
items[9627] = {id=9627,name="Explorers' League Lodestar",source={ID=2240,SourceName="The Hidden Chamber",SourceType="Quest",DropChance="0",Zone="Uldaman"}}
items[15107] = {id=15107,name="Orb of Noh'Orahil",source={ID=4975,SourceName="The Completed Orb of Noh'Orahil",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[7685] = {id=7685,name="Orb of the Forgotten Seer",source={ID=4543,SourceName="Bloodmage Thalnos",SourceType="Kill",DropChance="49.6",Zone="Scarlet Monastery"}}
items[33266] = {id=33266,name="Book of the Adept",source={ID=11147,SourceName="Unleash the Raptors",SourceType="Quest",DropChance="0",Zone="Dustwallow Marsh"}}
items[15976] = {id=15976,name="Thistlefur Branch",source={ID=12976,SourceName="Kolkar Waylayer",SourceType="Kill",DropChance="0.1",Zone="Desolace"}}
items[2565] = {id=2565,name="Rod of Molten Fire",source={ID=23637,SourceName="Deserter Lieutenant",SourceType="Kill",DropChance="0.2",Zone="Dustwallow Marsh"}}
items[15857] = {id=15857,name="Magebane Scion",source={ID=5942,SourceName="Hidden Treasures",SourceType="Quest",DropChance="0",Zone="Eastern Plaguelands"}}
items[18762] = {id=18762,name="Shard of the Green Flame",source={ID=7603,SourceName="Kroshius' Infernal Core",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[15979] = {id=15979,name="Embersilk Stave",source={ID=4328,SourceName="Firemane Scalebane",SourceType="Kill",DropChance="0",Zone="Dustwallow Marsh"}}
items[6774] = {id=6774,name="Uthek's Finger",source={ID=1380,SourceName="Khan Hratha",SourceType="Quest",DropChance="0",Zone="Desolace"}}
items[15918] = {id=15918,name="Conjurer's Sphere",source={ID=15070,SourceName="Vinchaxa",SourceType="Kill",DropChance="1.2",Zone="Stranglethorn Vale"}}
items[15962] = {id=15962,name="Satyr's Rod",source={ID=7404,SourceName="Galak Flame Guard",SourceType="Kill",DropChance="1.1",Zone="Thousand Needles"}}
items[15934] = {id=15934,name="Sage's Stave",source={ID=1200,SourceName="Morbent Fel",SourceType="Kill",DropChance="0.2",Zone="Duskwood"}}
items[2944] = {id=2944,name="Cursed Eye of Paleth",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[15936] = {id=15936,name="Duskwoven Branch",source={ID=9680,SourceName="Crest Killer",SourceType="Kill",DropChance="0.2",Zone="Blackrock Depths"}}
items[9944] = {id=9944,name="Abjurer's Crystal",source={ID=9028,SourceName="Grizzle",SourceType="Kill",DropChance="0.1",Zone="Blackrock Depths"}}
items[10708] = {id=10708,name="Skullspell Orb",source={ID=3461,SourceName="Return to Tymor",SourceType="Quest",DropChance="0",Zone="Ironforge"}}
items[15937] = {id=15937,name="Hibernal Sphere",source={ID=8497,SourceName="Nightmare Suppressor",SourceType="Kill",DropChance="0.1",Zone="The Temple of Atal'Hakkar"}}
items[15982] = {id=15982,name="Bloodwoven Rod",source={ID=6502,SourceName="Plated Stegodon",SourceType="Kill",DropChance="0.1",Zone="Un'Goro Crater"}}
items[15965] = {id=15965,name="Windchaser Orb",source={ID=193,SourceName="Blue Dragonspawn",SourceType="Kill",DropChance="0",Zone="Azshara"}}
items[12471] = {id=12471,name="Desertwalker Cane",source={ID=10081,SourceName="Dustwraith",SourceType="Kill",DropChance="21.7",Zone="Zul'Farrak"}}
items[15981] = {id=15981,name="Lunar Sphere",source={ID=5360,SourceName="Deep Strider",SourceType="Kill",DropChance="0",Zone="Feralas"}}
items[15980] = {id=15980,name="Darkmist Orb",source={ID=6193,SourceName="Spitelash Screamer",SourceType="Kill",DropChance="0.1",Zone="Azshara"}}
items[7611] = {id=7611,name="Mistscape Stave",source={ID=5280,SourceName="Nightmare Wyrmkin",SourceType="Kill",DropChance="0",Zone="The Temple of Atal'Hakkar"}}
items[7555] = {id=7555,name="Regal Star",source={ID=17235,SourceName="Witch Doctor Mai'jin",SourceType="Kill",DropChance="0.2",Zone="The Hinterlands"}}
items[15964] = {id=15964,name="Silksand Star",source={ID=5402,SourceName="Khan Hratha",SourceType="Kill",DropChance="0.1",Zone="Desolace"}}
items[6803] = {id=6803,name="Prophetic Cane",source={ID=14355,SourceName="Into The Scarlet Monastery",SourceType="Quest",DropChance="0",Zone="Scarlet Monastery"}}
items[15978] = {id=15978,name="Geomancer's Rod",source={ID=11781,SourceName="Ambershard Crusher",SourceType="Kill",DropChance="0.2",Zone="Desolace"}}
items[7610] = {id=7610,name="Aurora Sphere",source={ID=2571,SourceName="Boulderfist Lord",SourceType="Kill",DropChance="0.1",Zone="Arathi Highlands"}}
items[15108] = {id=15108,name="Orb of Dar'Orahil",source={ID=4964,SourceName="The Completed Orb of Dar'Orahil",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[15977] = {id=15977,name="Vital Orb",source={ID=23590,SourceName="Defias Conjuror",SourceType="Kill",DropChance="0.2",Zone="Dustwallow Marsh"}}
items[15929] = {id=15929,name="Nightsky Orb",source={ID=4063,SourceName="Feeboz",SourceType="Kill",DropChance="0.1",Zone="Arathi Highlands"}}
items[15935] = {id=15935,name="Durable Rod",source={ID=757,SourceName="Lost One Fisherman",SourceType="Kill",DropChance="0",Zone="Swamp of Sorrows"}}
items[15928] = {id=15928,name="Silver-thread Rod",source={ID=1200,SourceName="Morbent Fel",SourceType="Kill",DropChance="0.1",Zone="Duskwood"}}
items[15975] = {id=15975,name="Raincaller Scepter",source={ID=17300,SourceName="Gorgannon",SourceType="Kill",DropChance="0.3",Zone="Ashenvale"}}
items[10709] = {id=10709,name="Pyrestone Orb",source={ID=3507,SourceName="Betrayed",SourceType="Quest",DropChance="0",Zone="Orgrimmar"}}
items[11870] = {id=11870,name="Oblivion Orb",source={ID=4510,SourceName="Calm Before the Storm",SourceType="Quest",DropChance="0",Zone="Darnassus"}}
items[9914] = {id=9914,name="Royal Scepter",source={ID=678,SourceName="Mosh'Ogg Mauler",SourceType="Kill",DropChance="0",Zone="Stranglethorn Vale"}}
items[11859] = {id=11859,name="Jademoon Orb",source={ID=2976,SourceName="A Grim Discovery",SourceType="Quest",DropChance="0",Zone="Feralas"}}
items[11262] = {id=11262,name="Orb of Lorica",source={ID=1053,SourceName="In the Name of the Light",SourceType="Quest",DropChance="0",Zone="Scarlet Monastery"}}
items[9882] = {id=9882,name="Sorcerer Sphere",source={ID=2640,SourceName="Vilebranch Witch Doctor",SourceType="Kill",DropChance="0",Zone="The Hinterlands"}}
items[4125] = {id=4125,name="Tranquil Orb",source={ID=206,SourceName="Mai'Zoth",SourceType="Quest",DropChance="0",Zone="Stranglethorn Vale"}}
items[10770] = {id=10770,name="Mordresh's Lifeless Skull",source={ID=7357,SourceName="Mordresh Fire Eye",SourceType="Kill",DropChance="32.8",Zone="Razorfen Downs"}}
items[7556] = {id=7556,name="Twilight Orb",source={ID=2420,SourceName="Targ",SourceType="Kill",DropChance="0.1",Zone="Alterac Mountains"}}
items[15963] = {id=15963,name="Stonecloth Branch",source={ID=23590,SourceName="Defias Conjuror",SourceType="Kill",DropChance="0.2",Zone="Dustwallow Marsh"}}
items[7609] = {id=7609,name="Elder's Amber Stave",source={ID=943,SourceName="Kurzen Wrangler",SourceType="Kill",DropChance="0.5",Zone="Stranglethorn Vale"}}
items[45854] = {id=45854,name="Rituals of the New Moon",source={ID=64051,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[35609] = {id=35609,name="Talisman of Scourge Command",source={ID=29308,SourceName="Prince Taldaram",SourceType="Kill",DropChance="33.0",Zone="Ahn'kahet: The Old Kingdom"}}
items[37024] = {id=37024,name="Medicine Stick",source={ID=11613,SourceName="Karuk's Oath",SourceType="Quest",DropChance="0",Zone="Borean Tundra"}}
items[18602] = {id=18602,name="Tome of Sacrifice",source={ID=7583,SourceName="Suppression",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[45849] = {id=45849,name="Twilight Tome",source={ID=64053,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[36462] = {id=36462,name="Coldarra Crystal",source={ID=27949,SourceName="Alliance Commander",SourceType="Kill",DropChance="1.2",Zone="The Nexus"}}
items[35858] = {id=35858,name="Tome of Alacrity",source={ID=11307,SourceName="Field Test",SourceType="Quest",DropChance="0",Zone="Howling Fjord"}}
items[45850] = {id=45850,name="Rituals of the New Moon",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[45010] = {id=45010,name="Mining: The Pick and You",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13353] = {id=13353,name="Book of the Dead",source={ID=10812,SourceName="Grand Crusader Dathrohan",SourceType="Kill",DropChance="1.8",Zone="Stratholme"}}
items[36461] = {id=36461,name="Demon-Skull Orb",source={ID=26333,SourceName="Corrupted Lothalor Ancient",SourceType="Kill",DropChance="0.6",Zone="Dragonblight"}}
items[4696] = {id=4696,name="Lapidis Tankard of Tidesippe",source={ID=15741,SourceName="Colossus of Regal",SourceType="Kill",DropChance="25.0",Zone="Silithus"}}
items[37817] = {id=37817,name="Branch of Sinful Reprieve",source={ID=27860,SourceName="Luthion the Vile",SourceType="Kill",DropChance="0.8",Zone="Borean Tundra"}}
items[30857] = {id=30857,name="Deep Core Lantern",source={ID=10630,SourceName="Beneath Thrallmar",SourceType="Quest",DropChance="0",Zone="Hellfire Peninsula"}}
items[15986] = {id=15986,name="Bonecaster's Star",source={ID=14308,SourceName="Ferra",SourceType="Kill",DropChance="0.1",Zone="Dire Maul"}}
items[45853] = {id=45853,name="Rituals of the New Moon",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[36465] = {id=36465,name="Evergreen Branch",source={ID=26828,SourceName="Magister Keldonus",SourceType="Kill",DropChance="0.7",Zone="Dragonblight"}}
items[34206] = {id=34206,name="Book of Highborne Hymns",source={ID=25166,SourceName="Grand Warlock Alythess",SourceType="Kill",DropChance="18.3",Zone="Sunwell Plateau"}}
items[29269] = {id=29269,name="Sapphiron's Wing Bone",source={ID=18525,SourceName="G'eras",SourceType="Purchase",DropChance="100",Zone="Shattrath City"}}
items[21597] = {id=21597,name="Royal Scepter of Vek'lor",source={ID=15276,SourceName="Emperor Vek'lor",SourceType="Kill",DropChance="8.1",Zone="Ahn'Qiraj"}}
items[21666] = {id=21666,name="Sartura's Might",source={ID=15516,SourceName="Battleguard Sartura",SourceType="Kill",DropChance="8.4",Zone="Ahn'Qiraj"}}
items[15989] = {id=15989,name="Eternal Rod",source={ID=6109,SourceName="Azuregos",SourceType="Kill",DropChance="3.1",Zone="Azshara"}}
items[43666] = {id=43666,name="Hellfire Tome",source={ID=59495,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[19315] = {id=19315,name="Therazane's Touch",source={ID=13216,SourceName="Gaelden Hammersmith",SourceType="Purchase",DropChance="100",Zone="Alterac Valley"}}
items[15930] = {id=15930,name="Imperial Red Scepter",source={ID=9678,SourceName="Shill Dinger",SourceType="Kill",DropChance="0.2",Zone="Blackrock Depths"}}
items[45852] = {id=45852,name="Rituals of the New Moon",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[35598] = {id=35598,name="Tome of the Lore Keepers",source={ID=26763,SourceName="Anomalus",SourceType="Kill",DropChance="31.8",Zone="The Nexus"}}
items[39124] = {id=39124,name="Branch of Insightful Dreams",source={ID=12152,SourceName="Jin'arrak's End",SourceType="Quest",DropChance="0",Zone="Grizzly Hills"}}
items[37033] = {id=37033,name="Manual of the Tides",source={ID=11968,SourceName="The Tides Turn",SourceType="Quest",DropChance="0",Zone="Borean Tundra"}}
items[31715] = {id=31715,name="Demoniac Soul Prison",source={ID=10838,SourceName="The Demoniac Scryer",SourceType="Quest",DropChance="0",Zone="Hellfire Peninsula"}}
items[45851] = {id=45851,name="Rituals of the New Moon",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[36464] = {id=36464,name="Darkened Scepter",source={ID=26862,SourceName="Anthis",SourceType="Kill",DropChance="1.8",Zone="Grizzly Hills"}}
items[38293] = {id=38293,name="Suntouched Flowers",source={ID=12140,SourceName="All Hail Roanauk!",SourceType="Quest",DropChance="0",Zone="Dragonblight"}}
items[38217] = {id=38217,name="Tome of the Violet Tower",source={ID=12107,SourceName="The End of the Line",SourceType="Quest",DropChance="0",Zone="Dragonblight"}}
items[36459] = {id=36459,name="Icy Orb",source={ID=24215,SourceName="Jlarborn the Strategist",SourceType="Kill",DropChance="0.4",Zone="Howling Fjord"}}
items[27534] = {id=27534,name="Hortus' Seal of Brilliance",source={ID=16808,SourceName="Warchief Kargath Bladefist",SourceType="Kill",DropChance="14.3",Zone="The Shattered Halls"}}
items[29270] = {id=29270,name="Flametongue Seal",source={ID=18525,SourceName="G'eras",SourceType="Purchase",DropChance="100",Zone="Shattrath City"}}
items[31823] = {id=31823,name="Book of Many Blessings",source={ID=10921,SourceName="Terokkarantula",SourceType="Quest",DropChance="0",Zone="Terokkar Forest"}}
items[25090] = {id=25090,name="Slavehandler Rod",source={ID=19354,SourceName="Arzeth the Merciless",SourceType="Kill",DropChance="0.3",Zone="Hellfire Peninsula"}}
items[25088] = {id=25088,name="Laughing Skull Orb",source={ID=19312,SourceName="Drillmaster Zurok",SourceType="Kill",DropChance="0.3",Zone="Hellfire Peninsula"}}
items[25086] = {id=25086,name="Dreamseeker Dandelion",source={ID=19261,SourceName="Infernal Warbringer",SourceType="Kill",DropChance="0.2",Zone="Hellfire Peninsula"}}
items[17067] = {id=17067,name="Ancient Cornerstone Grimoire",source={ID=10184,SourceName="Onyxia",SourceType="Kill",DropChance="21.4",Zone="Onyxia's Lair"}}
items[19312] = {id=19312,name="Lei of the Lifegiver",source={ID=13216,SourceName="Gaelden Hammersmith",SourceType="Purchase",DropChance="100",Zone="Alterac Valley"}}
items[43667] = {id=43667,name="Book of Clever Tricks",source={ID=59496,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[15938] = {id=15938,name="Mystical Orb",source={ID=10584,SourceName="Urok Doomhowl",SourceType="Kill",DropChance="0.2",Zone="Blackrock Spire"}}
items[38224] = {id=38224,name="Life Binder Talisman",source={ID=12151,SourceName="Wanton Warlord",SourceType="Quest",DropChance="0",Zone="Dragonblight"}}
items[38214] = {id=38214,name="Hypergizmatic Energy Booster",source={ID=11701,SourceName="Back to the Airstrip",SourceType="Quest",DropChance="0",Zone="Borean Tundra"}}
items[28387] = {id=28387,name="Lamp of Peaceful Repose",source={ID=20885,SourceName="Dalliah the Doomsayer",SourceType="Kill",DropChance="18.5",Zone="The Arcatraz"}}
items[29274] = {id=29274,name="Tears of Heaven",source={ID=18525,SourceName="G'eras",SourceType="Purchase",DropChance="100",Zone="Shattrath City"}}
items[31493] = {id=31493,name="Netherwing Spiritualist's Charm",source={ID=10870,SourceName="Ally of the Netherwing",SourceType="Quest",DropChance="0",Zone="Shadowmoon Valley"}}
items[29170] = {id=29170,name="Windcaller's Orb",source={ID=17904,SourceName="Fedryen Swiftspear",SourceType="Purchase",DropChance="100",Zone="Zangarmarsh"}}
items[25091] = {id=25091,name="Mistyreed Torch",source={ID=17846,SourceName="Pit Spectator",SourceType="Kill",DropChance="3.2",Zone="Unknown"}}
items[23048] = {id=23048,name="Sapphiron's Right Eye",source={ID=15989,SourceName="Sapphiron",SourceType="Kill",DropChance="3.2",Zone="Naxxramas"}}
items[23469] = {id=23469,name="High Warlord's Tome of Mending",source={ID=12794,SourceName="Stone Guard Zarg",SourceType="Purchase",DropChance="100",Zone="Orgrimmar"}}
items[18695] = {id=18695,name="Spellbound Tome",source={ID=10508,SourceName="Ras Frostwhisper",SourceType="Kill",DropChance="15.2",Zone="Scholomance"}}
items[15931] = {id=15931,name="Arcane Star",source={ID=10439,SourceName="Ramstein the Gorger",SourceType="Kill",DropChance="0.4",Zone="Stratholme"}}
items[18425] = {id=18425,name="Kreeg's Mug",source={ID=14322,SourceName="Stomper Kreeg",SourceType="Kill",DropChance="53.5",Zone="Dire Maul"}}
items[18672] = {id=18672,name="Elemental Ember",source={ID=14461,SourceName="Baron Charr",SourceType="Kill",DropChance="45.5",Zone="Un'Goro Crater"}}
items[15985] = {id=15985,name="Arachnidian Branch",source={ID=14351,SourceName="Gordok Bushwacker",SourceType="Kill",DropChance="0.1",Zone="Dire Maul"}}
items[35016] = {id=35016,name="Brutal Gladiator's Grimoire",source={ID=26352,SourceName="Big Zokk Torquewrench",SourceType="Purchase",DropChance="100",Zone="Netherstorm"}}
items[34179] = {id=34179,name="Heart of the Pit",source={ID=25158,SourceName="Brutallus",SourceType="Kill",DropChance="40.0",Zone="Unknown"}}
items[30872] = {id=30872,name="Chronicle of Dark Secrets",source={ID=17767,SourceName="Rage Winterchill",SourceType="Kill",DropChance="16.1",Zone="Hyjal Summit"}}
items[28346] = {id=28346,name="Gladiator's Endgame",source={ID=18898,SourceName="Explodyne Fizzlespurt",SourceType="Purchase",DropChance="100",Zone="Nagrand"}}
items[28213] = {id=28213,name="Lordaeron Medical Guide",source={ID=17848,SourceName="Lieutenant Drake",SourceType="Kill",DropChance="5.0",Zone="Old Hillsbrad Foothills"}}
items[29272] = {id=29272,name="Orb of the Soul-Eater",source={ID=18525,SourceName="G'eras",SourceType="Purchase",DropChance="100",Zone="Shattrath City"}}
items[29273] = {id=29273,name="Khadgar's Knapsack",source={ID=18525,SourceName="G'eras",SourceType="Purchase",DropChance="100",Zone="Shattrath City"}}
items[31494] = {id=31494,name="Netherwing Sorceror's Charm",source={ID=10870,SourceName="Ally of the Netherwing",SourceType="Quest",DropChance="0",Zone="Shadowmoon Valley"}}
items[32651] = {id=32651,name="Crystal Orb of Enlightenment",source={ID=23428,SourceName="Jho'nass",SourceType="Purchase",DropChance="100",Zone="Blade's Edge Mountains"}}
items[25094] = {id=25094,name="Eldr'naan Scepter",source={ID=22160,SourceName="Bloodmaul Taskmaster",SourceType="Kill",DropChance="0.5",Zone="Blade's Edge Mountains"}}
items[31732] = {id=31732,name="Unearthed Orb",source={ID=10887,SourceName="Escaping the Tomb",SourceType="Quest",DropChance="0",Zone="Terokkar Forest"}}
items[23049] = {id=23049,name="Sapphiron's Left Eye",source={ID=15989,SourceName="Sapphiron",SourceType="Kill",DropChance="3.0",Zone="Naxxramas"}}
items[15988] = {id=15988,name="Resplendent Orb",source={ID=12129,SourceName="Onyxian Warder",SourceType="Kill",DropChance="0.3",Zone="Unknown"}}
items[15805] = {id=15805,name="Penelope's Rose",source={ID=5384,SourceName="Kirtonos the Herald",SourceType="Quest",DropChance="0",Zone="Scholomance"}}
items[36467] = {id=36467,name="Reflecting Sphere",source={ID=28034,SourceName="Drakkari Snake Handler",SourceType="Kill",DropChance="0.1",Zone="Zul'Drak"}}
items[35074] = {id=35074,name="Brutal Gladiator's Reprieve",source={ID=26352,SourceName="Big Zokk Torquewrench",SourceType="Purchase",DropChance="100",Zone="Netherstorm"}}
items[35008] = {id=35008,name="Brutal Gladiator's Endgame",source={ID=26352,SourceName="Big Zokk Torquewrench",SourceType="Purchase",DropChance="100",Zone="Netherstorm"}}
items[36463] = {id=36463,name="Polished Orb",source={ID=27508,SourceName="Necrolord Amarion",SourceType="Kill",DropChance="0.7",Zone="Dragonblight"}}
items[32350] = {id=32350,name="Touch of Inspiration",source={ID=23420,SourceName="Essence of Anger",SourceType="Kill",DropChance="15.8",Zone="Black Temple"}}
items[32361] = {id=32361,name="Blind-Seers Icon",source={ID=22841,SourceName="Shade of Akama",SourceType="Kill",DropChance="12.6",Zone="Black Temple"}}
items[32961] = {id=32961,name="Merciless Gladiator's Reprieve",source={ID=12782,SourceName="Captain O'Neal",SourceType="Purchase",DropChance="100",Zone="Alterac Valley"}}
items[33325] = {id=33325,name="Voodoo Shaker",source={ID=18525,SourceName="G'eras",SourceType="Purchase",DropChance="100",Zone="Shattrath City"}}
items[33334] = {id=33334,name="Fetish of the Primal Gods",source={ID=18525,SourceName="G'eras",SourceType="Purchase",DropChance="100",Zone="Shattrath City"}}
items[29923] = {id=29923,name="Talisman of the Sun King",source={ID=19514,SourceName="Al'ar",SourceType="Kill",DropChance="19.0",Zone="Tempest Keep"}}
items[30049] = {id=30049,name="Fathomstone",source={ID=21932,SourceName="Hydross the Unstable",SourceType="Kill",DropChance="24.2",Zone="Unknown"}}
items[199710] = {id=199710,name="Collective Rose",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[25098] = {id=25098,name="Tuurik Torch",source={ID=20911,SourceName="Blackwing Drakonaar",SourceType="Kill",DropChance="1.2",Zone="The Arcatraz"}}
items[27477] = {id=27477,name="Faol's Signet of Cleansing",source={ID=17308,SourceName="Omor the Unscarred",SourceType="Kill",DropChance="3.6",Zone="Hellfire Ramparts"}}
items[29330] = {id=29330,name="The Saga of Terokk",source={ID=10098,SourceName="Terokk's Legacy",SourceType="Quest",DropChance="0",Zone="Auchindoun"}}
items[27714] = {id=27714,name="Swamplight Lantern",source={ID=17942,SourceName="Quagmirran",SourceType="Kill",DropChance="7.4",Zone="The Slave Pens"}}
items[28941] = {id=28941,name="Grand Marshal's Battletome",source={ID=12782,SourceName="Captain O'Neal",SourceType="Purchase",DropChance="100",Zone="Alterac Valley"}}
items[25097] = {id=25097,name="Astralaan Orb",source={ID=23222,SourceName="Bonechewer Brawler",SourceType="Kill",DropChance="1.1",Zone="Black Temple"}}
items[31699] = {id=31699,name="Imbued Draenethyst Crystal",source={ID=10857,SourceName="Teleport This!",SourceType="Quest",DropChance="0",Zone="Netherstorm"}}
items[31731] = {id=31731,name="Mekeda's Gift",source={ID=10887,SourceName="Escaping the Tomb",SourceType="Quest",DropChance="0",Zone="Terokkar Forest"}}
items[25092] = {id=25092,name="Consortium Crystal",source={ID=17814,SourceName="Lordaeron Watchman",SourceType="Kill",DropChance="0.2",Zone="Unknown"}}
items[25089] = {id=25089,name="Supplicant's Rod",source={ID=19312,SourceName="Drillmaster Zurok",SourceType="Kill",DropChance="0.4",Zone="Hellfire Peninsula"}}
items[25087] = {id=25087,name="Bleeding Eye",source={ID=17455,SourceName="Bonechewer Beastmaster",SourceType="Kill",DropChance="0.2",Zone="Hellfire Ramparts"}}
items[19366] = {id=19366,name="Master Dragonslayer's Orb",source={ID=7782,SourceName="The Lord of Blackrock",SourceType="Quest",DropChance="0",Zone="Stormwind City"}}
items[22937] = {id=22937,name="Gem of Nerubis",source={ID=15956,SourceName="Anub'Rekhan",SourceType="Kill",DropChance="10.8",Zone="Naxxramas"}}
items[22994] = {id=22994,name="Digested Hand of Power",source={ID=15932,SourceName="Gluth",SourceType="Kill",DropChance="9.9",Zone="Naxxramas"}}
items[23029] = {id=23029,name="Noth's Frigid Heart",source={ID=15954,SourceName="Noth the Plaguebringer",SourceType="Kill",DropChance="8.3",Zone="Naxxramas"}}
items[23452] = {id=23452,name="Grand Marshal's Tome of Power",source={ID=12784,SourceName="Lieutenant Jackspring",SourceType="Purchase",DropChance="100",Zone="Stormwind City"}}
items[23453] = {id=23453,name="Grand Marshal's Tome of Restoration",source={ID=12784,SourceName="Lieutenant Jackspring",SourceType="Purchase",DropChance="100",Zone="Stormwind City"}}
items[23462] = {id=23462,name="High Warlord's Tome of Destruction",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[23468] = {id=23468,name="High Warlord's Tome of Destruction",source={ID=12794,SourceName="Stone Guard Zarg",SourceType="Purchase",DropChance="100",Zone="Orgrimmar"}}
items[20582] = {id=20582,name="Trance Stone",source={ID=14887,SourceName="Ysondre",SourceType="Kill",DropChance="16.3",Zone="Duskwood"}}
items[19142] = {id=19142,name="Fire Runed Grimoire",source={ID=11982,SourceName="Magmadar",SourceType="Kill",DropChance="6.3",Zone="Molten Core"}}
items[21471] = {id=21471,name="Talon of Furious Concentration",source={ID=15340,SourceName="Moam",SourceType="Kill",DropChance="9.6",Zone="Ruins of Ahn'Qiraj"}}
items[19922] = {id=19922,name="Arlokk's Hoodoo Stick",source={ID=14515,SourceName="High Priestess Arlokk",SourceType="Kill",DropChance="24.4",Zone="Zul'Gurub"}}
items[19891] = {id=19891,name="Jin'do's Bag of Whammies",source={ID=11380,SourceName="Jin'do the Hexxer",SourceType="Kill",DropChance="14.4",Zone="Zul'Gurub"}}
items[19308] = {id=19308,name="Tome of Arcane Domination",source={ID=13216,SourceName="Gaelden Hammersmith",SourceType="Purchase",DropChance="100",Zone="Alterac Valley"}}
items[19309] = {id=19309,name="Tome of Shadow Force",source={ID=13216,SourceName="Gaelden Hammersmith",SourceType="Purchase",DropChance="100",Zone="Alterac Valley"}}
items[19310] = {id=19310,name="Tome of the Ice Lord",source={ID=13216,SourceName="Gaelden Hammersmith",SourceType="Purchase",DropChance="100",Zone="Alterac Valley"}}
items[19311] = {id=19311,name="Tome of Fiery Arcana",source={ID=13216,SourceName="Gaelden Hammersmith",SourceType="Purchase",DropChance="100",Zone="Alterac Valley"}}
items[15942] = {id=15942,name="Master's Rod",source={ID=18338,SourceName="Highlord Kruul",SourceType="Kill",DropChance="5.5",Zone="Searing Gorge"}}
items[15941] = {id=15941,name="High Councillor's Scepter",source={ID=12464,SourceName="Death Talon Seether",SourceType="Kill",DropChance="0.1",Zone="Blackwing Lair"}}
items[15968] = {id=15968,name="Elunarian Sphere",source={ID=15235,SourceName="Vekniss Stinger",SourceType="Kill",DropChance="0",Zone="Ahn'Qiraj"}}
items[18523] = {id=18523,name="Brightly Glowing Stone",source={ID=11501,SourceName="King Gordok",SourceType="Kill",DropChance="24.2",Zone="Dire Maul"}}
items[21185] = {id=21185,name="Earthcalm Orb",source={ID=8574,SourceName="Stalwart's Battlegear",SourceType="Quest",DropChance="0",Zone="Silithus"}}
items[23156] = {id=23156,name="Blackwood's Thigh",source={ID=14695,SourceName="Lord Blackwood",SourceType="Kill",DropChance="26.7",Zone="Scholomance"}}
items[15940] = {id=15940,name="Elegant Scepter",source={ID=10439,SourceName="Ramstein the Gorger",SourceType="Kill",DropChance="0.4",Zone="Stratholme"}}
items[15987] = {id=15987,name="Astral Orb",source={ID=12476,SourceName="Emeraldon Oracle",SourceType="Kill",DropChance="0.3",Zone="Ashenvale"}}
items[22319] = {id=22319,name="Tome of Divine Right",source={ID=16080,SourceName="Mor Grayhoof",SourceType="Kill",DropChance="20.3",Zone="Blackrock Spire"}}
items[13385] = {id=13385,name="Tome of Knowledge",source={ID=10811,SourceName="Archivist Galford",SourceType="Kill",DropChance="13.6",Zone="Stratholme"}}
items[11928] = {id=11928,name="Thaurissan's Royal Scepter",source={ID=9019,SourceName="Emperor Dagran Thaurissan",SourceType="Kill",DropChance="18.7",Zone="Blackrock Depths"}}
items[20694] = {id=20694,name="Glowing Black Orb",source={ID=15184,SourceName="Cenarion Hold Infantry",SourceType="Kill",DropChance="1.2",Zone="Silithus"}}
items[15939] = {id=15939,name="Councillor's Scepter",source={ID=11143,SourceName="Postmaster Malown",SourceType="Kill",DropChance="0.4",Zone="Stratholme"}}
items[15967] = {id=15967,name="Highborne Star",source={ID=11465,SourceName="Warpwood Stomper",SourceType="Kill",DropChance="0.1",Zone="Dire Maul"}}
items[18536] = {id=18536,name="Milli's Lexicon",source={ID=5526,SourceName="Shards of the Felvine",SourceType="Quest",DropChance="0",Zone="Moonglade"}}
items[15984] = {id=15984,name="Opulent Scepter",source={ID=6129,SourceName="Draconic Magelord",SourceType="Kill",DropChance="0.3",Zone="Azshara"}}
items[39827] = {id=39827,name="Vile Tome of Tenets",source={ID=12596,SourceName="Pa'Troll",SourceType="Quest",DropChance="0",Zone="Zul'Drak"}}
items[38755] = {id=38755,name="Scepter of Passionate Reprisal",source={ID=12134,SourceName="Sasha's Hunt",SourceType="Quest",DropChance="0",Zone="Grizzly Hills"}}
items[39118] = {id=39118,name="Glowing Voodoo Orb",source={ID=12152,SourceName="Jin'arrak's End",SourceType="Quest",DropChance="0",Zone="Grizzly Hills"}}
items[33736] = {id=33736,name="Vengeful Gladiator's Reprieve",source={ID=20278,SourceName="Vixton Pinchwhistle",SourceType="Purchase",DropChance="100",Zone="Netherstorm"}}
items[31978] = {id=31978,name="Merciless Gladiator's Endgame",source={ID=12782,SourceName="Captain O'Neal",SourceType="Purchase",DropChance="100",Zone="Alterac Valley"}}
items[36460] = {id=36460,name="Northern Star",source={ID=24238,SourceName="Bjorn Halgurdsson",SourceType="Kill",DropChance="0.8",Zone="Howling Fjord"}}
items[32452] = {id=32452,name="Gladiator's Reprieve",source={ID=18898,SourceName="Explodyne Fizzlespurt",SourceType="Purchase",DropChance="100",Zone="Nagrand"}}
items[25099] = {id=25099,name="Draenei Crystal Rod",source={ID=21304,SourceName="Warder Corpse",SourceType="Kill",DropChance="9.3",Zone="The Arcatraz"}}
items[32533] = {id=32533,name="Karrog's Shard",source={ID=23165,SourceName="Karrog",SourceType="Kill",DropChance="18.5",Zone="Terokkar Forest"}}
items[28728] = {id=28728,name="Aran's Soothing Sapphire",source={ID=16524,SourceName="Shade of Aran",SourceType="Kill",DropChance="15.5",Zone="Karazhan"}}
items[28412] = {id=28412,name="Lamp of Peaceful Radiance",source={ID=21466,SourceName="Harbinger Skyriss",SourceType="Kill",DropChance="20.7",Zone="The Arcatraz"}}
items[28187] = {id=28187,name="Star-Heart Lamp",source={ID=17880,SourceName="Temporus",SourceType="Kill",DropChance="15.6",Zone="The Black Morass"}}
items[23463] = {id=23463,name="High Warlord's Tome of Mending",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[22253] = {id=22253,name="Tome of the Lost",source={ID=10363,SourceName="General Drakkisath",SourceType="Kill",DropChance="25.4",Zone="Blackrock Spire"}}
items[22329] = {id=22329,name="Scepter of Interminable Focus",source={ID=181083,SourceName="Sothos and Jarien's Heirlooms",SourceType="Container",DropChance="26.8",Zone="Stratholme"}}
items[13524] = {id=13524,name="Skull of Burning Shadows",source={ID=10438,SourceName="Maleki the Pallid",SourceType="Kill",DropChance="17.8",Zone="Stratholme"}}
items[13261] = {id=13261,name="Globe of D'sak",source={ID=9217,SourceName="Spirestone Lord Magus",SourceType="Kill",DropChance="22.0",Zone="Blackrock Spire"}}
items[11935] = {id=11935,name="Magmus Stone",source={ID=9938,SourceName="Magmus",SourceType="Kill",DropChance="21.0",Zone="Blackrock Depths"}}
items[36466] = {id=36466,name="Facetted Orb",source={ID=28848,SourceName="Prophet of Har'koa",SourceType="Kill",DropChance="0.7",Zone="Zul'Drak"}}
items[30911] = {id=30911,name="Scepter of Purification",source={ID=17968,SourceName="Archimonde",SourceType="Kill",DropChance="12.5",Zone="Hyjal Summit"}}
items[33681] = {id=33681,name="Vengeful Gladiator's Endgame",source={ID=20278,SourceName="Vixton Pinchwhistle",SourceType="Purchase",DropChance="100",Zone="Netherstorm"}}
items[34033] = {id=34033,name="Vengeful Gladiator's Grimoire",source={ID=20278,SourceName="Vixton Pinchwhistle",SourceType="Purchase",DropChance="100",Zone="Netherstorm"}}
items[37074] = {id=37074,name="Greatmother's Talisman of Cleansing",source={ID=11689,SourceName="Return with the Bad News",SourceType="Quest",DropChance="0",Zone="Borean Tundra"}}
items[28781] = {id=28781,name="Karaborian Talisman",source={ID=17257,SourceName="Magtheridon",SourceType="Kill",DropChance="14.3",Zone="Magtheridon's Lair"}}
items[28525] = {id=28525,name="Signet of Unshakable Faith",source={ID=15687,SourceName="Moroes",SourceType="Kill",DropChance="16.2",Zone="Karazhan"}}
items[28603] = {id=28603,name="Talisman of Nightbane",source={ID=17225,SourceName="Nightbane",SourceType="Kill",DropChance="15.9",Zone="Karazhan"}}
items[28734] = {id=28734,name="Jewel of Infinite Possibilities",source={ID=15689,SourceName="Netherspite",SourceType="Kill",DropChance="18.1",Zone="Karazhan"}}
items[28938] = {id=28938,name="High Warlord's Battletome",source={ID=14581,SourceName="Sergeant Thunderhorn",SourceType="Purchase",DropChance="100",Zone="Alterac Valley"}}
items[28260] = {id=28260,name="Manual of the Nethermancer",source={ID=19221,SourceName="Nethermancer Sepethrea",SourceType="Kill",DropChance="18.9",Zone="The Mechanar"}}
items[25096] = {id=25096,name="Elementalist Star",source={ID=23584,SourceName="Amani Bear",SourceType="Kill",DropChance="0.8",Zone="Zul'Aman"}}
items[29271] = {id=29271,name="Talisman of Kalecgos",source={ID=18525,SourceName="G'eras",SourceType="Purchase",DropChance="100",Zone="Shattrath City"}}
items[32520] = {id=32520,name="Manaforged Sphere",source={ID=20520,SourceName="Ethereum Prisoner",SourceType="Kill",DropChance="1.5",Zone="Netherstorm"}}
items[25095] = {id=25095,name="Archmage Orb",source={ID=23180,SourceName="Tarren Mill Protector",SourceType="Kill",DropChance="0.4",Zone="Unknown"}}
items[25093] = {id=25093,name="Shadow Council Orb",source={ID=17814,SourceName="Lordaeron Watchman",SourceType="Kill",DropChance="0.3",Zone="Unknown"}}
items[186049] = {id=186049,name="Communal Rose",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[45271] = {id=45271,name="Ironmender",source={ID=32930,SourceName="Kologarn",SourceType="Kill",DropChance="16.8",Zone="Ulduar"}}
items[40350] = {id=40350,name="Urn of Lost Memories",source={ID=16063,SourceName="Sir Zeliek",SourceType="Kill",DropChance="14.1",Zone="Naxxramas"}}
items[45617] = {id=45617,name="Cosmos",source={ID=32871,SourceName="Algalon the Observer",SourceType="Kill",DropChance="11.3",Zone="Ulduar"}}
items[45115] = {id=45115,name="Leviathan Fueling Manual",source={ID=33113,SourceName="Flame Leviathan",SourceType="Kill",DropChance="18.9",Zone="Ulduar"}}
items[45314] = {id=45314,name="Igniter Rod",source={ID=33118,SourceName="Ignis the Furnace Master",SourceType="Kill",DropChance="19.0",Zone="Ulduar"}}
items[40698] = {id=40698,name="Ward of the Violet Citadel",source={ID=29527,SourceName="Orton Bennet",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[40273] = {id=40273,name="Surplus Limb",source={ID=16028,SourceName="Patchwerk",SourceType="Kill",DropChance="5.9",Zone="Naxxramas"}}
items[39766] = {id=39766,name="Matriarch's Spawn",source={ID=15952,SourceName="Maexxna",SourceType="Kill",DropChance="5.7",Zone="Naxxramas"}}
items[44210] = {id=44210,name="Faces of Doom",source={ID=59498,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[40699] = {id=40699,name="Handbook of Obscure Remedies",source={ID=29527,SourceName="Orton Bennet",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[39311] = {id=39311,name="Scepter of Murmuring Spirits",source={ID=27655,SourceName="Mage-Lord Urom",SourceType="Kill",DropChance="5.8",Zone="The Oculus"}}
items[40192] = {id=40192,name="Accursed Spine",source={ID=15954,SourceName="Noth the Plaguebringer",SourceType="Kill",DropChance="6.2",Zone="Naxxramas"}}
items[42526] = {id=42526,name="Furious Gladiator's Endgame",source={ID=31863,SourceName="Nargle Lashcord",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[39199] = {id=39199,name="Watchful Eye",source={ID=27977,SourceName="Krystallus",SourceType="Kill",DropChance="3.0",Zone="Halls of Stone"}}
items[50173] = {id=50173,name="Shadow Silk Spindle",source={ID=37970,SourceName="Prince Valanar",SourceType="Kill",DropChance="31.7",Zone="Icecrown Citadel"}}
items[42537] = {id=42537,name="Deadly Gladiator's Grimoire",source={ID=31863,SourceName="Nargle Lashcord",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[37889] = {id=37889,name="Prison Manifest",source={ID=30660,SourceName="Portal Guardian",SourceType="Kill",DropChance="2.8",Zone="The Violet Hold"}}
items[38322] = {id=38322,name="Iron-bound Tome",source={ID=59497,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[47064] = {id=47064,name="Symbol of Transgression",source={ID=34780,SourceName="Lord Jaraxxus",SourceType="Kill",DropChance="8.3",Zone="Trial of the Crusader"}}
items[48032] = {id=48032,name="Lightbane Focus",source={ID=34496,SourceName="Eydis Darkbane",SourceType="Kill",DropChance="6.0",Zone="Trial of the Crusader"}}
items[50309] = {id=50309,name="Shriveled Heart",source={ID=37226,SourceName="The Lich King",SourceType="Kill",DropChance="14.1",Zone="Halls of Reflection"}}
items[50719] = {id=50719,name="Shadow Silk Spindle",source={ID=37970,SourceName="Prince Valanar",SourceType="Kill",DropChance="29.2",Zone="Icecrown Citadel"}}
items[47053] = {id=47053,name="Symbol of Transgression",source={ID=34780,SourceName="Lord Jaraxxus",SourceType="Kill",DropChance="9.6",Zone="Trial of the Crusader"}}
items[47437] = {id=47437,name="Talisman of Heedless Sins",source={ID=34780,SourceName="Lord Jaraxxus",SourceType="Kill",DropChance="9.0",Zone="Trial of the Crusader"}}
items[47958] = {id=47958,name="Chalice of Benedictus",source={ID=34496,SourceName="Eydis Darkbane",SourceType="Kill",DropChance="6.5",Zone="Trial of the Crusader"}}
items[47470] = {id=47470,name="Mystifying Charm",source={ID=34496,SourceName="Eydis Darkbane",SourceType="Kill",DropChance="8.0",Zone="Trial of the Crusader"}}
items[49490] = {id=49490,name="Antediluvian Cornerstone Grimoire",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[50781] = {id=50781,name="Scourgelord's Baton",source={ID=36855,SourceName="Lady Deathwhisper",SourceType="Kill",DropChance="23.7",Zone="Icecrown Citadel"}}
items[49308] = {id=49308,name="Antique Cornerstone Grimoire",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[47742] = {id=47742,name="Chalice of Benedictus",source={ID=34496,SourceName="Eydis Darkbane",SourceType="Kill",DropChance="5.1",Zone="Trial of the Crusader"}}
items[50635] = {id=50635,name="Sundial of Eternal Dusk",source={ID=36853,SourceName="Sindragosa",SourceType="Kill",DropChance="16.0",Zone="Icecrown Citadel"}}
items[42530] = {id=42530,name="Hateful Gladiator's Reprieve",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[42525] = {id=42525,name="Deadly Gladiator's Endgame",source={ID=31863,SourceName="Nargle Lashcord",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[42536] = {id=42536,name="Hateful Gladiator's Grimoire",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[37364] = {id=37364,name="Frostbridge Orb",source={ID=27635,SourceName="Azure Spellbinder",SourceType="Kill",DropChance="2.5",Zone="The Oculus"}}
items[47309] = {id=47309,name="Mystifying Charm",source={ID=34496,SourceName="Eydis Darkbane",SourceType="Kill",DropChance="8.1",Zone="Trial of the Crusader"}}
items[42796] = {id=42796,name="Lantern of Enchanted Flame",source={ID=12984,SourceName="Valduran the Stormborn",SourceType="Quest",DropChance="0",Zone="The Storm Peaks"}}
items[50423] = {id=50423,name="Sundial of Eternal Dusk",source={ID=36853,SourceName="Sindragosa",SourceType="Kill",DropChance="16.5",Zone="Icecrown Citadel"}}
items[38458] = {id=38458,name="Darkspear Orb",source={ID=32565,SourceName="Gara Skullcrush",SourceType="Purchase",DropChance="100",Zone="Borean Tundra"}}
items[49187] = {id=49187,name="Relentless Gladiator's Compendium",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[42524] = {id=42524,name="Hateful Gladiator's Endgame",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[47146] = {id=47146,name="Chalice of Searing Light",source={ID=34496,SourceName="Eydis Darkbane",SourceType="Kill",DropChance="5.1",Zone="Trial of the Crusader"}}
items[47138] = {id=47138,name="Chalice of Searing Light",source={ID=34496,SourceName="Eydis Darkbane",SourceType="Kill",DropChance="6.5",Zone="Trial of the Crusader"}}
items[47276] = {id=47276,name="Talisman of Heedless Sins",source={ID=34780,SourceName="Lord Jaraxxus",SourceType="Kill",DropChance="9.5",Zone="Trial of the Crusader"}}
items[42532] = {id=42532,name="Furious Gladiator's Reprieve",source={ID=31863,SourceName="Nargle Lashcord",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[37051] = {id=37051,name="Seal of Valgarde",source={ID=26687,SourceName="Gortok Palehoof",SourceType="Kill",DropChance="27.1",Zone="Utgarde Pinnacle"}}
items[42538] = {id=42538,name="Furious Gladiator's Grimoire",source={ID=31863,SourceName="Nargle Lashcord",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[38459] = {id=38459,name="Orb of the Eastern Kingdoms",source={ID=32564,SourceName="Logistics Officer Silverstone",SourceType="Purchase",DropChance="100",Zone="Borean Tundra"}}
items[37134] = {id=37134,name="Telestra's Journal",source={ID=26731,SourceName="Grand Magus Telestra",SourceType="Kill",DropChance="25.1",Zone="The Nexus"}}
items[51922] = {id=51922,name="Scourgelord's Baton",source={ID=36855,SourceName="Lady Deathwhisper",SourceType="Kill",DropChance="26.6",Zone="Icecrown Citadel"}}
items[42533] = {id=42533,name="Relentless Gladiator's Reprieve",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[47913] = {id=47913,name="Lightbane Focus",source={ID=34496,SourceName="Eydis Darkbane",SourceType="Kill",DropChance="5.5",Zone="Trial of the Crusader"}}
items[42531] = {id=42531,name="Deadly Gladiator's Reprieve",source={ID=31863,SourceName="Nargle Lashcord",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[42535] = {id=42535,name="Savage Gladiator's Grimoire",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[44022] = {id=44022,name="The Witching Grimoire",source={ID=13142,SourceName="Banshee's Revenge",SourceType="Quest",DropChance="0",Zone="Icecrown"}}
items[44023] = {id=44023,name="Bonecaster's Endgame",source={ID=13142,SourceName="Banshee's Revenge",SourceType="Quest",DropChance="0",Zone="Icecrown"}}
items[36469] = {id=36469,name="Lidless Orb",source={ID=31224,SourceName="Icefury",SourceType="Kill",DropChance="5.2",Zone="Icecrown"}}
items[51408] = {id=51408,name="Wrathful Gladiator's Grimoire",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[51396] = {id=51396,name="Wrathful Gladiator's Endgame",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[42523] = {id=42523,name="Savage Gladiator's Endgame",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[42529] = {id=42529,name="Savage Gladiator's Reprieve",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[51407] = {id=51407,name="Wrathful Gladiator's Compendium",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[51409] = {id=51409,name="Wrathful Gladiator's Reprieve",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[42527] = {id=42527,name="Relentless Gladiator's Endgame",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[37718] = {id=37718,name="Temple Crystal Fragment",source={ID=26631,SourceName="Novos the Summoner",SourceType="Kill",DropChance="23.8",Zone="Drak'Tharon Keep"}}
items[37086] = {id=37086,name="Tome of Salramm",source={ID=26530,SourceName="Salramm the Fleshcrafter",SourceType="Kill",DropChance="22.1",Zone="The Culling of Stratholme"}}
items[36471] = {id=36471,name="Ice Crystal",source={ID=37149,SourceName="Kor'kron Necrolyte",SourceType="Kill",DropChance="1.5",Zone="Unknown"}}
items[36470] = {id=36470,name="Gilded Scepter",source={ID=31225,SourceName="Plaguehoof",SourceType="Kill",DropChance="4.1",Zone="Icecrown"}}
items[36468] = {id=36468,name="Glistening Star",source={ID=29885,SourceName="Mildred the Cruel",SourceType="Kill",DropChance="16.6",Zone="The Storm Peaks"}}
items[42539] = {id=42539,name="Relentless Gladiator's Grimoire",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[36472] = {id=36472,name="Carved Rod",source={ID=32492,SourceName="Frostbrood Matriarch",SourceType="Kill",DropChance="20.0",Zone="Icecrown"}}
items[6295] = {id=6295,name="15 Pound Mud Snapper",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[34484] = {id=34484,name="Old Ironjaw",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13917] = {id=13917,name="103 Pound Mightfish",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[34486] = {id=34486,name="Old Crafty",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[16967] = {id=16967,name="Feralas Ahi",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[27516] = {id=27516,name="Enormous Barbed Gill Trout",source={ID=33844,SourceName="Barrel of Fish",SourceType="Container",DropChance="19.1",Zone="Unknown"}}
items[6364] = {id=6364,name="32 Pound Catfish",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13887] = {id=13887,name="52 Pound Redgill",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[27515] = {id=27515,name="Huge Spotted Feltail",source={ID=33844,SourceName="Barrel of Fish",SourceType="Container",DropChance="17.8",Zone="Unknown"}}
items[16768] = {id=16768,name="Furbolg Medicine Pouch",source={ID=11555,SourceName="Gorn One Eye",SourceType="Purchase",DropChance="100",Zone="Felwood"}}
items[44678] = {id=44678,name="Wine Glass",source={ID=32337,SourceName="Christi Stockton",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[13905] = {id=13905,name="29 Pound Salmon",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[44679] = {id=44679,name="Red Wine Glass",source={ID=32337,SourceName="Christi Stockton",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[43327] = {id=43327,name="Stratholme Lily",source={ID=31021,SourceName="Sophie Aaren",SourceType="Purchase",DropChance="100",Zone="The Culling of Stratholme"}}
items[44731] = {id=44731,name="Bouquet of Ebon Roses",source={ID=23953,SourceName="Prince Keleseth",SourceType="Kill",DropChance="2.7",Zone="Utgarde Keep"}}
items[46861] = {id=46861,name="Bouquet of Orange Marigolds",source={ID=34382,SourceName="Chapman",SourceType="Purchase",DropChance="100",Zone="Dalaran"}}
items[43886] = {id=43886,name="QR IC34 Healer Offhand - PH",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[44802] = {id=44802,name="Egg Basket",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13371] = {id=13371,name="Father Flame",source={ID=175245,SourceName="Father Flame",SourceType="Container",DropChance="100.0",Zone="Blackrock Spire"}}
items[6310] = {id=6310,name="19 Pound Catfish",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[3421] = {id=3421,name="Simple Wildflowers",source={ID=8766,SourceName="Forest Ooze",SourceType="Kill",DropChance="0",Zone="Azshara"}}
items[6309] = {id=6309,name="17 Pound Catfish",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[22206] = {id=22206,name="Bouquet of Red Roses",source={ID=23953,SourceName="Prince Keleseth",SourceType="Kill",DropChance="2.8",Zone="Utgarde Keep"}}
items[39147] = {id=39147,name="113 Pound Swordfish",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[3419] = {id=3419,name="Red Rose",source={ID=10952,SourceName="Marauding Skeleton",SourceType="Kill",DropChance="41.6",Zone="Eastern Plaguelands"}}
items[39832] = {id=39832,name="QR ZD26 Spell Offhand - PH",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[34140] = {id=34140,name="Dark Iron Tankard",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[23844] = {id=23844,name="Nolkai's Lantern",source={ID=23846,SourceName="Nolkai's Box",SourceType="Container",DropChance="98.5",Zone="Unknown"}}
items[6292] = {id=6292,name="10 Pound Mud Snapper",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[6294] = {id=6294,name="12 Pound Mud Snapper",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[2410] = {id=2410,name="Smoky Torch",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[7297] = {id=7297,name="Morbent's Bane",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13902] = {id=13902,name="18 Pound Salmon",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[6311] = {id=6311,name="22 Pound Catfish",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13906] = {id=13906,name="32 Pound Salmon",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13914] = {id=13914,name="70 Pound Mightfish",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13915] = {id=13915,name="85 Pound Mightfish",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[34829] = {id=34829,name="Ornate Drinking Stein",source={ID=34863,SourceName="Bag of Fishing Treasures",SourceType="Container",DropChance="1.0",Zone="Unknown"}}
items[13901] = {id=13901,name="15 Pound Salmon",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13885] = {id=13885,name="34 Pound Redgill",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[11522] = {id=11522,name="Silver Totem of Aquementas",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[3424] = {id=3424,name="Bouquet of Black Roses",source={ID=1302,SourceName="Bernard Gump",SourceType="Purchase",DropChance="100",Zone="Stormwind City"}}
items[33014] = {id=33014,name="Fine Poking Stick",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13903] = {id=13903,name="22 Pound Salmon",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13904] = {id=13904,name="25 Pound Salmon",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13916] = {id=13916,name="92 Pound Mightfish",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13886] = {id=13886,name="37 Pound Redgill",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[6899] = {id=6899,name="Warlock Orb 35",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[8626] = {id=8626,name="Blue Sparkler",source={ID=8116,SourceName="Ziggle Sparks",SourceType="Purchase",DropChance="100",Zone="Stranglethorn Vale"}}
items[23691] = {id=23691,name="Corrupted Mark of the Lightbringer",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[6653] = {id=6653,name="Torch of the Dormant Flame",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[3423] = {id=3423,name="Bouquet of White Roses",source={ID=1302,SourceName="Bernard Gump",SourceType="Purchase",DropChance="100",Zone="Stormwind City"}}
items[6363] = {id=6363,name="26 Pound Catfish",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[33012] = {id=33012,name="Terokkar Lilac",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13882] = {id=13882,name="42 Pound Redgill",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13883] = {id=13883,name="45 Pound Redgill",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[13884] = {id=13884,name="49 Pound Redgill",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}
items[3420] = {id=3420,name="Black Rose",source={ID=1302,SourceName="Bernard Gump",SourceType="Purchase",DropChance="100",Zone="Stormwind City"}}
items[3422] = {id=3422,name="Beautiful Wildflowers",source={ID=1302,SourceName="Bernard Gump",SourceType="Purchase",DropChance="100",Zone="Stormwind City"}}
items[8625] = {id=8625,name="White Sparkler",source={ID=8116,SourceName="Ziggle Sparks",SourceType="Purchase",DropChance="100",Zone="Stranglethorn Vale"}}
items[8624] = {id=8624,name="Red Sparkler",source={ID=8116,SourceName="Ziggle Sparks",SourceType="Purchase",DropChance="100",Zone="Stranglethorn Vale"}}
items[3675] = {id=3675,name="Burnt Out Torch",source={ID=0,SourceName="",SourceType="Unknown",DropChance="0",Zone=""}}

names["Darkmoon Flower"] = 19295
names["Stitches' Femur"] = 3360
names["Torch of Holy Flame"] = 7344
names["Totem of Infliction"] = 1131
names["Mystic Tome"] = 43515
names["Egg Basket"] = 45067
names["Buccaneer's Orb"] = 15912
names["Everglow Lantern"] = 5323
names["Eerie Stable Lantern"] = 6341
names["Ritual Stein"] = 15972
names["Book of Survival"] = 43655
names["Sunwell Orb"] = 22784
names["Journeyman's Stave"] = 15925
names["Eye of Paleth"] = 2943
names["Watcher's Star"] = 15973
names["Simple Branch"] = 15933
names["Witch's Finger"] = 16887
names["Grayson's Torch"] = 1172
names["Sanguine Star"] = 15947
names["Venomous Tome"] = 38579
names["Veildust Medicine Bag"] = 15866
names["Pagan Rod"] = 15974
names["Tome of the Dawn"] = 43654
names["Bouquet of Scarlet Begonias"] = 2562
names["Tork Wrench"] = 11855
names["Spellbinder Orb"] = 15926
names["Ley Orb"] = 7508
names["Dim Torch"] = 6182
names["Antipodean Rod"] = 2879
names["Tear of Grief"] = 5611
names["Beaded Orb"] = 15969
names["Bright Sphere"] = 15927
names["Greenweave Branch"] = 9769
names["Orb of Soran'ruk"] = 6898
names["Mystic's Sphere"] = 15946
names["Pulsating Hydra Heart"] = 5183
names["Aboriginal Rod"] = 15971
names["Runic Stave"] = 15945
names["Carved Crystalline Orb"] = 27398
names["Divining Crystal"] = 23401
names["Native Branch"] = 15970
names["Disciple's Stein"] = 15932
names["Ancestral Orb"] = 15944
names["Strength of Will"] = 4837
names["Ivy Orb"] = 9800
names["Orb of Mistmantle"] = 13031
names["Fireproof Orb"] = 4836
names["Orb of Power"] = 4838
names["Shimmering Stave"] = 7558
names["Seer's Fine Stein"] = 7608
names["Jadefinger Baton"] = 15206
names["Willow Branch"] = 7554
names["Nightglow Concoction"] = 3451
names["Runic Cane"] = 7559
names["Arcane Orb"] = 7507
names["Torch of the Eternal Flame"] = 6654
names["Skull of Impending Doom"] = 4984
names["Stormbound Tome"] = 43663
names["Drakestone"] = 10796
names["Tome of Kings"] = 43656
names["Manual of Clouds"] = 43664
names["Fire Eater's Guide"] = 43660
names["Celestial Orb"] = 7515
names["Spirit of Aquementas"] = 11904
names["Basilisk Bone"] = 13030
names["Gossamer Rod"] = 7557
names["Beacon of Hope"] = 9393
names["Royal Guide of Escape Routes"] = 43657
names["Book of Stars"] = 43661
names["Umbral Crystal"] = 13029
names["Omega Orb"] = 7749
names["Swampchill Fetish"] = 1992
names["Venomshroud Orb"] = 15966
names["Cloud Stone"] = 17737
names["Enthralled Sphere"] = 11625
names["Gaea's Scepter"] = 15983
names["Flask of Forest Mojo"] = 19115
names["Thermotastic Egg Timer"] = 9644
names["Lord Sakrasis' Scepter"] = 5028
names["Explorers' League Lodestar"] = 9627
names["Orb of Noh'Orahil"] = 15107
names["Orb of the Forgotten Seer"] = 7685
names["Book of the Adept"] = 33266
names["Thistlefur Branch"] = 15976
names["Rod of Molten Fire"] = 2565
names["Magebane Scion"] = 15857
names["Shard of the Green Flame"] = 18762
names["Embersilk Stave"] = 15979
names["Uthek's Finger"] = 6774
names["Conjurer's Sphere"] = 15918
names["Satyr's Rod"] = 15962
names["Sage's Stave"] = 15934
names["Cursed Eye of Paleth"] = 2944
names["Duskwoven Branch"] = 15936
names["Abjurer's Crystal"] = 9944
names["Skullspell Orb"] = 10708
names["Hibernal Sphere"] = 15937
names["Bloodwoven Rod"] = 15982
names["Windchaser Orb"] = 15965
names["Desertwalker Cane"] = 12471
names["Lunar Sphere"] = 15981
names["Darkmist Orb"] = 15980
names["Mistscape Stave"] = 7611
names["Regal Star"] = 7555
names["Silksand Star"] = 15964
names["Prophetic Cane"] = 6803
names["Geomancer's Rod"] = 15978
names["Aurora Sphere"] = 7610
names["Orb of Dar'Orahil"] = 15108
names["Vital Orb"] = 15977
names["Nightsky Orb"] = 15929
names["Durable Rod"] = 15935
names["Silver-thread Rod"] = 15928
names["Raincaller Scepter"] = 15975
names["Pyrestone Orb"] = 10709
names["Oblivion Orb"] = 11870
names["Royal Scepter"] = 9914
names["Jademoon Orb"] = 11859
names["Orb of Lorica"] = 11262
names["Sorcerer Sphere"] = 9882
names["Tranquil Orb"] = 4125
names["Mordresh's Lifeless Skull"] = 10770
names["Twilight Orb"] = 7556
names["Stonecloth Branch"] = 15963
names["Elder's Amber Stave"] = 7609
names["Rituals of the New Moon"] = 45854
names["Talisman of Scourge Command"] = 35609
names["Medicine Stick"] = 37024
names["Tome of Sacrifice"] = 18602
names["Twilight Tome"] = 45849
names["Coldarra Crystal"] = 36462
names["Tome of Alacrity"] = 35858
names["Rituals of the New Moon"] = 45850
names["Mining: The Pick and You"] = 45010
names["Book of the Dead"] = 13353
names["Demon-Skull Orb"] = 36461
names["Lapidis Tankard of Tidesippe"] = 4696
names["Branch of Sinful Reprieve"] = 37817
names["Deep Core Lantern"] = 30857
names["Bonecaster's Star"] = 15986
names["Rituals of the New Moon"] = 45853
names["Evergreen Branch"] = 36465
names["Book of Highborne Hymns"] = 34206
names["Sapphiron's Wing Bone"] = 29269
names["Royal Scepter of Vek'lor"] = 21597
names["Sartura's Might"] = 21666
names["Eternal Rod"] = 15989
names["Hellfire Tome"] = 43666
names["Therazane's Touch"] = 19315
names["Imperial Red Scepter"] = 15930
names["Rituals of the New Moon"] = 45852
names["Tome of the Lore Keepers"] = 35598
names["Branch of Insightful Dreams"] = 39124
names["Manual of the Tides"] = 37033
names["Demoniac Soul Prison"] = 31715
names["Rituals of the New Moon"] = 45851
names["Darkened Scepter"] = 36464
names["Suntouched Flowers"] = 38293
names["Tome of the Violet Tower"] = 38217
names["Icy Orb"] = 36459
names["Hortus' Seal of Brilliance"] = 27534
names["Flametongue Seal"] = 29270
names["Book of Many Blessings"] = 31823
names["Slavehandler Rod"] = 25090
names["Laughing Skull Orb"] = 25088
names["Dreamseeker Dandelion"] = 25086
names["Ancient Cornerstone Grimoire"] = 17067
names["Lei of the Lifegiver"] = 19312
names["Book of Clever Tricks"] = 43667
names["Mystical Orb"] = 15938
names["Life Binder Talisman"] = 38224
names["Hypergizmatic Energy Booster"] = 38214
names["Lamp of Peaceful Repose"] = 28387
names["Tears of Heaven"] = 29274
names["Netherwing Spiritualist's Charm"] = 31493
names["Windcaller's Orb"] = 29170
names["Mistyreed Torch"] = 25091
names["Sapphiron's Right Eye"] = 23048
names["High Warlord's Tome of Mending"] = 23469
names["Spellbound Tome"] = 18695
names["Arcane Star"] = 15931
names["Kreeg's Mug"] = 18425
names["Elemental Ember"] = 18672
names["Arachnidian Branch"] = 15985
names["Brutal Gladiator's Grimoire"] = 35016
names["Heart of the Pit"] = 34179
names["Chronicle of Dark Secrets"] = 30872
names["Gladiator's Endgame"] = 28346
names["Lordaeron Medical Guide"] = 28213
names["Orb of the Soul-Eater"] = 29272
names["Khadgar's Knapsack"] = 29273
names["Netherwing Sorceror's Charm"] = 31494
names["Crystal Orb of Enlightenment"] = 32651
names["Eldr'naan Scepter"] = 25094
names["Unearthed Orb"] = 31732
names["Sapphiron's Left Eye"] = 23049
names["Resplendent Orb"] = 15988
names["Penelope's Rose"] = 15805
names["Reflecting Sphere"] = 36467
names["Brutal Gladiator's Reprieve"] = 35074
names["Brutal Gladiator's Endgame"] = 35008
names["Polished Orb"] = 36463
names["Touch of Inspiration"] = 32350
names["Blind-Seers Icon"] = 32361
names["Merciless Gladiator's Reprieve"] = 32961
names["Voodoo Shaker"] = 33325
names["Fetish of the Primal Gods"] = 33334
names["Talisman of the Sun King"] = 29923
names["Fathomstone"] = 30049
names["Collective Rose"] = 199710
names["Tuurik Torch"] = 25098
names["Faol's Signet of Cleansing"] = 27477
names["The Saga of Terokk"] = 29330
names["Swamplight Lantern"] = 27714
names["Grand Marshal's Battletome"] = 28941
names["Astralaan Orb"] = 25097
names["Imbued Draenethyst Crystal"] = 31699
names["Mekeda's Gift"] = 31731
names["Consortium Crystal"] = 25092
names["Supplicant's Rod"] = 25089
names["Bleeding Eye"] = 25087
names["Master Dragonslayer's Orb"] = 19366
names["Gem of Nerubis"] = 22937
names["Digested Hand of Power"] = 22994
names["Noth's Frigid Heart"] = 23029
names["Grand Marshal's Tome of Power"] = 23452
names["Grand Marshal's Tome of Restoration"] = 23453
names["High Warlord's Tome of Destruction"] = 23462
names["High Warlord's Tome of Destruction"] = 23468
names["Trance Stone"] = 20582
names["Fire Runed Grimoire"] = 19142
names["Talon of Furious Concentration"] = 21471
names["Arlokk's Hoodoo Stick"] = 19922
names["Jin'do's Bag of Whammies"] = 19891
names["Tome of Arcane Domination"] = 19308
names["Tome of Shadow Force"] = 19309
names["Tome of the Ice Lord"] = 19310
names["Tome of Fiery Arcana"] = 19311
names["Master's Rod"] = 15942
names["High Councillor's Scepter"] = 15941
names["Elunarian Sphere"] = 15968
names["Brightly Glowing Stone"] = 18523
names["Earthcalm Orb"] = 21185
names["Blackwood's Thigh"] = 23156
names["Elegant Scepter"] = 15940
names["Astral Orb"] = 15987
names["Tome of Divine Right"] = 22319
names["Tome of Knowledge"] = 13385
names["Thaurissan's Royal Scepter"] = 11928
names["Glowing Black Orb"] = 20694
names["Councillor's Scepter"] = 15939
names["Highborne Star"] = 15967
names["Milli's Lexicon"] = 18536
names["Opulent Scepter"] = 15984
names["Vile Tome of Tenets"] = 39827
names["Scepter of Passionate Reprisal"] = 38755
names["Glowing Voodoo Orb"] = 39118
names["Vengeful Gladiator's Reprieve"] = 33736
names["Merciless Gladiator's Endgame"] = 31978
names["Northern Star"] = 36460
names["Gladiator's Reprieve"] = 32452
names["Draenei Crystal Rod"] = 25099
names["Karrog's Shard"] = 32533
names["Aran's Soothing Sapphire"] = 28728
names["Lamp of Peaceful Radiance"] = 28412
names["Star-Heart Lamp"] = 28187
names["High Warlord's Tome of Mending"] = 23463
names["Tome of the Lost"] = 22253
names["Scepter of Interminable Focus"] = 22329
names["Skull of Burning Shadows"] = 13524
names["Globe of D'sak"] = 13261
names["Magmus Stone"] = 11935
names["Facetted Orb"] = 36466
names["Scepter of Purification"] = 30911
names["Vengeful Gladiator's Endgame"] = 33681
names["Vengeful Gladiator's Grimoire"] = 34033
names["Greatmother's Talisman of Cleansing"] = 37074
names["Karaborian Talisman"] = 28781
names["Signet of Unshakable Faith"] = 28525
names["Talisman of Nightbane"] = 28603
names["Jewel of Infinite Possibilities"] = 28734
names["High Warlord's Battletome"] = 28938
names["Manual of the Nethermancer"] = 28260
names["Elementalist Star"] = 25096
names["Talisman of Kalecgos"] = 29271
names["Manaforged Sphere"] = 32520
names["Archmage Orb"] = 25095
names["Shadow Council Orb"] = 25093
names["Communal Rose"] = 186049
names["Ironmender"] = 45271
names["Urn of Lost Memories"] = 40350
names["Cosmos"] = 45617
names["Leviathan Fueling Manual"] = 45115
names["Igniter Rod"] = 45314
names["Ward of the Violet Citadel"] = 40698
names["Surplus Limb"] = 40273
names["Matriarch's Spawn"] = 39766
names["Faces of Doom"] = 44210
names["Handbook of Obscure Remedies"] = 40699
names["Scepter of Murmuring Spirits"] = 39311
names["Accursed Spine"] = 40192
names["Furious Gladiator's Endgame"] = 42526
names["Watchful Eye"] = 39199
names["Shadow Silk Spindle"] = 50173
names["Deadly Gladiator's Grimoire"] = 42537
names["Prison Manifest"] = 37889
names["Iron-bound Tome"] = 38322
names["Symbol of Transgression"] = 47064
names["Lightbane Focus"] = 48032
names["Shriveled Heart"] = 50309
names["Shadow Silk Spindle"] = 50719
names["Symbol of Transgression"] = 47053
names["Talisman of Heedless Sins"] = 47437
names["Chalice of Benedictus"] = 47958
names["Mystifying Charm"] = 47470
names["Antediluvian Cornerstone Grimoire"] = 49490
names["Scourgelord's Baton"] = 50781
names["Antique Cornerstone Grimoire"] = 49308
names["Chalice of Benedictus"] = 47742
names["Sundial of Eternal Dusk"] = 50635
names["Hateful Gladiator's Reprieve"] = 42530
names["Deadly Gladiator's Endgame"] = 42525
names["Hateful Gladiator's Grimoire"] = 42536
names["Frostbridge Orb"] = 37364
names["Mystifying Charm"] = 47309
names["Lantern of Enchanted Flame"] = 42796
names["Sundial of Eternal Dusk"] = 50423
names["Darkspear Orb"] = 38458
names["Relentless Gladiator's Compendium"] = 49187
names["Hateful Gladiator's Endgame"] = 42524
names["Chalice of Searing Light"] = 47146
names["Chalice of Searing Light"] = 47138
names["Talisman of Heedless Sins"] = 47276
names["Furious Gladiator's Reprieve"] = 42532
names["Seal of Valgarde"] = 37051
names["Furious Gladiator's Grimoire"] = 42538
names["Orb of the Eastern Kingdoms"] = 38459
names["Telestra's Journal"] = 37134
names["Scourgelord's Baton"] = 51922
names["Relentless Gladiator's Reprieve"] = 42533
names["Lightbane Focus"] = 47913
names["Deadly Gladiator's Reprieve"] = 42531
names["Savage Gladiator's Grimoire"] = 42535
names["The Witching Grimoire"] = 44022
names["Bonecaster's Endgame"] = 44023
names["Lidless Orb"] = 36469
names["Wrathful Gladiator's Grimoire"] = 51408
names["Wrathful Gladiator's Endgame"] = 51396
names["Savage Gladiator's Endgame"] = 42523
names["Savage Gladiator's Reprieve"] = 42529
names["Wrathful Gladiator's Compendium"] = 51407
names["Wrathful Gladiator's Reprieve"] = 51409
names["Relentless Gladiator's Endgame"] = 42527
names["Temple Crystal Fragment"] = 37718
names["Tome of Salramm"] = 37086
names["Ice Crystal"] = 36471
names["Gilded Scepter"] = 36470
names["Glistening Star"] = 36468
names["Relentless Gladiator's Grimoire"] = 42539
names["Carved Rod"] = 36472
names["15 Pound Mud Snapper"] = 6295
names["Old Ironjaw"] = 34484
names["103 Pound Mightfish"] = 13917
names["Old Crafty"] = 34486
names["Feralas Ahi"] = 16967
names["Enormous Barbed Gill Trout"] = 27516
names["32 Pound Catfish"] = 6364
names["52 Pound Redgill"] = 13887
names["Huge Spotted Feltail"] = 27515
names["Furbolg Medicine Pouch"] = 16768
names["Wine Glass"] = 44678
names["29 Pound Salmon"] = 13905
names["Red Wine Glass"] = 44679
names["Stratholme Lily"] = 43327
names["Bouquet of Ebon Roses"] = 44731
names["Bouquet of Orange Marigolds"] = 46861
names["QR IC34 Healer Offhand - PH"] = 43886
names["Egg Basket"] = 44802
names["Father Flame"] = 13371
names["19 Pound Catfish"] = 6310
names["Simple Wildflowers"] = 3421
names["17 Pound Catfish"] = 6309
names["Bouquet of Red Roses"] = 22206
names["113 Pound Swordfish"] = 39147
names["Red Rose"] = 3419
names["QR ZD26 Spell Offhand - PH"] = 39832
names["Dark Iron Tankard"] = 34140
names["Nolkai's Lantern"] = 23844
names["10 Pound Mud Snapper"] = 6292
names["12 Pound Mud Snapper"] = 6294
names["Smoky Torch"] = 2410
names["Morbent's Bane"] = 7297
names["18 Pound Salmon"] = 13902
names["22 Pound Catfish"] = 6311
names["32 Pound Salmon"] = 13906
names["70 Pound Mightfish"] = 13914
names["85 Pound Mightfish"] = 13915
names["Ornate Drinking Stein"] = 34829
names["15 Pound Salmon"] = 13901
names["34 Pound Redgill"] = 13885
names["Silver Totem of Aquementas"] = 11522
names["Bouquet of Black Roses"] = 3424
names["Fine Poking Stick"] = 33014
names["22 Pound Salmon"] = 13903
names["25 Pound Salmon"] = 13904
names["92 Pound Mightfish"] = 13916
names["37 Pound Redgill"] = 13886
names["Warlock Orb 35"] = 6899
names["Blue Sparkler"] = 8626
names["Corrupted Mark of the Lightbringer"] = 23691
names["Torch of the Dormant Flame"] = 6653
names["Bouquet of White Roses"] = 3423
names["26 Pound Catfish"] = 6363
names["Terokkar Lilac"] = 33012
names["42 Pound Redgill"] = 13882
names["45 Pound Redgill"] = 13883
names["49 Pound Redgill"] = 13884
names["Black Rose"] = 3420
names["Beautiful Wildflowers"] = 3422
names["White Sparkler"] = 8625
names["Red Sparkler"] = 8624
names["Burnt Out Torch"] = 3675

LE:RegisterDBItems(items)
LE:RegisterNameDBItems(names)