-------------------------------------**     LibEquippable     **-------------------------------------
-- This file is autogenerated, please do not edit it manually or fuckups might occur.
-------------------------------------**  All Rights Reserved  **-------------------------------------

local LE = LibStub and LibStub("LibEquippable-1.0", true)
if not LE  then return end

local items = {}
local names = {}


-- Item Data
items[1168] = {id=1168,name="Skullflame Shield",obtain={NpcID=15741,NpcName="Colossus of Regal",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=25.0,Zone="Silithus"}}
items[25828] = {id=25828,name="Petrified Lichen Guard",obtain={NpcID=18382,NpcName="Mycah (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Zangarmarsh"}}
items[28825] = {id=28825,name="Aldori Legacy Defender",obtain={NpcID=19044,NpcName="Gruul the Dragonkiller",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.8,Zone="Gruul's Lair"}}
items[18825] = {id=18825,name="Grand Marshal's Aegis",obtain={NpcID=12782,NpcName="Captain O'Neal (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[29458] = {id=29458,name="Aegis of the Vindicator",obtain={NpcID=17257,NpcName="Magtheridon",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=12.3,Zone="Magtheridon's Lair"}}
items[13243] = {id=13243,name="Argent Defender",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=5265,Recipe=false,RecipeID=0,DropChance=0,Zone="Eastern Plaguelands"}}
items[19321] = {id=19321,name="The Immovable Object",obtain={NpcID=13216,NpcName="Gaelden Hammersmith (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[28606] = {id=28606,name="Shield of Impenetrable Darkness",obtain={NpcID=17225,NpcName="Nightbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=14.2,Zone="Karazhan"}}
items[29266] = {id=29266,name="Azure-Shield of Coldarra",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[29176] = {id=29176,name="Crest of the Sha'tar",obtain={NpcID=21432,NpcName="Almaador (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[18826] = {id=18826,name="High Warlord's Shield Wall",obtain={NpcID=14581,NpcName="Sergeant Thunderhorn (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[18168] = {id=18168,name="Force Reactive Disk",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=22797,DropChance=0,Zone=""}}
items[28358] = {id=28358,name="Gladiator's Shield Wall",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[28166] = {id=28166,name="Shield of the Void",obtain={NpcID=18341,NpcName="Pandemonius",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=6.2,Zone="Mana-Tombs"}}
items[27887] = {id=27887,name="Platinum Shield of the Valorous",obtain={NpcID=18731,NpcName="Ambassador Hellmaw",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=20.0,Zone="Shadow Labyrinth"}}
items[29268] = {id=29268,name="Mazthoril Honor Shield",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[31200] = {id=31200,name="Shield of the Wayward Footman",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[28754] = {id=28754,name="Triptych Shield of the Ancients",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[22198] = {id=22198,name="Jagged Obsidian Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=true,RecipeID=27586,DropChance=0,Zone=""}}
items[28611] = {id=28611,name="Dragonheart Flameshield",obtain={NpcID=17225,NpcName="Nightbane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=14.2,Zone="Karazhan"}}
items[9458] = {id=9458,name="Thermaplugg's Central Core",obtain={NpcID=7800,NpcName="Mekgineer Thermaplugg",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=31.7,Zone="Gnomeregan"}}
items[23043] = {id=23043,name="The Face of Death",obtain={NpcID=15989,NpcName="Sapphiron",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=31.8,Zone="Naxxramas"}}
items[32375] = {id=32375,name="Bulwark of Azzinoth",obtain={NpcID=22917,NpcName="Illidan Stormrage",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=38.2,Zone="Black Temple"}}
items[27772] = {id=27772,name="Stormshield of Renewal",obtain={NpcID=17882,NpcName="The Black Stalker",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=16.6,Zone="The Underbog"}}
items[28316] = {id=28316,name="Aegis of the Sunbird",obtain={NpcID=17975,NpcName="High Botanist Freywinn",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="The Botanica"}}
items[21269] = {id=21269,name="Blessed Qiraji Bulwark",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=8789,Recipe=false,RecipeID=0,DropChance=0,Zone="Ahn'Qiraj"}}
items[22819] = {id=22819,name="Shield of Condemnation",obtain={NpcID=15990,NpcName="Kel'Thuzad",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=19.6,Zone="Naxxramas"}}
items[7726] = {id=7726,name="Aegis of the Scarlet Commander",obtain={NpcID=3976,NpcName="Scarlet Commander Mograine",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=43.0,Zone="Scarlet Monastery"}}
items[32082] = {id=32082,name="The Fel Barrier",obtain={NpcID=18344,NpcName="Nexus-Prince Shaffar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=11.6,Zone="Mana-Tombs"}}
items[27449] = {id=27449,name="Blood Knight Defender",obtain={NpcID=17306,NpcName="Watchkeeper Gargolmar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=20.5,Zone="Hellfire Ramparts"}}
items[31292] = {id=31292,name="Crystal Pulse Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[28940] = {id=28940,name="Grand Marshal's Barricade",obtain={NpcID=12782,NpcName="Captain O'Neal (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Alterac Valley"}}
items[23075] = {id=23075,name="Death's Bargain",obtain={NpcID=15932,NpcName="Gluth",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=35.1,Zone="Naxxramas"}}
items[29267] = {id=29267,name="Light-Bearer's Faith Shield",obtain={NpcID=18525,NpcName="G'eras (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Shattrath City"}}
items[22336] = {id=22336,name="Draconian Aegis of the Legion",obtain={NpcID=16042,NpcName="Lord Valthalak",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=23.7,Zone="Blackrock Spire"}}
items[1204] = {id=1204,name="The Green Tower",obtain={NpcID=675,NpcName="Venture Co. Foreman",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Stranglethorn Vale"}}
items[13375] = {id=13375,name="Crest of Retribution",obtain={NpcID=10439,NpcName="Ramstein the Gorger",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=11.9,Zone="Stratholme"}}
items[32652] = {id=32652,name="Ogri'la Aegis",obtain={NpcID=23428,NpcName="Jho'nass (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Blade's Edge Mountains"}}
items[31491] = {id=31491,name="Netherwing Defender's Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[31287] = {id=31287,name="Draenei Honor Guard Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[19349] = {id=19349,name="Elementium Reinforced Bulwark",obtain={NpcID=14020,NpcName="Chromaggus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=15.2,Zone="Blackwing Lair"}}
items[30909] = {id=30909,name="Antonidas's Aegis of Rapt Concentration",obtain={NpcID=17968,NpcName="Archimonde",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=15.5,Zone="Hyjal Summit"}}
items[17718] = {id=17718,name="Gizlock's Hypertech Buckler",obtain={NpcID=13601,NpcName="Tinkerer Gizlock",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=32.8,Zone="Maraudon"}}
items[34185] = {id=34185,name="Sword Breaker's Bulwark",obtain={NpcID=25038,NpcName="Felmyst",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=28.8,Zone="Sunwell Plateau"}}
items[19862] = {id=19862,name="Aegis of the Blood God",obtain={NpcID=14834,NpcName="Hakkar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=15.4,Zone="Zul'Gurub"}}
items[1203] = {id=1203,name="Aegis of Stormwind",obtain={NpcID=15741,NpcName="Colossus of Regal",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=25.0,Zone="Silithus"}}
items[13082] = {id=13082,name="Mountainside Buckler",obtain={NpcID=15816,NpcName="Qiraji Major He'al-ie",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=8.3,Zone="Thousand Needles"}}
items[17066] = {id=17066,name="Drillborer Disk",obtain={NpcID=12057,NpcName="Garr",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=26.0,Zone="Molten Core"}}
items[30882] = {id=30882,name="Bastion of Light",obtain={NpcID=17808,NpcName="Anetheron",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=15.8,Zone="Hyjal Summit"}}
items[1979] = {id=1979,name="Wall of the Dead",obtain={NpcID=950,NpcName="Swamp Talker",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Swamp of Sorrows"}}
items[30314] = {id=30314,name="Phaseshift Bulwark",obtain={NpcID=21273,NpcName="Phaseshift Bulwark",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100.0,Zone="Unknown"}}
items[19348] = {id=19348,name="Red Dragonscale Protector",obtain={NpcID=13020,NpcName="Vaelastrasz the Corrupt",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=17.0,Zone="Blackwing Lair"}}
items[10835] = {id=10835,name="Crest of Supremacy",obtain={NpcID=5709,NpcName="Shade of Eranikus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=28.4,Zone="The Temple of Atal'Hakkar"}}
items[6320] = {id=6320,name="Commander's Crest",obtain={NpcID=4278,NpcName="Commander Springvale",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=28.7,Zone="Shadowfang Keep"}}
items[27910] = {id=27910,name="Silvermoon Crest Shield",obtain={NpcID=18708,NpcName="Murmur",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=33.3,Zone="Shadow Labyrinth"}}
items[22818] = {id=22818,name="The Plague Bearer",obtain={NpcID=16028,NpcName="Patchwerk",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=31.2,Zone="Naxxramas"}}
items[21610] = {id=21610,name="Wormscale Blocker",obtain={NpcID=15517,NpcName="Ouro",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=20.4,Zone="Ahn'Qiraj"}}
items[12997] = {id=12997,name="Redbeard Crest",obtain={NpcID=15812,NpcName="Qiraji Officer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.7,Zone="The Barrens"}}
items[20912] = {id=20912,name="Large Shield",obtain={NpcID=15292,NpcName="Faraden Thelryn (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Eversong Woods"}}
items[34231] = {id=34231,name="Aegis of Angelic Fortune",obtain={NpcID=25741,NpcName="M'uru",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=35.4,Zone="Sunwell Plateau"}}
items[30984] = {id=30984,name="Spellbreaker's Buckler",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10708,Recipe=false,RecipeID=0,DropChance=0,Zone="Outland Shadowmoon Valley"}}
items[6447] = {id=6447,name="Worn Turtle Shell Shield",obtain={NpcID=3653,NpcName="Kresh",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=67.5,Zone="Wailing Caverns"}}
items[34675] = {id=34675,name="Sunward Crest",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[31490] = {id=31490,name="Netherwing Protector's Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[15633] = {id=15633,name="Formidable Crest",obtain={NpcID=8201,NpcName="Omgorn the Lost",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Tanaris"}}
items[30889] = {id=30889,name="Kaz'rogal's Hardened Heart",obtain={NpcID=17888,NpcName="Kaz'rogal",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=16.3,Zone="Hyjal Summit"}}
items[34676] = {id=34676,name="Dawnforged Defender",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[2040] = {id=2040,name="Troll Protector",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[1169] = {id=1169,name="Blackskull Shield",obtain={NpcID=1488,NpcName="Zanzil Zombie",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Stranglethorn Vale"}}
items[34011] = {id=34011,name="Illidari Runeshield",obtain={NpcID=22847,NpcName="Ashtongue Primalist",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.0,Zone="Unknown"}}
items[28939] = {id=28939,name="High Warlord's Barricade",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[25075] = {id=25075,name="Hardened Steel Shield",obtain={NpcID=17307,NpcName="Vazruden the Herald",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=6.6,Zone="Hellfire Ramparts"}}
items[13079] = {id=13079,name="Shield of Thorsen",obtain={NpcID=15814,NpcName="Qiraji Lieutenant Jo-rel",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.8,Zone="The Barrens"}}
items[18535] = {id=18535,name="Milli's Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=5526,Recipe=false,RecipeID=0,DropChance=0,Zone="Moonglade"}}
items[6694] = {id=6694,name="Heart of Agamaggan",obtain={NpcID=4421,NpcName="Charlga Razorflank",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=32.7,Zone="Razorfen Kraul"}}
items[34986] = {id=34986,name="Brutal Gladiator's Barrier",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[18485] = {id=18485,name="Observer's Shield",obtain={NpcID=14324,NpcName="Cho'Rush the Observer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=42.4,Zone="Dire Maul"}}
items[9643] = {id=9643,name="Optomatic Deflector",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=648,Recipe=false,RecipeID=0,DropChance=0,Zone="Tanaris"}}
items[25073] = {id=25073,name="Emperor Shield",obtain={NpcID=16929,NpcName="Stonescythe Alpha",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.5,Zone="Hellfire Peninsula"}}
items[6572] = {id=6572,name="Defender Shield",obtain={NpcID=5683,NpcName="Comar Villard",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Wetlands"}}
items[31734] = {id=31734,name="Ancient Draenei Crest",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10887,Recipe=false,RecipeID=0,DropChance=0,Zone="Terokkar Forest"}}
items[13083] = {id=13083,name="Garrett Family Crest",obtain={NpcID=15741,NpcName="Colossus of Regal",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=25.0,Zone="Silithus"}}
items[4129] = {id=4129,name="Collection Plate",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=613,Recipe=false,RecipeID=0,DropChance=0,Zone="Stranglethorn Vale"}}
items[33326] = {id=33326,name="Bulwark of the Amani Empire",obtain={NpcID=23578,NpcName="Jan'alai",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.3,Zone="Unknown"}}
items[33332] = {id=33332,name="Enamelled Disc of Mojo",obtain={NpcID=23578,NpcName="Jan'alai",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=8.3,Zone="Unknown"}}
items[18499] = {id=18499,name="Barrier Shield",obtain={NpcID=14353,NpcName="Mizzle the Crafty",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.4,Zone="Dire Maul"}}
items[11915] = {id=11915,name="Shizzle's Drizzle Blocker",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=4503,Recipe=false,RecipeID=0,DropChance=0,Zone="Un'Goro Crater"}}
items[15352] = {id=15352,name="Headhunter's Buckler",obtain={NpcID=7337,NpcName="Death's Head Necromancer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Razorfen Downs"}}
items[14916] = {id=14916,name="Jade Deflector",obtain={NpcID=6129,NpcName="Draconic Magelord",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Azshara"}}
items[5094] = {id=5094,name="Razormane War Shield",obtain={NpcID=3459,NpcName="Razormane Warfrenzy",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=25.0,Zone="The Barrens"}}
items[8275] = {id=8275,name="Ebonhold Buckler",obtain={NpcID=7045,NpcName="Scalding Drake",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Burning Steppes"}}
items[3987] = {id=3987,name="Deflecting Tower",obtain={NpcID=1045,NpcName="Red Dragonspawn",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.0,Zone="Wetlands"}}
items[10767] = {id=10767,name="Savage Boar's Guard",obtain={NpcID=7354,NpcName="Ragglesnout",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=40.1,Zone="Razorfen Downs"}}
items[9444] = {id=9444,name="Techbot CPU Shell",obtain={NpcID=6231,NpcName="Techbot",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=48.4,Zone="Unknown"}}
items[14902] = {id=14902,name="Saltstone Shield",obtain={NpcID=5645,NpcName="Sandfury Hideskinner",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Tanaris"}}
items[25624] = {id=25624,name="King's Bulwark",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=9907,Recipe=false,RecipeID=0,DropChance=0,Zone="Outland Nagrand"}}
items[23238] = {id=23238,name="Stygian Buckler",obtain={NpcID=16156,NpcName="Dark Touched Warrior",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.0,Zone="Naxxramas"}}
items[21485] = {id=21485,name="Buru's Skull Fragment",obtain={NpcID=15370,NpcName="Buru the Gorger",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=17.0,Zone="Ruins of Ahn'Qiraj"}}
items[10271] = {id=10271,name="Masterwork Shield",obtain={NpcID=10371,NpcName="Rage Talon Captain",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Blackrock Spire"}}
items[10367] = {id=10367,name="Hyperion Shield",obtain={NpcID=18338,NpcName="Highlord Kruul",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=3.1,Zone="Searing Gorge"}}
items[12602] = {id=12602,name="Draconian Deflector",obtain={NpcID=10363,NpcName="General Drakkisath",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=22.0,Zone="Blackrock Spire"}}
items[14002] = {id=14002,name="Darrowshire Strongguard",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=5466,Recipe=false,RecipeID=0,DropChance=0,Zone="Scholomance"}}
items[34415] = {id=34415,name="Crystaline Shard Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[13245] = {id=13245,name="Kresh's Back",obtain={NpcID=3653,NpcName="Kresh",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=13.1,Zone="Wailing Caverns"}}
items[15943] = {id=15943,name="Imbued Shield",obtain={NpcID=10439,NpcName="Ramstein the Gorger",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Stratholme"}}
items[10363] = {id=10363,name="Engraved Wall",obtain={NpcID=13334,NpcName="Veteran Legionnaire",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.8,Zone="Alterac Valley"}}
items[10204] = {id=10204,name="Heavy Lamellar Shield",obtain={NpcID=7071,NpcName="Cursed Paladin",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Hillsbrad Foothills"}}
items[14825] = {id=14825,name="Symbolic Crest",obtain={NpcID=7606,NpcName="Oro Eyegouge",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Zul'Farrak"}}
items[9858] = {id=9858,name="Archer's Buckler",obtain={NpcID=3985,NpcName="Grandpa Vishas",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Alterac Mountains"}}
items[6560] = {id=6560,name="Soldier's Shield",obtain={NpcID=3532,NpcName="Pyrewood Leatherworker",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.2,Zone="Silverpine Forest"}}
items[35094] = {id=35094,name="Brutal Gladiator's Shield Wall",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[20688] = {id=20688,name="Earthen Guard",obtain={NpcID=15205,NpcName="Baron Kazum",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=29.8,Zone="Silithus"}}
items[15675] = {id=15675,name="Magnificent Guard",obtain={NpcID=5314,NpcName="Phantim",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Ashenvale"}}
items[23139] = {id=23139,name="Lord Blackwood's Buckler",obtain={NpcID=14695,NpcName="Lord Blackwood",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=29.3,Zone="Scholomance"}}
items[9974] = {id=9974,name="Overlord's Shield",obtain={NpcID=5983,NpcName="Bonepicker",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Blasted Lands"}}
items[14777] = {id=14777,name="Ravager's Shield",obtain={NpcID=14236,NpcName="Lord Angler",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Dustwallow Marsh"}}
items[7496] = {id=7496,name="Field Plate Shield",obtain={NpcID=7321,NpcName="Stonevault Flameweaver",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Uldaman"}}
items[15569] = {id=15569,name="Marauder's Crest",obtain={NpcID=4394,NpcName="Bubbling Swamp Ooze",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.3,Zone="Dustwallow Marsh"}}
items[4821] = {id=4821,name="Bear Buckler",obtain={NpcID=793,NpcName="Kara Adams (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Redridge Mountains"}}
items[4822] = {id=4822,name="Owl's Disk",obtain={NpcID=793,NpcName="Kara Adams (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Redridge Mountains"}}
items[7108] = {id=7108,name="Infantry Shield",obtain={NpcID=16855,NpcName="Tregla",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.5,Zone="Eversong Woods"}}
items[25084] = {id=25084,name="Zeth'Gor Shield",obtain={NpcID=16460,NpcName="Night Mistress",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=33.3,Zone="Karazhan"}}
items[25407] = {id=25407,name="The Movable Object",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[10366] = {id=10366,name="Demon Guard",obtain={NpcID=13446,NpcName="Field Marshal Teravaine",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.7,Zone="Alterac Valley"}}
items[18756] = {id=18756,name="Dreadguard's Protector",obtain={NpcID=14506,NpcName="Lord Hel'nurath",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=24.4,Zone="Dire Maul"}}
items[15648] = {id=15648,name="Ironhide Shield",obtain={NpcID=10662,NpcName="Spellmaw",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.2,Zone="Winterspring"}}
items[7495] = {id=7495,name="Captain's Buckler",obtain={NpcID=1552,NpcName="Scale Belly",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Stranglethorn Vale"}}
items[7787] = {id=7787,name="Resplendent Guardian",obtain={NpcID=14693,NpcName="Scorn",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Scarlet Monastery"}}
items[2222] = {id=2222,name="Tower Shield",obtain={NpcID=4440,NpcName="Razorfen Totemic",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.0,Zone="Razorfen Kraul"}}
items[4820] = {id=4820,name="Guardian Buckler",obtain={NpcID=793,NpcName="Kara Adams (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Redridge Mountains"}}
items[6383] = {id=6383,name="Forest Buckler",obtain={NpcID=5682,NpcName="Dalin Forgewright",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Silverpine Forest"}}
items[6571] = {id=6571,name="Scouting Buckler",obtain={NpcID=1210,NpcName="Chok'sul",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Loch Modan"}}
items[15298] = {id=15298,name="Grizzly Buckler",obtain={NpcID=12319,NpcName="Burning Blade Toxicologist",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.0,Zone="The Barrens"}}
items[15486] = {id=15486,name="War Torn Shield",obtain={NpcID=3228,NpcName="Corrupted Surf Crawler",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Durotar"}}
items[8313] = {id=8313,name="Hero's Buckler",obtain={NpcID=10439,NpcName="Ramstein the Gorger",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Stratholme"}}
items[18352] = {id=18352,name="Petrified Bark Shield",obtain={NpcID=11489,NpcName="Tendris Warpwood",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=23.8,Zone="Dire Maul"}}
items[3986] = {id=3986,name="Protective Pavise",obtain={NpcID=8212,NpcName="The Reak",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.4,Zone="The Hinterlands"}}
items[7536] = {id=7536,name="Champion's Wall Shield",obtain={NpcID=10120,NpcName="Vault Warder",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.0,Zone="Uldaman"}}
items[14947] = {id=14947,name="Warbringer's Shield",obtain={NpcID=4328,NpcName="Firemane Scalebane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Dustwallow Marsh"}}
items[9918] = {id=9918,name="Brigade Defender",obtain={NpcID=7290,NpcName="Shadowforge Sharpshooter",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Uldaman"}}
items[15342] = {id=15342,name="Pathfinder Guard",obtain={NpcID=11682,NpcName="Warsong Grunt",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Ashenvale"}}
items[6598] = {id=6598,name="Dervish Buckler",obtain={NpcID=6407,NpcName="Holdout Technician",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Gnomeregan"}}
items[15512] = {id=15512,name="Grunt's Shield",obtain={NpcID=3899,NpcName="Balizar the Umbrage",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Darkshore"}}
items[15113] = {id=15113,name="Rigid Buckler",obtain={NpcID=3670,NpcName="Lord Pythas",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Wailing Caverns"}}
items[6380] = {id=6380,name="Inscribed Buckler",obtain={NpcID=2106,NpcName="Apothecary Berard",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Silverpine Forest"}}
items[3649] = {id=3649,name="Tribal Buckler",obtain={NpcID=5785,NpcName="Sister Hatelash",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.4,Zone="Mulgore"}}
items[2211] = {id=2211,name="Bent Large Shield",obtain={NpcID=1918,NpcName="Karrel Grayves",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=6.4,Zone="Tirisfal Glades"}}
items[17184] = {id=17184,name="Small Shield",obtain={NpcID=1104,NpcName="Grundel Harkin (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Dun Morogh"}}
items[33661] = {id=33661,name="Vengeful Gladiator's Barrier",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[33735] = {id=33735,name="Vengeful Gladiator's Redoubt",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[32255] = {id=32255,name="Felstone Bulwark",obtain={NpcID=22898,NpcName="Supremus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=18.3,Zone="Black Temple"}}
items[25085] = {id=25085,name="Dragonscale Shield",obtain={NpcID=23333,NpcName="The Grand Collector",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=9.3,Zone="Unknown"}}
items[25076] = {id=25076,name="Screaming Shield",obtain={NpcID=18311,NpcName="Ethereal Crypt Raider",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=7.6,Zone="Mana-Tombs"}}
items[25074] = {id=25074,name="Telaari Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[15887] = {id=15887,name="Heroic Guard",obtain={NpcID=5320,NpcName="Jademir Boughguard",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Feralas"}}
items[10362] = {id=10362,name="Ornate Shield",obtain={NpcID=7734,NpcName="Ilifar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Blasted Lands"}}
items[14930] = {id=14930,name="Lofty Shield",obtain={NpcID=10806,NpcName="Ursius",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Winterspring"}}
items[3990] = {id=3990,name="Crested Buckler",obtain={NpcID=6130,NpcName="Blue Scalebane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.8,Zone="Azshara"}}
items[14790] = {id=14790,name="Protector Buckler",obtain={NpcID=6129,NpcName="Draconic Magelord",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Azshara"}}
items[14954] = {id=14954,name="Bloodforged Shield",obtain={NpcID=3094,NpcName="Unseen",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Duskwood"}}
items[15618] = {id=15618,name="Bonelink Wall Shield",obtain={NpcID=11793,NpcName="Celebrian Dryad",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Maraudon"}}
items[9899] = {id=9899,name="Jazeraint Shield",obtain={NpcID=2781,NpcName="Caretaker Weston",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Arathi Highlands"}}
items[4070] = {id=4070,name="Jouster's Crest",obtain={NpcID=2782,NpcName="Caretaker Alaric",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Arathi Highlands"}}
items[15367] = {id=15367,name="Trickster's Protector",obtain={NpcID=23637,NpcName="Deserter Lieutenant",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.7,Zone="Dustwallow Marsh"}}
items[7463] = {id=7463,name="Sentinel Buckler",obtain={NpcID=814,NpcName="Sergeant Malthus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Stranglethorn Vale"}}
items[4065] = {id=4065,name="Combat Shield",obtain={NpcID=861,NpcName="Stonard Scout",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Swamp of Sorrows"}}
items[9522] = {id=9522,name="Energized Stone Circle",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=2418,Recipe=false,RecipeID=0,DropChance=0,Zone="Uldaman"}}
items[15145] = {id=15145,name="Ghostwalker Buckler",obtain={NpcID=7332,NpcName="Withered Spearhide",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Razorfen Downs"}}
items[17189] = {id=17189,name="Metal Buckler",obtain={NpcID=1319,NpcName="Bryan Cross (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Stormwind City"}}
items[9830] = {id=9830,name="Scaled Shield",obtain={NpcID=4284,NpcName="Scarlet Augur",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Tirisfal Glades"}}
items[2221] = {id=2221,name="Targe Shield",obtain={NpcID=6407,NpcName="Holdout Technician",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.3,Zone="Gnomeregan"}}
items[15123] = {id=15123,name="Robust Buckler",obtain={NpcID=4440,NpcName="Razorfen Totemic",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Razorfen Kraul"}}
items[2446] = {id=2446,name="Kite Shield",obtain={NpcID=226,NpcName="Morg Gnarltree (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Duskwood"}}
items[15504] = {id=15504,name="Outrunner's Shield",obtain={NpcID=5931,NpcName="Foreman Rigger",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Stonetalon Mountains"}}
items[3655] = {id=3655,name="Burnished Shield",obtain={NpcID=16317,NpcName="Deatholme Necromancer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Ghostlands"}}
items[5443] = {id=5443,name="Gold-plated Buckler",obtain={NpcID=3586,NpcName="Miner Johnson",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=41.0,Zone="The Deadmines"}}
items[9790] = {id=9790,name="Raider's Shield",obtain={NpcID=17592,NpcName="Razormaw",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.8,Zone="Bloodmyst Isle"}}
items[1202] = {id=1202,name="Wall Shield",obtain={NpcID=3319,NpcName="Sana (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Orgrimmar"}}
items[2214] = {id=2214,name="Wooden Buckler",obtain={NpcID=1271,NpcName="Old Icebeard",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.1,Zone="Dun Morogh"}}
items[2215] = {id=2215,name="Wooden Shield",obtain={NpcID=17210,NpcName="Sentinel Leader",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.5,Zone="Ghostlands"}}
items[1438] = {id=1438,name="Warrior's Shield",obtain={NpcID=15642,NpcName="Amani Shadowpriest",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Eversong Woods"}}
items[15006] = {id=15006,name="Primal Buckler",obtain={NpcID=15636,NpcName="Eversong Green Keeper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.4,Zone="Eversong Woods"}}
items[2213] = {id=2213,name="Worn Large Shield",obtain={NpcID=15636,NpcName="Eversong Green Keeper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=4.4,Zone="Eversong Woods"}}
items[876] = {id=876,name="Worn Wooden Buckler",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[32045] = {id=32045,name="Merciless Gladiator's Shield Wall",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[33313] = {id=33313,name="Merciless Gladiator's Barrier",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[25079] = {id=25079,name="Outland Shield",obtain={NpcID=18313,NpcName="Ethereal Sorcerer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.8,Zone="Mana-Tombs"}}
items[25627] = {id=25627,name="QR 9922 Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[19915] = {id=19915,name="Zulian Defender",obtain={NpcID=14517,NpcName="High Priestess Jeklik",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=18.6,Zone="Zul'Gurub"}}
items[14528] = {id=14528,name="Rattlecage Buckler",obtain={NpcID=11622,NpcName="Rattlegore",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=12.1,Zone="Scholomance"}}
items[18673] = {id=18673,name="Avalanchion's Stony Hide",obtain={NpcID=14464,NpcName="Avalanchion",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=21.3,Zone="Azshara"}}
items[10364] = {id=10364,name="Templar Shield",obtain={NpcID=10762,NpcName="Blackhand Thug",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Blackrock Spire"}}
items[15657] = {id=15657,name="Merciless Shield",obtain={NpcID=11498,NpcName="Skarr the Unbreakable",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Unknown"}}
items[14964] = {id=14964,name="High Chief's Shield",obtain={NpcID=13021,NpcName="Warpwood Crusher",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Dire Maul"}}
items[10093] = {id=10093,name="Revenant Deflector",obtain={NpcID=5720,NpcName="Weaver",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="The Temple of Atal'Hakkar"}}
items[14852] = {id=14852,name="Sunscale Shield",obtain={NpcID=6502,NpcName="Plated Stegodon",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Un'Goro Crater"}}
items[10078] = {id=10078,name="Lord's Crest",obtain={NpcID=9319,NpcName="Houndmaster Grebmar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Blackrock Depths"}}
items[8134] = {id=8134,name="Myrmidon's Defender",obtain={NpcID=8497,NpcName="Nightmare Suppressor",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="The Temple of Atal'Hakkar"}}
items[8282] = {id=8282,name="Valorous Shield",obtain={NpcID=8282,NpcName="Highlord Mastrogonde",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.7,Zone="Searing Gorge"}}
items[2444] = {id=2444,name="Rusted Buckler",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[9958] = {id=9958,name="Warmonger's Buckler",obtain={NpcID=8497,NpcName="Nightmare Suppressor",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="The Temple of Atal'Hakkar"}}
items[4069] = {id=4069,name="Blackforge Buckler",obtain={NpcID=5401,NpcName="Kazkaz the Unholy",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Unknown"}}
items[15592] = {id=15592,name="Steadfast Buckler",obtain={NpcID=7605,NpcName="Raven",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Zul'Farrak"}}
items[15584] = {id=15584,name="Sparkleshell Shield",obtain={NpcID=4385,NpcName="Withervine Rager",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Dustwallow Marsh"}}
items[9403] = {id=9403,name="Battered Viking Shield",obtain={NpcID=6908,NpcName="Olaf",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=78.5,Zone="Uldaman"}}
items[15990] = {id=15990,name="Enduring Shield",obtain={NpcID=14232,NpcName="Dart",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Dustwallow Marsh"}}
items[6828] = {id=6828,name="Visionary Buckler",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=1393,Recipe=false,RecipeID=0,DropChance=0,Zone="Swamp of Sorrows"}}
items[13081] = {id=13081,name="Skullance Shield",obtain={NpcID=15815,NpcName="Qiraji Captain Ka'ark",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=20.0,Zone="Thousand Needles"}}
items[15563] = {id=15563,name="Pillager's Shield",obtain={NpcID=23589,NpcName="Defias Rummager",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Dustwallow Marsh"}}
items[15552] = {id=15552,name="Thick Scale Shield",obtain={NpcID=7332,NpcName="Withered Spearhide",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Razorfen Downs"}}
items[4066] = {id=4066,name="Insignia Buckler",obtain={NpcID=24830,NpcName="Stonevault Pillager",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.7,Zone="Uldaman"}}
items[15543] = {id=15543,name="Wicked Chain Shield",obtain={NpcID=5935,NpcName="Ironeye the Invincible",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Thousand Needles"}}
items[7330] = {id=7330,name="Infiltrator Buckler",obtain={NpcID=6230,NpcName="Peacekeeper Security Suit",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Gnomeregan"}}
items[9843] = {id=9843,name="Banded Shield",obtain={NpcID=2552,NpcName="Witherbark Troll",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Arathi Highlands"}}
items[15892] = {id=15892,name="Slayer's Shield",obtain={NpcID=5934,NpcName="Heartrazor",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.7,Zone="Thousand Needles"}}
items[15522] = {id=15522,name="Spiked Chain Shield",obtain={NpcID=3789,NpcName="Terrowulf Fleshripper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Ashenvale"}}
items[3656] = {id=3656,name="Lambent Scale Shield",obtain={NpcID=1014,NpcName="Mosshide Alpha",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Wetlands"}}
items[15891] = {id=15891,name="Hulking Shield",obtain={NpcID=4112,NpcName="Gravelsnout Vermin",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Thousand Needles"}}
items[9816] = {id=9816,name="Fortified Shield",obtain={NpcID=898,NpcName="Nightbane Worgen",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Duskwood"}}
items[2220] = {id=2220,name="Box Shield",obtain={NpcID=3898,NpcName="Aligar the Tormentor",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.7,Zone="Darkshore"}}
items[2219] = {id=2219,name="Small Round Shield",obtain={NpcID=431,NpcName="Shadowhide Slayer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=3.4,Zone="Redridge Mountains"}}
items[2445] = {id=2445,name="Large Metal Shield",obtain={NpcID=793,NpcName="Kara Adams (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Redridge Mountains"}}
items[2021] = {id=2021,name="Green Carapace Shield",obtain={NpcID=569,NpcName="Green Recluse",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.1,Zone="Duskwood"}}
items[15893] = {id=15893,name="Prospector's Buckler",obtain={NpcID=17494,NpcName="Zevrax",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.8,Zone="Bloodmyst Isle"}}
items[9778] = {id=9778,name="Bandit Buckler",obtain={NpcID=14266,NpcName="Shanda the Spinner",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Loch Modan"}}
items[4290] = {id=4290,name="Dust Bowl",obtain={NpcID=832,NpcName="Dust Devil",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.5,Zone="Westfall"}}
items[2217] = {id=2217,name="Rectangular Shield",obtain={NpcID=16247,NpcName="Borgoth the Bloodletter",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=6.6,Zone="Ghostlands"}}
items[3654] = {id=3654,name="Brackwater Shield",obtain={NpcID=12319,NpcName="Burning Blade Toxicologist",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.0,Zone="The Barrens"}}
items[17187] = {id=17187,name="Banded Buckler",obtain={NpcID=3319,NpcName="Sana (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Orgrimmar"}}
items[9753] = {id=9753,name="Gypsy Buckler",obtain={NpcID=16854,NpcName="Eldinarcus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.0,Zone="Eversong Woods"}}
items[3648] = {id=3648,name="Warrior's Buckler",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[3650] = {id=3650,name="Battle Shield",obtain={NpcID=2968,NpcName="Galak Outrunner",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Mulgore"}}
items[2129] = {id=2129,name="Large Round Shield",obtain={NpcID=1104,NpcName="Grundel Harkin (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Dun Morogh"}}
items[21021] = {id=21021,name="Battered Shield",obtain={NpcID=15372,NpcName="Springpaw Lynx",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.0,Zone="Eversong Woods"}}
items[17183] = {id=17183,name="Dented Buckler",obtain={NpcID=2116,NpcName="Blacksmith Rand (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Tirisfal Glades"}}
items[2210] = {id=2210,name="Battered Buckler",obtain={NpcID=1917,NpcName="Daniel Ulfman",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=4.1,Zone="Tirisfal Glades"}}
items[21022] = {id=21022,name="Weather Beaten Buckler",obtain={NpcID=15372,NpcName="Springpaw Lynx",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.0,Zone="Eversong Woods"}}
items[2362] = {id=2362,name="Worn Wooden Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[24322] = {id=24322,name="Monster - Shield, Blood Elf A02",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[29821] = {id=29821,name="Monster - Shield, Ethereal",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[25082] = {id=25082,name="Fel-Iron Shield",obtain={NpcID=17800,NpcName="Coilfang Myrmidon",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=16.6,Zone="The Steamvault"}}
items[3991] = {id=3991,name="Plated Buckler",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[3988] = {id=3988,name="Plate Wall Shield",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[14982] = {id=14982,name="Exalted Shield",obtain={NpcID=14890,NpcName="Taerar",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=4.1,Zone="Duskwood"}}
items[15687] = {id=15687,name="Triumphant Shield",obtain={NpcID=6109,NpcName="Azuregos",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=3.2,Zone="Azshara"}}
items[10158] = {id=10158,name="Mercurial Guard",obtain={NpcID=11121,NpcName="Black Guard Swordsmith",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Stratholme"}}
items[14812] = {id=14812,name="Warstrike Buckler",obtain={NpcID=15390,NpcName="Captain Xurrem",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Ruins of Ahn'Qiraj"}}
items[15991] = {id=15991,name="Warleader's Shield",obtain={NpcID=14454,NpcName="The Windreaver",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.9,Zone="Silithus"}}
items[15667] = {id=15667,name="Impenetrable Wall",obtain={NpcID=12498,NpcName="Dreamstalker",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.7,Zone="Ashenvale"}}
items[14973] = {id=14973,name="Glorious Shield",obtain={NpcID=7137,NpcName="Immolatus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Felwood"}}
items[14800] = {id=14800,name="Bloodlust Buckler",obtain={NpcID=6584,NpcName="King Mosh",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.2,Zone="Un'Goro Crater"}}
items[15890] = {id=15890,name="Vanguard Shield",obtain={NpcID=10664,NpcName="Scryer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Winterspring"}}
items[8320] = {id=8320,name="Alabaster Shield",obtain={NpcID=10385,NpcName="Ghostly Citizen",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Stratholme"}}
items[10195] = {id=10195,name="Crusader's Shield",obtain={NpcID=9522,NpcName="Blackrock Ambusher",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.8,Zone="Burning Steppes"}}
items[15621] = {id=15621,name="Gryphon Mail Buckler",obtain={NpcID=6130,NpcName="Blue Scalebane",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Azshara"}}
items[2451] = {id=2451,name="Crested Heater Shield",obtain={NpcID=980,NpcName="Grimnal (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Swamp of Sorrows"}}
items[14912] = {id=14912,name="Brutish Shield",obtain={NpcID=6581,NpcName="Ravasaur Matriarch",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Un'Goro Crater"}}
items[7537] = {id=7537,name="Gothic Shield",obtain={NpcID=5720,NpcName="Weaver",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="The Temple of Atal'Hakkar"}}
items[14780] = {id=14780,name="Khan's Buckler",obtain={NpcID=3094,NpcName="Unseen",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone="Duskwood"}}
items[17190] = {id=17190,name="Ornate Buckler",obtain={NpcID=980,NpcName="Grimnal (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Swamp of Sorrows"}}
items[8135] = {id=8135,name="Chromite Shield",obtain={NpcID=4469,NpcName="Emerald Ooze",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="The Hinterlands"}}
items[3989] = {id=3989,name="Blocking Targe",obtain={NpcID=2782,NpcName="Caretaker Alaric",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.9,Zone="Arathi Highlands"}}
items[4068] = {id=4068,name="Chief Brigadier Shield",obtain={NpcID=2763,NpcName="Thenan",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Arathi Highlands"}}
items[4067] = {id=4067,name="Glyphed Buckler",obtain={NpcID=814,NpcName="Sergeant Malthus",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.8,Zone="Stranglethorn Vale"}}
items[15695] = {id=15695,name="Studded Ring Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=5943,Recipe=false,RecipeID=0,DropChance=0,Zone="Desolace"}}
items[2448] = {id=2448,name="Heavy Pavise",obtain={NpcID=1319,NpcName="Bryan Cross (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Stormwind City"}}
items[9873] = {id=9873,name="Renegade Shield",obtain={NpcID=7057,NpcName="Digmaster Shovelphlange",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Unknown"}}
items[14607] = {id=14607,name="Hawkeye's Buckler",obtain={NpcID=4386,NpcName="Withervine Bark Ripper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Dustwallow Marsh"}}
items[4477] = {id=4477,name="Nefarious Buckler",obtain={NpcID=534,NpcName="Nefaru",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=68.9,Zone="Duskwood"}}
items[3817] = {id=3817,name="Reinforced Buckler",obtain={NpcID=3942,NpcName="Mavoris Cloudsbreak",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.2,Zone="Ashenvale"}}
items[15133] = {id=15133,name="Cutthroat's Buckler",obtain={NpcID=4425,NpcName="Blind Hunter",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.9,Zone="Razorfen Kraul"}}
items[6400] = {id=6400,name="Glimmering Shield",obtain={NpcID=14693,NpcName="Scorn",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Scarlet Monastery"}}
items[14608] = {id=14608,name="Dokebi Buckler",obtain={NpcID=5934,NpcName="Heartrazor",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Thousand Needles"}}
items[15530] = {id=15530,name="Sentry's Shield",obtain={NpcID=11682,NpcName="Warsong Grunt",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Ashenvale"}}
items[9804] = {id=9804,name="Superior Buckler",obtain={NpcID=1041,NpcName="Fen Lord",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Wetlands"}}
items[6630] = {id=6630,name="Seedcloud Buckler",obtain={NpcID=5775,NpcName="Verdan the Everliving",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=39.0,Zone="Wailing Caverns"}}
items[15894] = {id=15894,name="Bristlebark Buckler",obtain={NpcID=3815,NpcName="Blink Dragon",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Ashenvale"}}
items[17192] = {id=17192,name="Reinforced Targe",obtain={NpcID=226,NpcName="Morg Gnarltree (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Duskwood"}}
items[14729] = {id=14729,name="War Paint Shield",obtain={NpcID=3295,NpcName="Sludge Beast",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.5,Zone="The Barrens"}}
items[15307] = {id=15307,name="Feral Buckler",obtain={NpcID=3295,NpcName="Sludge Beast",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.7,Zone="The Barrens"}}
items[2216] = {id=2216,name="Simple Buckler",obtain={NpcID=17664,NpcName="Matis the Cruel",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=5.2,Zone="Bloodmyst Isle"}}
items[6559] = {id=6559,name="Bard's Buckler",obtain={NpcID=3533,NpcName="Moonrage Leatherworker",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.5,Zone="Silverpine Forest"}}
items[3651] = {id=3651,name="Veteran Shield",obtain={NpcID=3532,NpcName="Pyrewood Leatherworker",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.1,Zone="Silverpine Forest"}}
items[3653] = {id=3653,name="Ceremonial Buckler",obtain={NpcID=17331,NpcName="Wrathscale Shorestalker",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Bloodmyst Isle"}}
items[3652] = {id=3652,name="Hunting Buckler",obtain={NpcID=2060,NpcName="Councilman Smithers",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Silverpine Forest"}}
items[9764] = {id=9764,name="Cadet Shield",obtain={NpcID=3528,NpcName="Pyrewood Armorer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.8,Zone="Silverpine Forest"}}
items[6203] = {id=6203,name="Thuggish Shield",obtain={NpcID=61,NpcName="Thuros Lightfingers",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=31.3,Zone="Elwynn Forest"}}
items[7109] = {id=7109,name="Pioneer Buckler",obtain={NpcID=15409,NpcName="Old Whitebark",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.2,Zone="Eversong Woods"}}
items[15478] = {id=15478,name="Charger's Shield",obtain={NpcID=15637,NpcName="Withered Green Keeper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.6,Zone="Eversong Woods"}}
items[15895] = {id=15895,name="Burnt Buckler",obtain={NpcID=15408,NpcName="Spearcrafter Otembe",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Eversong Woods"}}
items[2133] = {id=2133,name="Small Shield",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[20984] = {id=20984,name="Recruit's Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[18696] = {id=18696,name="Intricately Runed Shield",obtain={NpcID=10508,NpcName="Ras Frostwhisper",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=15.4,Zone="Scholomance"}}
items[13254] = {id=13254,name="Astral Guard",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[9935] = {id=9935,name="Embossed Plate Shield",obtain={NpcID=14365,NpcName="Thief Catcher Farmountain",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=4.8,Zone="Ironforge"}}
items[15494] = {id=15494,name="Bloodspattered Shield",obtain={NpcID=17322,NpcName="Infected Wildkin",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.4,Zone="Bloodmyst Isle"}}
items[20913] = {id=20913,name="Medium Guard",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[11201] = {id=11201,name="Engineer's Shield 3",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[24038] = {id=24038,name="Monster - Shield, Blood Elf A01",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[25083] = {id=25083,name="Smouldering Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[25078] = {id=25078,name="Zangari Shield",obtain={NpcID=18464,NpcName="Warp Stalker",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.6,Zone="Terokkar Forest"}}
items[30775] = {id=30775,name="Layered Bone Shield",obtain={NpcID=18010,NpcName="Maktu (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Zangarmarsh"}}
items[25072] = {id=25072,name="Northman's Shield",obtain={NpcID=17280,NpcName="Shattered Hand Warhound",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.5,Zone="Hellfire Ramparts"}}
items[11785] = {id=11785,name="Rock Golem Bulwark",obtain={NpcID=8923,NpcName="Panzor the Invincible",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=21.3,Zone="Blackrock Depths"}}
items[186064] = {id=186064,name="Communal Buckler",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[15604] = {id=15604,name="Ancient Defender",obtain={NpcID=11794,NpcName="Sister of Celebrian",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Maraudon"}}
items[15865] = {id=15865,name="Anchorhold Buckler",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=6134,Recipe=false,RecipeID=0,DropChance=0,Zone="Desolace"}}
items[2441] = {id=2441,name="Ringed Buckler",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[1200] = {id=1200,name="Large Wooden Shield",obtain={NpcID=2116,NpcName="Blacksmith Rand (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Tirisfal Glades"}}
items[23365] = {id=23365,name="Steel Rimmed Buckler",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[11199] = {id=11199,name="Engineer's Shield 1",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[11200] = {id=11200,name="Engineer's Shield 2",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[27406] = {id=27406,name="Monster - Shield, Blood Elf (Blood Knight)",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[34553] = {id=34553,name="Monster - Shield, General Tiras",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[34589] = {id=34589,name="Monster - Shield, Shattered Sun D01 Red",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[34590] = {id=34590,name="Monster - Shield, Shattered Sun D01 Yellow",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[35073] = {id=35073,name="Brutal Gladiator's Redoubt",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[32522] = {id=32522,name="Demonic Bulwark",obtain={NpcID=22828,NpcName="Trelopades",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=88.1,Zone="Unknown"}}
items[25081] = {id=25081,name="Bayeaux Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[25077] = {id=25077,name="Modani War-Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[9404] = {id=9404,name="Olaf's All Purpose Shield",obtain={NpcID=6908,NpcName="Olaf",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=12.9,Zone="Uldaman"}}
items[2443] = {id=2443,name="Metal Buckler",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[16788] = {id=16788,name="Captain Rackmore's Wheel",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=6161,Recipe=false,RecipeID=0,DropChance=0,Zone="Desolace"}}
items[2442] = {id=2442,name="Reinforced Targe",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[17188] = {id=17188,name="Ringed Buckler",obtain={NpcID=793,NpcName="Kara Adams (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Redridge Mountains"}}
items[1193] = {id=1193,name="Banded Buckler",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[1167] = {id=1167,name="Small Targe",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[1201] = {id=1201,name="Dull Heater Shield",obtain={NpcID=1249,NpcName="Quartermaster Hudson (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Elwynn Forest"}}
items[2377] = {id=2377,name="Round Buckler",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[1166] = {id=1166,name="Dented Buckler",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[14393] = {id=14393,name="Durability Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[23907] = {id=23907,name="Monster - Shield, Draenei A02 Purple",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[24328] = {id=24328,name="Monster - Shield, Blood Elf A03",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[24331] = {id=24331,name="Monster - Shield, Draenei A02 Gold",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[28737] = {id=28737,name="Monster - Shield, Malistar's Defender",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[15014] = {id=15014,name="Lupine Buckler",obtain={NpcID=5841,NpcName="Rocklance",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="The Barrens"}}
items[2376] = {id=2376,name="Worn Heater Shield",obtain={NpcID=2135,NpcName="Abe Winters (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Tirisfal Glades"}}
items[20911] = {id=20911,name="Light Guard",obtain={NpcID=15292,NpcName="Faraden Thelryn (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Eversong Woods"}}
items[29636] = {id=29636,name="Monster - Shield, Draenei A02 Orange",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[29638] = {id=29638,name="Monster - Shield, Draenei A01 Blue",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[29639] = {id=29639,name="Monster - Shield, Draenei A01 Brown",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[29640] = {id=29640,name="Monster - Shield, Draenei A01 Gold",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[29641] = {id=29641,name="Monster - Shield, Draenei A01 Orange",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[34586] = {id=34586,name="Monster - Shield, Shattered Sun D01 Green",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[34588] = {id=34588,name="Monster - Shield, Shattered Sun D01 Purple",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[33755] = {id=33755,name="Vengeful Gladiator's Shield Wall",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[17106] = {id=17106,name="Malistar's Defender",obtain={NpcID=11502,NpcName="Ragnaros",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=21.2,Zone="Molten Core"}}
items[186063] = {id=186063,name="Communal Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[7748] = {id=7748,name="Forcestone Buckler",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[4263] = {id=4263,name="Standard Issue Shield",obtain={NpcID=1660,NpcName="Scarlet Bodyguard",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=6.0,Zone="Tirisfal Glades"}}
items[17186] = {id=17186,name="Small Targe",obtain={NpcID=1249,NpcName="Quartermaster Hudson (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Elwynn Forest"}}
items[25818] = {id=25818,name="Monster - Shield, Legion",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[27851] = {id=27851,name="Monster - Shield (Broken)",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[29635] = {id=29635,name="Monster - Shield, Draenei A02 Black",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[29637] = {id=29637,name="Monster - Shield, Draenei A02 Red",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[29642] = {id=29642,name="Monster - Shield, Draenei A01 Purple",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[30662] = {id=30662,name="Monster - Shield, Grom'tor",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[31466] = {id=31466,name="Monster - Shield, Illidari Type 1",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[31467] = {id=31467,name="Monster - Shield, Illidari Type 2",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[31468] = {id=31468,name="Monster - Shield, Illidari Type 3",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[32885] = {id=32885,name="Monster - Black Temple - Shield - Bonechewer Shield Disciple",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[32891] = {id=32891,name="Monster - Black Temple - Shield - Illidari Blood Lord",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[33789] = {id=33789,name="Monster - Shield, Zul'gurub",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[34532] = {id=34532,name="Monster - Shield, Shattered Sun Trainee",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[34591] = {id=34591,name="Monster - Shield, Shattered Sun D01 White",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[33309] = {id=33309,name="Merciless Gladiator's Redoubt",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[31415] = {id=31415,name="Iron Oak Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=10771,Recipe=false,RecipeID=0,DropChance=0,Zone="Blade's Edge Mountains"}}
items[13529] = {id=13529,name="Husk of Nerub'enkan",obtain={NpcID=10437,NpcName="Nerub'enkan",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=18.5,Zone="Stratholme"}}
items[11631] = {id=11631,name="Stoneshell Guard",obtain={NpcID=9025,NpcName="Lord Roccor",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=23.2,Zone="Blackrock Depths"}}
items[7331] = {id=7331,name="Phalanx Shield",obtain={NpcID=412,NpcName="Stitches",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Duskwood"}}
items[4444] = {id=4444,name="Black Husk Shield",obtain={NpcID=1112,NpcName="Leech Widow",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=65.5,Zone="Wetlands"}}
items[1557] = {id=1557,name="Buckler of the Seas",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=104,Recipe=false,RecipeID=0,DropChance=0,Zone="Westfall"}}
items[17185] = {id=17185,name="Round Buckler",obtain={NpcID=2135,NpcName="Abe Winters (Purchase)",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=100,Zone="Tirisfal Glades"}}
items[13205] = {id=13205,name="Rhombeard Protector",obtain={NpcID=10268,NpcName="Gizrul the Slavener",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=24.8,Zone="Blackrock Spire"}}
items[7465] = {id=7465,name="Knight's Crest",obtain={NpcID=2416,NpcName="Crushridge Plunderer",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Alterac Mountains"}}
items[5325] = {id=5325,name="Welding Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=true,QuestID=902,Recipe=false,RecipeID=0,DropChance=0,Zone="The Barrens"}}
items[2212] = {id=2212,name="Cracked Buckler",obtain={NpcID=6911,NpcName="Minion of Sethir",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=2.2,Zone="Teldrassil"}}
items[30391] = {id=30391,name="Monster - Shield, Phaseshift Bulwark",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[10365] = {id=10365,name="Emerald Shield",obtain={NpcID=11032,NpcName="Malor the Zealous",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Stratholme"}}
items[3816] = {id=3816,name="Reflective Heater",obtain={NpcID=4394,NpcName="Bubbling Swamp Ooze",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=1.3,Zone="Dustwallow Marsh"}}
items[7188] = {id=7188,name="Stormwind Guard Shield",obtain={NpcID=0,NpcName="Unknown acquisition method",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[25080] = {id=25080,name="Spell-Breaker Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[14842] = {id=14842,name="Tyrant's Shield",obtain={NpcID=4334,NpcName="Firemane Flamecaller",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Dustwallow Marsh"}}
items[4064] = {id=4064,name="Emblazoned Buckler",obtain={NpcID=6391,NpcName="Holdout Warrior",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.2,Zone="Gnomeregan"}}
items[31265] = {id=31265,name="(Action Figure) Human Warrior Shield",obtain={NpcID=0,NpcName="",Kill=false,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0,Zone=""}}
items[6599] = {id=6599,name="Battleforge Shield",obtain={NpcID=14276,NpcName="Scargil",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.3,Zone="Hillsbrad Foothills"}}
items[15332] = {id=15332,name="Wrangler's Buckler",obtain={NpcID=4052,NpcName="Cenarion Druid",Kill=true,Quest=false,QuestID=0,Recipe=false,RecipeID=0,DropChance=0.1,Zone="Stonetalon Mountains"}}


-- Name Data
names["Skullflame Shield"] = 1168
names["Petrified Lichen Guard"] = 25828
names["Aldori Legacy Defender"] = 28825
names["Grand Marshal's Aegis"] = 18825
names["Aegis of the Vindicator"] = 29458
names["Argent Defender"] = 13243
names["The Immovable Object"] = 19321
names["Shield of Impenetrable Darkness"] = 28606
names["Azure-Shield of Coldarra"] = 29266
names["Crest of the Sha'tar"] = 29176
names["High Warlord's Shield Wall"] = 18826
names["Force Reactive Disk"] = 18168
names["Gladiator's Shield Wall"] = 28358
names["Shield of the Void"] = 28166
names["Platinum Shield of the Valorous"] = 27887
names["Mazthoril Honor Shield"] = 29268
names["Shield of the Wayward Footman"] = 31200
names["Triptych Shield of the Ancients"] = 28754
names["Jagged Obsidian Shield"] = 22198
names["Dragonheart Flameshield"] = 28611
names["Thermaplugg's Central Core"] = 9458
names["The Face of Death"] = 23043
names["Bulwark of Azzinoth"] = 32375
names["Stormshield of Renewal"] = 27772
names["Aegis of the Sunbird"] = 28316
names["Blessed Qiraji Bulwark"] = 21269
names["Shield of Condemnation"] = 22819
names["Aegis of the Scarlet Commander"] = 7726
names["The Fel Barrier"] = 32082
names["Blood Knight Defender"] = 27449
names["Crystal Pulse Shield"] = 31292
names["Grand Marshal's Barricade"] = 28940
names["Death's Bargain"] = 23075
names["Light-Bearer's Faith Shield"] = 29267
names["Draconian Aegis of the Legion"] = 22336
names["The Green Tower"] = 1204
names["Crest of Retribution"] = 13375
names["Ogri'la Aegis"] = 32652
names["Netherwing Defender's Shield"] = 31491
names["Draenei Honor Guard Shield"] = 31287
names["Elementium Reinforced Bulwark"] = 19349
names["Antonidas's Aegis of Rapt Concentration"] = 30909
names["Gizlock's Hypertech Buckler"] = 17718
names["Sword Breaker's Bulwark"] = 34185
names["Aegis of the Blood God"] = 19862
names["Aegis of Stormwind"] = 1203
names["Mountainside Buckler"] = 13082
names["Drillborer Disk"] = 17066
names["Bastion of Light"] = 30882
names["Wall of the Dead"] = 1979
names["Phaseshift Bulwark"] = 30314
names["Red Dragonscale Protector"] = 19348
names["Crest of Supremacy"] = 10835
names["Commander's Crest"] = 6320
names["Silvermoon Crest Shield"] = 27910
names["The Plague Bearer"] = 22818
names["Wormscale Blocker"] = 21610
names["Redbeard Crest"] = 12997
names["Large Shield"] = 20912
names["Aegis of Angelic Fortune"] = 34231
names["Spellbreaker's Buckler"] = 30984
names["Worn Turtle Shell Shield"] = 6447
names["Sunward Crest"] = 34675
names["Netherwing Protector's Shield"] = 31490
names["Formidable Crest"] = 15633
names["Kaz'rogal's Hardened Heart"] = 30889
names["Dawnforged Defender"] = 34676
names["Troll Protector"] = 2040
names["Blackskull Shield"] = 1169
names["Illidari Runeshield"] = 34011
names["High Warlord's Barricade"] = 28939
names["Hardened Steel Shield"] = 25075
names["Shield of Thorsen"] = 13079
names["Milli's Shield"] = 18535
names["Heart of Agamaggan"] = 6694
names["Brutal Gladiator's Barrier"] = 34986
names["Observer's Shield"] = 18485
names["Optomatic Deflector"] = 9643
names["Emperor Shield"] = 25073
names["Defender Shield"] = 6572
names["Ancient Draenei Crest"] = 31734
names["Garrett Family Crest"] = 13083
names["Collection Plate"] = 4129
names["Bulwark of the Amani Empire"] = 33326
names["Enamelled Disc of Mojo"] = 33332
names["Barrier Shield"] = 18499
names["Shizzle's Drizzle Blocker"] = 11915
names["Headhunter's Buckler"] = 15352
names["Jade Deflector"] = 14916
names["Razormane War Shield"] = 5094
names["Ebonhold Buckler"] = 8275
names["Deflecting Tower"] = 3987
names["Savage Boar's Guard"] = 10767
names["Techbot CPU Shell"] = 9444
names["Saltstone Shield"] = 14902
names["King's Bulwark"] = 25624
names["Stygian Buckler"] = 23238
names["Buru's Skull Fragment"] = 21485
names["Masterwork Shield"] = 10271
names["Hyperion Shield"] = 10367
names["Draconian Deflector"] = 12602
names["Darrowshire Strongguard"] = 14002
names["Crystaline Shard Shield"] = 34415
names["Kresh's Back"] = 13245
names["Imbued Shield"] = 15943
names["Engraved Wall"] = 10363
names["Heavy Lamellar Shield"] = 10204
names["Symbolic Crest"] = 14825
names["Archer's Buckler"] = 9858
names["Soldier's Shield"] = 6560
names["Brutal Gladiator's Shield Wall"] = 35094
names["Earthen Guard"] = 20688
names["Magnificent Guard"] = 15675
names["Lord Blackwood's Buckler"] = 23139
names["Overlord's Shield"] = 9974
names["Ravager's Shield"] = 14777
names["Field Plate Shield"] = 7496
names["Marauder's Crest"] = 15569
names["Bear Buckler"] = 4821
names["Owl's Disk"] = 4822
names["Infantry Shield"] = 7108
names["Zeth'Gor Shield"] = 25084
names["The Movable Object"] = 25407
names["Demon Guard"] = 10366
names["Dreadguard's Protector"] = 18756
names["Ironhide Shield"] = 15648
names["Captain's Buckler"] = 7495
names["Resplendent Guardian"] = 7787
names["Tower Shield"] = 2222
names["Guardian Buckler"] = 4820
names["Forest Buckler"] = 6383
names["Scouting Buckler"] = 6571
names["Grizzly Buckler"] = 15298
names["War Torn Shield"] = 15486
names["Hero's Buckler"] = 8313
names["Petrified Bark Shield"] = 18352
names["Protective Pavise"] = 3986
names["Champion's Wall Shield"] = 7536
names["Warbringer's Shield"] = 14947
names["Brigade Defender"] = 9918
names["Pathfinder Guard"] = 15342
names["Dervish Buckler"] = 6598
names["Grunt's Shield"] = 15512
names["Rigid Buckler"] = 15113
names["Inscribed Buckler"] = 6380
names["Tribal Buckler"] = 3649
names["Bent Large Shield"] = 2211
names["Small Shield"] = 17184
names["Vengeful Gladiator's Barrier"] = 33661
names["Vengeful Gladiator's Redoubt"] = 33735
names["Felstone Bulwark"] = 32255
names["Dragonscale Shield"] = 25085
names["Screaming Shield"] = 25076
names["Telaari Shield"] = 25074
names["Heroic Guard"] = 15887
names["Ornate Shield"] = 10362
names["Lofty Shield"] = 14930
names["Crested Buckler"] = 3990
names["Protector Buckler"] = 14790
names["Bloodforged Shield"] = 14954
names["Bonelink Wall Shield"] = 15618
names["Jazeraint Shield"] = 9899
names["Jouster's Crest"] = 4070
names["Trickster's Protector"] = 15367
names["Sentinel Buckler"] = 7463
names["Combat Shield"] = 4065
names["Energized Stone Circle"] = 9522
names["Ghostwalker Buckler"] = 15145
names["Metal Buckler"] = 17189
names["Scaled Shield"] = 9830
names["Targe Shield"] = 2221
names["Robust Buckler"] = 15123
names["Kite Shield"] = 2446
names["Outrunner's Shield"] = 15504
names["Burnished Shield"] = 3655
names["Gold-plated Buckler"] = 5443
names["Raider's Shield"] = 9790
names["Wall Shield"] = 1202
names["Wooden Buckler"] = 2214
names["Wooden Shield"] = 2215
names["Warrior's Shield"] = 1438
names["Primal Buckler"] = 15006
names["Worn Large Shield"] = 2213
names["Worn Wooden Buckler"] = 876
names["Merciless Gladiator's Shield Wall"] = 32045
names["Merciless Gladiator's Barrier"] = 33313
names["Outland Shield"] = 25079
names["QR 9922 Shield"] = 25627
names["Zulian Defender"] = 19915
names["Rattlecage Buckler"] = 14528
names["Avalanchion's Stony Hide"] = 18673
names["Templar Shield"] = 10364
names["Merciless Shield"] = 15657
names["High Chief's Shield"] = 14964
names["Revenant Deflector"] = 10093
names["Sunscale Shield"] = 14852
names["Lord's Crest"] = 10078
names["Myrmidon's Defender"] = 8134
names["Valorous Shield"] = 8282
names["Rusted Buckler"] = 2444
names["Warmonger's Buckler"] = 9958
names["Blackforge Buckler"] = 4069
names["Steadfast Buckler"] = 15592
names["Sparkleshell Shield"] = 15584
names["Battered Viking Shield"] = 9403
names["Enduring Shield"] = 15990
names["Visionary Buckler"] = 6828
names["Skullance Shield"] = 13081
names["Pillager's Shield"] = 15563
names["Thick Scale Shield"] = 15552
names["Insignia Buckler"] = 4066
names["Wicked Chain Shield"] = 15543
names["Infiltrator Buckler"] = 7330
names["Banded Shield"] = 9843
names["Slayer's Shield"] = 15892
names["Spiked Chain Shield"] = 15522
names["Lambent Scale Shield"] = 3656
names["Hulking Shield"] = 15891
names["Fortified Shield"] = 9816
names["Box Shield"] = 2220
names["Small Round Shield"] = 2219
names["Large Metal Shield"] = 2445
names["Green Carapace Shield"] = 2021
names["Prospector's Buckler"] = 15893
names["Bandit Buckler"] = 9778
names["Dust Bowl"] = 4290
names["Rectangular Shield"] = 2217
names["Brackwater Shield"] = 3654
names["Banded Buckler"] = 17187
names["Gypsy Buckler"] = 9753
names["Warrior's Buckler"] = 3648
names["Battle Shield"] = 3650
names["Large Round Shield"] = 2129
names["Battered Shield"] = 21021
names["Dented Buckler"] = 17183
names["Battered Buckler"] = 2210
names["Weather Beaten Buckler"] = 21022
names["Worn Wooden Shield"] = 2362
names["Monster - Shield, Blood Elf A02"] = 24322
names["Monster - Shield, Ethereal"] = 29821
names["Fel-Iron Shield"] = 25082
names["Plated Buckler"] = 3991
names["Plate Wall Shield"] = 3988
names["Exalted Shield"] = 14982
names["Triumphant Shield"] = 15687
names["Mercurial Guard"] = 10158
names["Warstrike Buckler"] = 14812
names["Warleader's Shield"] = 15991
names["Impenetrable Wall"] = 15667
names["Glorious Shield"] = 14973
names["Bloodlust Buckler"] = 14800
names["Vanguard Shield"] = 15890
names["Alabaster Shield"] = 8320
names["Crusader's Shield"] = 10195
names["Gryphon Mail Buckler"] = 15621
names["Crested Heater Shield"] = 2451
names["Brutish Shield"] = 14912
names["Gothic Shield"] = 7537
names["Khan's Buckler"] = 14780
names["Ornate Buckler"] = 17190
names["Chromite Shield"] = 8135
names["Blocking Targe"] = 3989
names["Chief Brigadier Shield"] = 4068
names["Glyphed Buckler"] = 4067
names["Studded Ring Shield"] = 15695
names["Heavy Pavise"] = 2448
names["Renegade Shield"] = 9873
names["Hawkeye's Buckler"] = 14607
names["Nefarious Buckler"] = 4477
names["Reinforced Buckler"] = 3817
names["Cutthroat's Buckler"] = 15133
names["Glimmering Shield"] = 6400
names["Dokebi Buckler"] = 14608
names["Sentry's Shield"] = 15530
names["Superior Buckler"] = 9804
names["Seedcloud Buckler"] = 6630
names["Bristlebark Buckler"] = 15894
names["Reinforced Targe"] = 17192
names["War Paint Shield"] = 14729
names["Feral Buckler"] = 15307
names["Simple Buckler"] = 2216
names["Bard's Buckler"] = 6559
names["Veteran Shield"] = 3651
names["Ceremonial Buckler"] = 3653
names["Hunting Buckler"] = 3652
names["Cadet Shield"] = 9764
names["Thuggish Shield"] = 6203
names["Pioneer Buckler"] = 7109
names["Charger's Shield"] = 15478
names["Burnt Buckler"] = 15895
names["Small Shield"] = 2133
names["Recruit's Shield"] = 20984
names["Intricately Runed Shield"] = 18696
names["Astral Guard"] = 13254
names["Embossed Plate Shield"] = 9935
names["Bloodspattered Shield"] = 15494
names["Medium Guard"] = 20913
names["Engineer's Shield 3"] = 11201
names["Monster - Shield, Blood Elf A01"] = 24038
names["Smouldering Shield"] = 25083
names["Zangari Shield"] = 25078
names["Layered Bone Shield"] = 30775
names["Northman's Shield"] = 25072
names["Rock Golem Bulwark"] = 11785
names["Communal Buckler"] = 186064
names["Ancient Defender"] = 15604
names["Anchorhold Buckler"] = 15865
names["Ringed Buckler"] = 2441
names["Large Wooden Shield"] = 1200
names["Steel Rimmed Buckler"] = 23365
names["Engineer's Shield 1"] = 11199
names["Engineer's Shield 2"] = 11200
names["Monster - Shield, Blood Elf (Blood Knight)"] = 27406
names["Monster - Shield, General Tiras"] = 34553
names["Monster - Shield, Shattered Sun D01 Red"] = 34589
names["Monster - Shield, Shattered Sun D01 Yellow"] = 34590
names["Brutal Gladiator's Redoubt"] = 35073
names["Demonic Bulwark"] = 32522
names["Bayeaux Shield"] = 25081
names["Modani War-Shield"] = 25077
names["Olaf's All Purpose Shield"] = 9404
names["Metal Buckler"] = 2443
names["Captain Rackmore's Wheel"] = 16788
names["Reinforced Targe"] = 2442
names["Ringed Buckler"] = 17188
names["Banded Buckler"] = 1193
names["Small Targe"] = 1167
names["Dull Heater Shield"] = 1201
names["Round Buckler"] = 2377
names["Dented Buckler"] = 1166
names["Durability Shield"] = 14393
names["Monster - Shield, Draenei A02 Purple"] = 23907
names["Monster - Shield, Blood Elf A03"] = 24328
names["Monster - Shield, Draenei A02 Gold"] = 24331
names["Monster - Shield, Malistar's Defender"] = 28737
names["Lupine Buckler"] = 15014
names["Worn Heater Shield"] = 2376
names["Light Guard"] = 20911
names["Monster - Shield, Draenei A02 Orange"] = 29636
names["Monster - Shield, Draenei A01 Blue"] = 29638
names["Monster - Shield, Draenei A01 Brown"] = 29639
names["Monster - Shield, Draenei A01 Gold"] = 29640
names["Monster - Shield, Draenei A01 Orange"] = 29641
names["Monster - Shield, Shattered Sun D01 Green"] = 34586
names["Monster - Shield, Shattered Sun D01 Purple"] = 34588
names["Vengeful Gladiator's Shield Wall"] = 33755
names["Malistar's Defender"] = 17106
names["Communal Shield"] = 186063
names["Forcestone Buckler"] = 7748
names["Standard Issue Shield"] = 4263
names["Small Targe"] = 17186
names["Monster - Shield, Legion"] = 25818
names["Monster - Shield (Broken)"] = 27851
names["Monster - Shield, Draenei A02 Black"] = 29635
names["Monster - Shield, Draenei A02 Red"] = 29637
names["Monster - Shield, Draenei A01 Purple"] = 29642
names["Monster - Shield, Grom'tor"] = 30662
names["Monster - Shield, Illidari Type 1"] = 31466
names["Monster - Shield, Illidari Type 2"] = 31467
names["Monster - Shield, Illidari Type 3"] = 31468
names["Monster - Black Temple - Shield - Bonechewer Shield Disciple"] = 32885
names["Monster - Black Temple - Shield - Illidari Blood Lord"] = 32891
names["Monster - Shield, Zul'gurub"] = 33789
names["Monster - Shield, Shattered Sun Trainee"] = 34532
names["Monster - Shield, Shattered Sun D01 White"] = 34591
names["Merciless Gladiator's Redoubt"] = 33309
names["Iron Oak Shield"] = 31415
names["Husk of Nerub'enkan"] = 13529
names["Stoneshell Guard"] = 11631
names["Phalanx Shield"] = 7331
names["Black Husk Shield"] = 4444
names["Buckler of the Seas"] = 1557
names["Round Buckler"] = 17185
names["Rhombeard Protector"] = 13205
names["Knight's Crest"] = 7465
names["Welding Shield"] = 5325
names["Cracked Buckler"] = 2212
names["Monster - Shield, Phaseshift Bulwark"] = 30391
names["Emerald Shield"] = 10365
names["Reflective Heater"] = 3816
names["Stormwind Guard Shield"] = 7188
names["Spell-Breaker Shield"] = 25080
names["Tyrant's Shield"] = 14842
names["Emblazoned Buckler"] = 4064
names["(Action Figure) Human Warrior Shield"] = 31265
names["Battleforge Shield"] = 6599
names["Wrangler's Buckler"] = 15332


LE:RegisterDBItems(items)
LE:RegisterNameDBItems(names)