-------------------------------------**     LibEquippable     **-------------------------------------
-- This file is autogenerated, please do not edit it manually or fuckups might occur.
-------------------------------------**  All Rights Reserved  **-------------------------------------

local LE = LibStub and LibStub("LibEquippable-1.0", true)
if not LE  then return end

local items = {}
local names = {}

items[3342] = {id=3342,name="Captain Sanders' Shirt",source={ID=140,SourceName="Captain Sanders' Hidden Treasure",SourceType="Quest",DropChance="0",Zone="Westfall"}}
items[859] = {id=859,name="Fine Cloth Shirt",source={ID=258,SourceName="A Hunter's Challenge",SourceType="Quest",DropChance="0",Zone="Loch Modan"}}
items[2575] = {id=2575,name="Red Linen Shirt",source={ID=2392,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}

names["Captain Sanders' Shirt"] = 3342
names["Fine Cloth Shirt"] = 859
names["Red Linen Shirt"] = 2575

LE:RegisterDBItems(items)
LE:RegisterNameDBItems(names)