-------------------------------------**     LibEquippable     **-------------------------------------
-- This file is autogenerated, please do not edit it manually or fuckups might occur.
-------------------------------------**  All Rights Reserved  **-------------------------------------

local LE = LibStub and LibStub("LibEquippable-1.0", true)
if not LE  then return end

local items = {}
local names = {}

items[23705] = {id=23705,name="Tabard of Flame",source={ID=65561,SourceName="Tabard of Flame",SourceType="Quest",DropChance="0",Zone="Quests"}}
items[24344] = {id=24344,name="Tabard of the Hand",source={ID=54976,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[22999] = {id=22999,name="Tabard of the Argent Dawn",source={ID=54975,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[25549] = {id=25549,name="Blood Knight Tabard",source={ID=54974,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[20131] = {id=20131,name="Battle Tabard of the Defilers",source={ID=54973,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[28788] = {id=28788,name="Tabard of the Protector",source={ID=55008,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[20132] = {id=20132,name="Arathor Battle Tabard",source={ID=54971,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[35280] = {id=35280,name="Tabard of Summer Flames",source={ID=62769,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[35279] = {id=35279,name="Tabard of Summer Skies",source={ID=62768,SourceName="",SourceType="Recipe",DropChance="0",Zone=""}}
items[32445] = {id=32445,name="Skyguard Tabard",source={ID=5049,SourceName="Lyesa Steelbrow",SourceType="Purchase",DropChance="100",Zone="Ironforge"}}
items[52252] = {id=52252,name="Tabard of the Lightbringer",source={ID=24919,SourceName="The Lightbringer's Redemption",SourceType="Quest",DropChance="0",Zone="Icecrown Citadel"}}

names["Tabard of Flame"] = 23705
names["Tabard of the Hand"] = 24344
names["Tabard of the Argent Dawn"] = 22999
names["Blood Knight Tabard"] = 25549
names["Battle Tabard of the Defilers"] = 20131
names["Tabard of the Protector"] = 28788
names["Arathor Battle Tabard"] = 20132
names["Tabard of Summer Flames"] = 35280
names["Tabard of Summer Skies"] = 35279
names["Skyguard Tabard"] = 32445
names["Tabard of the Lightbringer"] = 52252

LE:RegisterDBItems(items)
LE:RegisterNameDBItems(names)